-- Revert: schemas/myapp_memberships_public/tables/app_permission_default_permissions/constraints/app_permission_default_permissions_permission_id_fkey/constraint


ALTER TABLE myapp_memberships_public.app_permission_default_permissions 
  DROP CONSTRAINT app_permission_default_permissions_permission_id_fkey;


