-- Revert: schemas/myapp_memberships_private/tables/org_hierarchy_sprts/indexes/org_hierarchy_sprts_entity_id_descendant_id_idx


DROP INDEX myapp_memberships_private.org_hierarchy_sprts_entity_id_descendant_id_idx;


