-- Revert: schemas/myapp_profiles_public/tables/app_profile_permissions/triggers/app_profile_permissions_recompute_trg


DROP TRIGGER app_profile_permissions_recompute_trg ON myapp_profiles_public.app_profile_permissions;


