/**
 * AuditLogAuth model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AuditLogAuth,
  AuditLogAuthWithRelations,
  AuditLogAuthSelect,
  AuditLogAuthFilter,
  AuditLogAuthOrderBy,
  CreateAuditLogAuthInput,
  UpdateAuditLogAuthInput,
  AuditLogAuthPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AuditLogAuthModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AuditLogAuthSelect>(
    args: FindManyArgs<S, AuditLogAuthFilter, AuditLogAuthOrderBy> & {
      select: S;
    } & StrictSelect<S, AuditLogAuthSelect>
  ): QueryBuilder<{
    auditLogAuths: ConnectionResult<InferSelectResult<AuditLogAuthWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AuditLogAuth',
      'auditLogAuths',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AuditLogAuthFilter',
      'AuditLogAuthOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AuditLogAuth',
      fieldName: 'auditLogAuths',
      document,
      variables,
    });
  }
  findFirst<S extends AuditLogAuthSelect>(
    args: FindFirstArgs<S, AuditLogAuthFilter, AuditLogAuthOrderBy> & {
      select: S;
    } & StrictSelect<S, AuditLogAuthSelect>
  ): QueryBuilder<{
    auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AuditLogAuth',
      'auditLogAuths',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AuditLogAuthFilter',
      'AuditLogAuthOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AuditLogAuth',
      fieldName: 'auditLogAuth',
      document,
      variables,
      transform: (data: {
        auditLogAuths?: {
          nodes?: InferSelectResult<AuditLogAuthWithRelations, S>[];
        };
      }) => ({
        auditLogAuth: data.auditLogAuths?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AuditLogAuthSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AuditLogAuthSelect>
  ): QueryBuilder<{
    auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AuditLogAuth',
      'auditLogAuths',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AuditLogAuthFilter',
      'AuditLogAuthOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AuditLogAuth',
      fieldName: 'auditLogAuth',
      document,
      variables,
      transform: (data: {
        auditLogAuths?: {
          nodes?: InferSelectResult<AuditLogAuthWithRelations, S>[];
        };
      }) => ({
        auditLogAuth: data.auditLogAuths?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AuditLogAuthSelect>(
    args: CreateArgs<S, CreateAuditLogAuthInput['auditLogAuth']> & {
      select: S;
    } & StrictSelect<S, AuditLogAuthSelect>
  ): QueryBuilder<{
    createAuditLogAuth: {
      auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AuditLogAuth',
      'createAuditLogAuth',
      'auditLogAuth',
      args.select,
      args.data,
      'CreateAuditLogAuthInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AuditLogAuth',
      fieldName: 'createAuditLogAuth',
      document,
      variables,
    });
  }
  update<S extends AuditLogAuthSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
        createdAt: string;
      },
      AuditLogAuthPatch
    > & {
      select: S;
    } & StrictSelect<S, AuditLogAuthSelect>
  ): QueryBuilder<{
    updateAuditLogAuth: {
      auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AuditLogAuth',
      'updateAuditLogAuth',
      'auditLogAuth',
      args.select,
      args.where.id,
      args.data,
      'UpdateAuditLogAuthInput',
      'id',
      'auditLogAuthPatch',
      connectionFieldsMap,
      {
        createdAt: args.where.createdAt,
      }
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AuditLogAuth',
      fieldName: 'updateAuditLogAuth',
      document,
      variables,
    });
  }
  delete<S extends AuditLogAuthSelect>(
    args: DeleteArgs<
      {
        id: string;
        createdAt: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AuditLogAuthSelect>
  ): QueryBuilder<{
    deleteAuditLogAuth: {
      auditLogAuth: InferSelectResult<AuditLogAuthWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AuditLogAuth',
      'deleteAuditLogAuth',
      'auditLogAuth',
      {
        id: args.where.id,
        createdAt: args.where.createdAt,
      },
      'DeleteAuditLogAuthInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AuditLogAuth',
      fieldName: 'deleteAuditLogAuth',
      document,
      variables,
    });
  }
}
