/**
 * Email model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  Email,
  EmailWithRelations,
  EmailSelect,
  EmailFilter,
  EmailOrderBy,
  CreateEmailInput,
  UpdateEmailInput,
  EmailPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class EmailModel {
  constructor(private client: OrmClient) {}
  findMany<S extends EmailSelect>(
    args: FindManyArgs<S, EmailFilter, EmailOrderBy> & {
      select: S;
    } & StrictSelect<S, EmailSelect>
  ): QueryBuilder<{
    emails: ConnectionResult<InferSelectResult<EmailWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Email',
      'emails',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'EmailFilter',
      'EmailOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Email',
      fieldName: 'emails',
      document,
      variables,
    });
  }
  findFirst<S extends EmailSelect>(
    args: FindFirstArgs<S, EmailFilter, EmailOrderBy> & {
      select: S;
    } & StrictSelect<S, EmailSelect>
  ): QueryBuilder<{
    email: InferSelectResult<EmailWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Email',
      'emails',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'EmailFilter',
      'EmailOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Email',
      fieldName: 'email',
      document,
      variables,
      transform: (data: {
        emails?: {
          nodes?: InferSelectResult<EmailWithRelations, S>[];
        };
      }) => ({
        email: data.emails?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends EmailSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, EmailSelect>
  ): QueryBuilder<{
    email: InferSelectResult<EmailWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Email',
      'emails',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'EmailFilter',
      'EmailOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Email',
      fieldName: 'email',
      document,
      variables,
      transform: (data: {
        emails?: {
          nodes?: InferSelectResult<EmailWithRelations, S>[];
        };
      }) => ({
        email: data.emails?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends EmailSelect>(
    args: CreateArgs<S, CreateEmailInput['email']> & {
      select: S;
    } & StrictSelect<S, EmailSelect>
  ): QueryBuilder<{
    createEmail: {
      email: InferSelectResult<EmailWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'Email',
      'createEmail',
      'email',
      args.select,
      args.data,
      'CreateEmailInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Email',
      fieldName: 'createEmail',
      document,
      variables,
    });
  }
  update<S extends EmailSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      EmailPatch
    > & {
      select: S;
    } & StrictSelect<S, EmailSelect>
  ): QueryBuilder<{
    updateEmail: {
      email: InferSelectResult<EmailWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'Email',
      'updateEmail',
      'email',
      args.select,
      args.where.id,
      args.data,
      'UpdateEmailInput',
      'id',
      'emailPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Email',
      fieldName: 'updateEmail',
      document,
      variables,
    });
  }
  delete<S extends EmailSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, EmailSelect>
  ): QueryBuilder<{
    deleteEmail: {
      email: InferSelectResult<EmailWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'Email',
      'deleteEmail',
      'email',
      {
        id: args.where.id,
      },
      'DeleteEmailInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Email',
      fieldName: 'deleteEmail',
      document,
      variables,
    });
  }
}
