/**
 * PhoneNumber model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PhoneNumber,
  PhoneNumberWithRelations,
  PhoneNumberSelect,
  PhoneNumberFilter,
  PhoneNumberOrderBy,
  CreatePhoneNumberInput,
  UpdatePhoneNumberInput,
  PhoneNumberPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PhoneNumberModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PhoneNumberSelect>(
    args: FindManyArgs<S, PhoneNumberFilter, PhoneNumberOrderBy> & {
      select: S;
    } & StrictSelect<S, PhoneNumberSelect>
  ): QueryBuilder<{
    phoneNumbers: ConnectionResult<InferSelectResult<PhoneNumberWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PhoneNumber',
      'phoneNumbers',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PhoneNumberFilter',
      'PhoneNumberOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PhoneNumber',
      fieldName: 'phoneNumbers',
      document,
      variables,
    });
  }
  findFirst<S extends PhoneNumberSelect>(
    args: FindFirstArgs<S, PhoneNumberFilter, PhoneNumberOrderBy> & {
      select: S;
    } & StrictSelect<S, PhoneNumberSelect>
  ): QueryBuilder<{
    phoneNumber: InferSelectResult<PhoneNumberWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PhoneNumber',
      'phoneNumbers',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PhoneNumberFilter',
      'PhoneNumberOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PhoneNumber',
      fieldName: 'phoneNumber',
      document,
      variables,
      transform: (data: {
        phoneNumbers?: {
          nodes?: InferSelectResult<PhoneNumberWithRelations, S>[];
        };
      }) => ({
        phoneNumber: data.phoneNumbers?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PhoneNumberSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PhoneNumberSelect>
  ): QueryBuilder<{
    phoneNumber: InferSelectResult<PhoneNumberWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PhoneNumber',
      'phoneNumbers',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PhoneNumberFilter',
      'PhoneNumberOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PhoneNumber',
      fieldName: 'phoneNumber',
      document,
      variables,
      transform: (data: {
        phoneNumbers?: {
          nodes?: InferSelectResult<PhoneNumberWithRelations, S>[];
        };
      }) => ({
        phoneNumber: data.phoneNumbers?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PhoneNumberSelect>(
    args: CreateArgs<S, CreatePhoneNumberInput['phoneNumber']> & {
      select: S;
    } & StrictSelect<S, PhoneNumberSelect>
  ): QueryBuilder<{
    createPhoneNumber: {
      phoneNumber: InferSelectResult<PhoneNumberWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PhoneNumber',
      'createPhoneNumber',
      'phoneNumber',
      args.select,
      args.data,
      'CreatePhoneNumberInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PhoneNumber',
      fieldName: 'createPhoneNumber',
      document,
      variables,
    });
  }
  update<S extends PhoneNumberSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PhoneNumberPatch
    > & {
      select: S;
    } & StrictSelect<S, PhoneNumberSelect>
  ): QueryBuilder<{
    updatePhoneNumber: {
      phoneNumber: InferSelectResult<PhoneNumberWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PhoneNumber',
      'updatePhoneNumber',
      'phoneNumber',
      args.select,
      args.where.id,
      args.data,
      'UpdatePhoneNumberInput',
      'id',
      'phoneNumberPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PhoneNumber',
      fieldName: 'updatePhoneNumber',
      document,
      variables,
    });
  }
  delete<S extends PhoneNumberSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PhoneNumberSelect>
  ): QueryBuilder<{
    deletePhoneNumber: {
      phoneNumber: InferSelectResult<PhoneNumberWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PhoneNumber',
      'deletePhoneNumber',
      'phoneNumber',
      {
        id: args.where.id,
      },
      'DeletePhoneNumberInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PhoneNumber',
      fieldName: 'deletePhoneNumber',
      document,
      variables,
    });
  }
}
