/**
 * Principal model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  Principal,
  PrincipalWithRelations,
  PrincipalSelect,
  PrincipalFilter,
  PrincipalOrderBy,
  CreatePrincipalInput,
  UpdatePrincipalInput,
  PrincipalPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PrincipalModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PrincipalSelect>(
    args: FindManyArgs<S, PrincipalFilter, PrincipalOrderBy> & {
      select: S;
    } & StrictSelect<S, PrincipalSelect>
  ): QueryBuilder<{
    principals: ConnectionResult<InferSelectResult<PrincipalWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Principal',
      'principals',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PrincipalFilter',
      'PrincipalOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Principal',
      fieldName: 'principals',
      document,
      variables,
    });
  }
  findFirst<S extends PrincipalSelect>(
    args: FindFirstArgs<S, PrincipalFilter, PrincipalOrderBy> & {
      select: S;
    } & StrictSelect<S, PrincipalSelect>
  ): QueryBuilder<{
    principal: InferSelectResult<PrincipalWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Principal',
      'principals',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PrincipalFilter',
      'PrincipalOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Principal',
      fieldName: 'principal',
      document,
      variables,
      transform: (data: {
        principals?: {
          nodes?: InferSelectResult<PrincipalWithRelations, S>[];
        };
      }) => ({
        principal: data.principals?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PrincipalSelect>(
    args: {
      principalId: string;
      select: S;
    } & StrictSelect<S, PrincipalSelect>
  ): QueryBuilder<{
    principal: InferSelectResult<PrincipalWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Principal',
      'principals',
      args.select,
      {
        where: {
          principalId: {
            equalTo: args.principalId,
          },
        },
        first: 1,
      },
      'PrincipalFilter',
      'PrincipalOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Principal',
      fieldName: 'principal',
      document,
      variables,
      transform: (data: {
        principals?: {
          nodes?: InferSelectResult<PrincipalWithRelations, S>[];
        };
      }) => ({
        principal: data.principals?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PrincipalSelect>(
    args: CreateArgs<S, CreatePrincipalInput['principal']> & {
      select: S;
    } & StrictSelect<S, PrincipalSelect>
  ): QueryBuilder<{
    createPrincipal: {
      principal: InferSelectResult<PrincipalWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'Principal',
      'createPrincipal',
      'principal',
      args.select,
      args.data,
      'CreatePrincipalInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Principal',
      fieldName: 'createPrincipal',
      document,
      variables,
    });
  }
}
