/**
 * UserSettingsSecurity model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  UserSettingsSecurity,
  UserSettingsSecurityWithRelations,
  UserSettingsSecuritySelect,
  UserSettingsSecurityFilter,
  UserSettingsSecurityOrderBy,
  CreateUserSettingsSecurityInput,
  UpdateUserSettingsSecurityInput,
  UserSettingsSecurityPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class UserSettingsSecurityModel {
  constructor(private client: OrmClient) {}
  findMany<S extends UserSettingsSecuritySelect>(
    args: FindManyArgs<S, UserSettingsSecurityFilter, UserSettingsSecurityOrderBy> & {
      select: S;
    } & StrictSelect<S, UserSettingsSecuritySelect>
  ): QueryBuilder<{
    userSettingsSecurities: ConnectionResult<
      InferSelectResult<UserSettingsSecurityWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'UserSettingsSecurity',
      'userSettingsSecurities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'UserSettingsSecurityFilter',
      'UserSettingsSecurityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'UserSettingsSecurity',
      fieldName: 'userSettingsSecurities',
      document,
      variables,
    });
  }
  findFirst<S extends UserSettingsSecuritySelect>(
    args: FindFirstArgs<S, UserSettingsSecurityFilter, UserSettingsSecurityOrderBy> & {
      select: S;
    } & StrictSelect<S, UserSettingsSecuritySelect>
  ): QueryBuilder<{
    userSettingsSecurity: InferSelectResult<UserSettingsSecurityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'UserSettingsSecurity',
      'userSettingsSecurities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'UserSettingsSecurityFilter',
      'UserSettingsSecurityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'UserSettingsSecurity',
      fieldName: 'userSettingsSecurity',
      document,
      variables,
      transform: (data: {
        userSettingsSecurities?: {
          nodes?: InferSelectResult<UserSettingsSecurityWithRelations, S>[];
        };
      }) => ({
        userSettingsSecurity: data.userSettingsSecurities?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends UserSettingsSecuritySelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, UserSettingsSecuritySelect>
  ): QueryBuilder<{
    userSettingsSecurity: InferSelectResult<UserSettingsSecurityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'UserSettingsSecurity',
      'userSettingsSecurities',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'UserSettingsSecurityFilter',
      'UserSettingsSecurityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'UserSettingsSecurity',
      fieldName: 'userSettingsSecurity',
      document,
      variables,
      transform: (data: {
        userSettingsSecurities?: {
          nodes?: InferSelectResult<UserSettingsSecurityWithRelations, S>[];
        };
      }) => ({
        userSettingsSecurity: data.userSettingsSecurities?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends UserSettingsSecuritySelect>(
    args: CreateArgs<S, CreateUserSettingsSecurityInput['userSettingsSecurity']> & {
      select: S;
    } & StrictSelect<S, UserSettingsSecuritySelect>
  ): QueryBuilder<{
    createUserSettingsSecurity: {
      userSettingsSecurity: InferSelectResult<UserSettingsSecurityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'UserSettingsSecurity',
      'createUserSettingsSecurity',
      'userSettingsSecurity',
      args.select,
      args.data,
      'CreateUserSettingsSecurityInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'UserSettingsSecurity',
      fieldName: 'createUserSettingsSecurity',
      document,
      variables,
    });
  }
  update<S extends UserSettingsSecuritySelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      UserSettingsSecurityPatch
    > & {
      select: S;
    } & StrictSelect<S, UserSettingsSecuritySelect>
  ): QueryBuilder<{
    updateUserSettingsSecurity: {
      userSettingsSecurity: InferSelectResult<UserSettingsSecurityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'UserSettingsSecurity',
      'updateUserSettingsSecurity',
      'userSettingsSecurity',
      args.select,
      args.where.id,
      args.data,
      'UpdateUserSettingsSecurityInput',
      'id',
      'userSettingsSecurityPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'UserSettingsSecurity',
      fieldName: 'updateUserSettingsSecurity',
      document,
      variables,
    });
  }
  delete<S extends UserSettingsSecuritySelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, UserSettingsSecuritySelect>
  ): QueryBuilder<{
    deleteUserSettingsSecurity: {
      userSettingsSecurity: InferSelectResult<UserSettingsSecurityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'UserSettingsSecurity',
      'deleteUserSettingsSecurity',
      'userSettingsSecurity',
      {
        id: args.where.id,
      },
      'DeleteUserSettingsSecurityInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'UserSettingsSecurity',
      fieldName: 'deleteUserSettingsSecurity',
      document,
      variables,
    });
  }
}
