/**
 * WebauthnCredential model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  WebauthnCredential,
  WebauthnCredentialWithRelations,
  WebauthnCredentialSelect,
  WebauthnCredentialFilter,
  WebauthnCredentialOrderBy,
  CreateWebauthnCredentialInput,
  UpdateWebauthnCredentialInput,
  WebauthnCredentialPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class WebauthnCredentialModel {
  constructor(private client: OrmClient) {}
  findMany<S extends WebauthnCredentialSelect>(
    args: FindManyArgs<S, WebauthnCredentialFilter, WebauthnCredentialOrderBy> & {
      select: S;
    } & StrictSelect<S, WebauthnCredentialSelect>
  ): QueryBuilder<{
    webauthnCredentials: ConnectionResult<InferSelectResult<WebauthnCredentialWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'WebauthnCredential',
      'webauthnCredentials',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'WebauthnCredentialFilter',
      'WebauthnCredentialOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'WebauthnCredential',
      fieldName: 'webauthnCredentials',
      document,
      variables,
    });
  }
  findFirst<S extends WebauthnCredentialSelect>(
    args: FindFirstArgs<S, WebauthnCredentialFilter, WebauthnCredentialOrderBy> & {
      select: S;
    } & StrictSelect<S, WebauthnCredentialSelect>
  ): QueryBuilder<{
    webauthnCredential: InferSelectResult<WebauthnCredentialWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'WebauthnCredential',
      'webauthnCredentials',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'WebauthnCredentialFilter',
      'WebauthnCredentialOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'WebauthnCredential',
      fieldName: 'webauthnCredential',
      document,
      variables,
      transform: (data: {
        webauthnCredentials?: {
          nodes?: InferSelectResult<WebauthnCredentialWithRelations, S>[];
        };
      }) => ({
        webauthnCredential: data.webauthnCredentials?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends WebauthnCredentialSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, WebauthnCredentialSelect>
  ): QueryBuilder<{
    webauthnCredential: InferSelectResult<WebauthnCredentialWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'WebauthnCredential',
      'webauthnCredentials',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'WebauthnCredentialFilter',
      'WebauthnCredentialOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'WebauthnCredential',
      fieldName: 'webauthnCredential',
      document,
      variables,
      transform: (data: {
        webauthnCredentials?: {
          nodes?: InferSelectResult<WebauthnCredentialWithRelations, S>[];
        };
      }) => ({
        webauthnCredential: data.webauthnCredentials?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends WebauthnCredentialSelect>(
    args: CreateArgs<S, CreateWebauthnCredentialInput['webauthnCredential']> & {
      select: S;
    } & StrictSelect<S, WebauthnCredentialSelect>
  ): QueryBuilder<{
    createWebauthnCredential: {
      webauthnCredential: InferSelectResult<WebauthnCredentialWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'WebauthnCredential',
      'createWebauthnCredential',
      'webauthnCredential',
      args.select,
      args.data,
      'CreateWebauthnCredentialInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'WebauthnCredential',
      fieldName: 'createWebauthnCredential',
      document,
      variables,
    });
  }
  update<S extends WebauthnCredentialSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      WebauthnCredentialPatch
    > & {
      select: S;
    } & StrictSelect<S, WebauthnCredentialSelect>
  ): QueryBuilder<{
    updateWebauthnCredential: {
      webauthnCredential: InferSelectResult<WebauthnCredentialWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'WebauthnCredential',
      'updateWebauthnCredential',
      'webauthnCredential',
      args.select,
      args.where.id,
      args.data,
      'UpdateWebauthnCredentialInput',
      'id',
      'webauthnCredentialPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'WebauthnCredential',
      fieldName: 'updateWebauthnCredential',
      document,
      variables,
    });
  }
  delete<S extends WebauthnCredentialSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, WebauthnCredentialSelect>
  ): QueryBuilder<{
    deleteWebauthnCredential: {
      webauthnCredential: InferSelectResult<WebauthnCredentialWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'WebauthnCredential',
      'deleteWebauthnCredential',
      'webauthnCredential',
      {
        id: args.where.id,
      },
      'DeleteWebauthnCredentialInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'WebauthnCredential',
      fieldName: 'deleteWebauthnCredential',
      document,
      variables,
    });
  }
}
