-- Revert: schemas/myapp_profiles_public/tables/app_profile_definition_grants/triggers/app_profile_definition_grants_apply_trg


DROP TRIGGER app_profile_definition_grants_apply_trg ON myapp_profiles_public.app_profile_definition_grants;


