-- Revert: schemas/myapp_profiles_public/tables/app_profile_definition_grants/indexes/app_profile_definition_grants_created_at_idx


DROP INDEX myapp_profiles_public.app_profile_definition_grants_created_at_idx;


