-- Revert: schemas/myapp_limits_private/tables/app_limit_warning_state/constraints/app_limit_warning_states_warning_id_actor_id_key/constraint


ALTER TABLE myapp_limits_private.app_limit_warning_state 
  DROP CONSTRAINT app_limit_warning_states_warning_id_actor_id_key;


