-- Revert: schemas/myapp_profiles_public/tables/org_profile_permissions/indexes/org_profile_permissions_permission_id_idx


DROP INDEX myapp_profiles_public.org_profile_permissions_permission_id_idx;


