/**
 * ORM Client - createClient factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from './client';
import type { OrmClientConfig } from './client';
import { OrgGetManagersRecordModel } from './models/orgGetManagersRecord';
import { OrgGetSubordinatesRecordModel } from './models/orgGetSubordinatesRecord';
import { MyPendingAppInvitesRecordModel } from './models/myPendingAppInvitesRecord';
import { MyPendingOrgInvitesRecordModel } from './models/myPendingOrgInvitesRecord';
import { AppCapabilityModel } from './models/appCapability';
import { AppCapabilityDefaultGrantModel } from './models/appCapabilityDefaultGrant';
import { AppProfileCapabilityModel } from './models/appProfileCapability';
import { AppMembershipModel } from './models/appMembership';
import { AppProfileGrantModel } from './models/appProfileGrant';
import { AppMembershipProfileModel } from './models/appMembershipProfile';
import { AppProfileDefinitionGrantModel } from './models/appProfileDefinitionGrant';
import { AppInviteModel } from './models/appInvite';
import { OrgCapabilityModel } from './models/orgCapability';
import { OrgCapabilityDefaultCapabilityModel } from './models/orgCapabilityDefaultCapability';
import { OrgCapabilityDefaultGrantModel } from './models/orgCapabilityDefaultGrant';
import { OrgProfileCapabilityModel } from './models/orgProfileCapability';
import { OrgMembershipModel } from './models/orgMembership';
import { OrgProfileGrantModel } from './models/orgProfileGrant';
import { OrgMembershipProfileModel } from './models/orgMembershipProfile';
import { OrgProfileDefinitionGrantModel } from './models/orgProfileDefinitionGrant';
import { OrgInviteModel } from './models/orgInvite';
import { OrgMemberModel } from './models/orgMember';
import { AppCapabilityDefaultModel } from './models/appCapabilityDefault';
import { OrgCapabilityDefaultModel } from './models/orgCapabilityDefault';
import { AppCapabilityDefaultCapabilityModel } from './models/appCapabilityDefaultCapability';
import { AppAdminGrantModel } from './models/appAdminGrant';
import { AppOwnerGrantModel } from './models/appOwnerGrant';
import { OrgAdminGrantModel } from './models/orgAdminGrant';
import { OrgOwnerGrantModel } from './models/orgOwnerGrant';
import { OrgChartEdgeGrantModel } from './models/orgChartEdgeGrant';
import { AppClaimedInviteModel } from './models/appClaimedInvite';
import { MembershipTypeModel } from './models/membershipType';
import { AppGrantModel } from './models/appGrant';
import { OrgClaimedInviteModel } from './models/orgClaimedInvite';
import { OrgGrantModel } from './models/orgGrant';
import { OrgChartEdgeModel } from './models/orgChartEdge';
import { AppProfileTemplateModel } from './models/appProfileTemplate';
import { OrgProfileTemplateModel } from './models/orgProfileTemplate';
import { AppMembershipDefaultModel } from './models/appMembershipDefault';
import { OrgMembershipDefaultModel } from './models/orgMembershipDefault';
import { AppProfileModel } from './models/appProfile';
import { OrgProfileModel } from './models/orgProfile';
import { OrgMemberProfileModel } from './models/orgMemberProfile';
import { OrgMembershipSettingModel } from './models/orgMembershipSetting';
import { createQueryOperations } from './query';
import { createMutationOperations } from './mutation';
export type { OrmClientConfig, QueryResult, GraphQLError, GraphQLAdapter } from './client';
export { GraphQLRequestError, FetchAdapter } from './client';
export { QueryBuilder } from './query-builder';
export * from './select-types';
export * from './models';
export { createQueryOperations } from './query';
export { createMutationOperations } from './mutation';
/**
 * Create an ORM client instance
 *
 * @example
 * ```typescript
 * const db = createClient({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer token' },
 * });
 *
 * // Query users
 * const users = await db.user.findMany({
 *   select: { id: true, name: true },
 *   first: 10,
 * }).execute();
 *
 * // Create a user
 * const newUser = await db.user.create({
 *   data: { name: 'John', email: 'john@example.com' },
 *   select: { id: true },
 * }).execute();
 * ```
 */
export function createClient(config: OrmClientConfig) {
  const client = new OrmClient(config);
  return {
    orgGetManagersRecord: new OrgGetManagersRecordModel(client),
    orgGetSubordinatesRecord: new OrgGetSubordinatesRecordModel(client),
    myPendingAppInvitesRecord: new MyPendingAppInvitesRecordModel(client),
    myPendingOrgInvitesRecord: new MyPendingOrgInvitesRecordModel(client),
    appCapability: new AppCapabilityModel(client),
    appCapabilityDefaultGrant: new AppCapabilityDefaultGrantModel(client),
    appProfileCapability: new AppProfileCapabilityModel(client),
    appMembership: new AppMembershipModel(client),
    appProfileGrant: new AppProfileGrantModel(client),
    appMembershipProfile: new AppMembershipProfileModel(client),
    appProfileDefinitionGrant: new AppProfileDefinitionGrantModel(client),
    appInvite: new AppInviteModel(client),
    orgCapability: new OrgCapabilityModel(client),
    orgCapabilityDefaultCapability: new OrgCapabilityDefaultCapabilityModel(client),
    orgCapabilityDefaultGrant: new OrgCapabilityDefaultGrantModel(client),
    orgProfileCapability: new OrgProfileCapabilityModel(client),
    orgMembership: new OrgMembershipModel(client),
    orgProfileGrant: new OrgProfileGrantModel(client),
    orgMembershipProfile: new OrgMembershipProfileModel(client),
    orgProfileDefinitionGrant: new OrgProfileDefinitionGrantModel(client),
    orgInvite: new OrgInviteModel(client),
    orgMember: new OrgMemberModel(client),
    appCapabilityDefault: new AppCapabilityDefaultModel(client),
    orgCapabilityDefault: new OrgCapabilityDefaultModel(client),
    appCapabilityDefaultCapability: new AppCapabilityDefaultCapabilityModel(client),
    appAdminGrant: new AppAdminGrantModel(client),
    appOwnerGrant: new AppOwnerGrantModel(client),
    orgAdminGrant: new OrgAdminGrantModel(client),
    orgOwnerGrant: new OrgOwnerGrantModel(client),
    orgChartEdgeGrant: new OrgChartEdgeGrantModel(client),
    appClaimedInvite: new AppClaimedInviteModel(client),
    membershipType: new MembershipTypeModel(client),
    appGrant: new AppGrantModel(client),
    orgClaimedInvite: new OrgClaimedInviteModel(client),
    orgGrant: new OrgGrantModel(client),
    orgChartEdge: new OrgChartEdgeModel(client),
    appProfileTemplate: new AppProfileTemplateModel(client),
    orgProfileTemplate: new OrgProfileTemplateModel(client),
    appMembershipDefault: new AppMembershipDefaultModel(client),
    orgMembershipDefault: new OrgMembershipDefaultModel(client),
    appProfile: new AppProfileModel(client),
    orgProfile: new OrgProfileModel(client),
    orgMemberProfile: new OrgMemberProfileModel(client),
    orgMembershipSetting: new OrgMembershipSettingModel(client),
    query: createQueryOperations(client),
    mutation: createMutationOperations(client),
  };
}
