-- Verify: schemas/myapp_memberships_public/tables/app_permission_default_permissions/indexes/app_permission_default_permissions_created_at_idx


SELECT verify_index('myapp_memberships_public.app_permission_default_permissions', 'app_permission_default_permissions_created_at_idx');


