-- Verify: schemas/myapp_memberships_public/tables/app_permission_default_grants/indexes/app_permission_default_grants_permission_id_idx


SELECT verify_index('myapp_memberships_public.app_permission_default_grants', 'app_permission_default_grants_permission_id_idx');


