-- Revert: schemas/myapp_events_public/tables/org_level_requirements/indexes/org_level_requirements_name_level_priority_idx


DROP INDEX myapp_events_public.org_level_requirements_name_level_priority_idx;


