-- Revert: schemas/myapp_events_public/tables/org_level_grants/constraints/org_level_grants_actor_id_level_name_period_start_entity_id_key/constraint


ALTER TABLE myapp_events_public.org_level_grants 
  DROP CONSTRAINT org_level_grants_actor_id_level_name_period_start_entity_id_key;


