-- Revert: schemas/myapp_memberships_public/tables/app_memberships/triggers/_00000_app_memberships_default_profile_trg


DROP TRIGGER _00000_app_memberships_default_profile_trg ON myapp_memberships_public.app_memberships;


