-- Revert: schemas/myapp_memberships_public/tables/app_memberships/triggers/_99999_app_memberships_session_banned_trg


DROP TRIGGER _99999_app_memberships_session_banned_trg ON myapp_memberships_public.app_memberships;


