-- Verify: schemas/myapp_memberships_public/tables/org_permission_default_permissions/indexes/org_permission_default_permissions_updated_at_idx


SELECT verify_index('myapp_memberships_public.org_permission_default_permissions', 'org_permission_default_permissions_updated_at_idx');


