-- Revert: schemas/myapp_memberships_public/tables/org_chart_edges/triggers/_00015_org_validate_active_member_insert


DROP TRIGGER _00015_org_validate_active_member_insert ON myapp_memberships_public.org_chart_edges;


