-- Revert: schemas/myapp_profiles_public/tables/app_profile_permissions/indexes/app_profile_permissions_permission_id_idx


DROP INDEX myapp_profiles_public.app_profile_permissions_permission_id_idx;


