-- Verify: schemas/myapp_memberships_public/tables/app_permission_default_permissions/triggers/app_permission_default_permissions_recompute_trg


SELECT verify_trigger('myapp_memberships_public.app_permission_default_permissions_recompute_trg');


