-- Revert: schemas/myapp_memberships_public/tables/org_permission_default_permissions/constraints/org_permission_default_permissions_entity_id_fkey/constraint


ALTER TABLE myapp_memberships_public.org_permission_default_permissions 
  DROP CONSTRAINT org_permission_default_permissions_entity_id_fkey;


