-- Revert: schemas/myapp_memberships_private/tables/org_memberships_sprt/indexes/org_memberships_sprts_actor_id_entity_id_idx


DROP INDEX myapp_memberships_private.org_memberships_sprts_actor_id_entity_id_idx;


