-- Revert: schemas/myapp_memberships_public/tables/app_permission_default_grants/constraints/app_permission_default_grants_permission_id_fkey/constraint


ALTER TABLE myapp_memberships_public.app_permission_default_grants 
  DROP CONSTRAINT app_permission_default_grants_permission_id_fkey;


