-- Revert: schemas/myapp_memberships_public/tables/org_memberships/triggers/_00015_org_memberships_profile_sync_utrg


DROP TRIGGER _00015_org_memberships_profile_sync_utrg ON myapp_memberships_public.org_memberships;


