-- Verify: schemas/myapp_memberships_private/trigger_fns/app_memberships_sprt_to_org_memberships_sprt_tg


SELECT verify_function('myapp_memberships_private.app_memberships_sprt_to_org_memberships_sprt_tg');


