-- Verify: schemas/myapp_memberships_private/trigger_fns/org_permission_default_permissions_recompute_tg


SELECT verify_function('myapp_memberships_private.org_permission_default_permissions_recompute_tg');


