'use client';

import { useState } from 'react';
import { Input } from '@constructive-io/ui/input';
import { Tooltip, TooltipContent, TooltipTrigger } from '@constructive-io/ui/tooltip';
import { CheckIcon, PencilIcon, RotateCcwIcon, Table2, XIcon } from 'lucide-react';

import type { GeneratedField } from '../policy-types';

interface FieldNameMapping {
	/** The policyData key that controls this field's name */
	policyKey: string;
	/** The default value for this field name */
	defaultValue: string;
}

interface AutoGeneratedFieldsInfoProps {
	fields: GeneratedField[];
	/** Current policyData values */
	value?: Record<string, unknown>;
	/** Callback when a field name is changed */
	onChange?: (key: string, value: string) => void;
	/** Mapping from field name to policyData key */
	fieldMappings?: Record<string, FieldNameMapping>;
	/** Whether editing is disabled */
	disabled?: boolean;
}

/**
 * Info box showing fields that will be automatically created by a table module.
 * Supports inline editing of field names when mappings are provided.
 */
export function AutoGeneratedFieldsInfo({
	fields,
	value,
	onChange,
	fieldMappings,
	disabled,
}: AutoGeneratedFieldsInfoProps) {
	const [editingField, setEditingField] = useState<string | null>(null);
	const [editValue, setEditValue] = useState('');

	if (!fields.length) return null;

	const handleStartEdit = (fieldName: string, currentValue: string) => {
		setEditingField(fieldName);
		setEditValue(currentValue);
	};

	const handleSave = (fieldName: string) => {
		const mapping = fieldMappings?.[fieldName];
		if (mapping && onChange && editValue.trim()) {
			onChange(mapping.policyKey, editValue.trim());
		}
		setEditingField(null);
		setEditValue('');
	};

	const handleCancel = () => {
		setEditingField(null);
		setEditValue('');
	};

	const handleKeyDown = (e: React.KeyboardEvent, fieldName: string) => {
		if (e.key === 'Enter') {
			handleSave(fieldName);
		} else if (e.key === 'Escape') {
			handleCancel();
		}
	};

	const getDisplayName = (field: GeneratedField): string => {
		const mapping = fieldMappings?.[field.name];
		if (mapping && value) {
			const customValue = value[mapping.policyKey];
			if (typeof customValue === 'string' && customValue !== mapping.defaultValue) {
				return customValue;
			}
		}
		return field.name;
	};

	const hasFieldMapping = (fieldName: string): boolean => {
		return !!fieldMappings?.[fieldName] && !!onChange;
	};

	const handleReset = (fieldName: string) => {
		const mapping = fieldMappings?.[fieldName];
		if (mapping && onChange) {
			onChange(mapping.policyKey, mapping.defaultValue);
			setEditValue(mapping.defaultValue);
		}
	};

	return (
		<div className='border-border/60 overflow-hidden rounded-lg border'>
			{/* Header */}
			<div className='bg-muted/50 flex items-center gap-2 border-b px-4 py-2.5'>
				<Table2 className='text-muted-foreground h-4 w-4' />
				<span className='text-muted-foreground text-xs font-medium'>The following fields will be auto-generated:</span>
			</div>

			{/* Fields list */}
			<div className='divide-border divide-y'>
				{fields.map((field) => {
					const displayName = getDisplayName(field);
					const canEdit = hasFieldMapping(field.name);
					const isEditing = editingField === field.name;

					return (
						<div key={field.name} className='space-y-1 px-4 py-3'>
							{/* Top row: field name/input + type badge + edit button */}
							<div className='flex items-center gap-2'>
								{isEditing ? (
									<>
										<Input
											type='text'
											value={editValue}
											onChange={(e) => setEditValue(e.target.value)}
											onKeyDown={(e) => handleKeyDown(e, field.name)}
											className='w-40 text-xs'
											size='sm'
											autoFocus
										/>
										<div className='flex items-center gap-0.5'>
											<Tooltip>
												<TooltipTrigger asChild>
													<button
														type='button'
														onClick={() => handleSave(field.name)}
														className='hover:bg-muted text-muted-foreground hover:text-foreground rounded p-1
															transition-colors'
													>
														<CheckIcon className='h-3.5 w-3.5' />
													</button>
												</TooltipTrigger>
												<TooltipContent>Save</TooltipContent>
											</Tooltip>
											<Tooltip>
												<TooltipTrigger asChild>
													<button
														type='button'
														onClick={handleCancel}
														className='hover:bg-muted text-muted-foreground hover:text-foreground rounded p-1
															transition-colors'
													>
														<XIcon className='h-3.5 w-3.5' />
													</button>
												</TooltipTrigger>
												<TooltipContent>Cancel</TooltipContent>
											</Tooltip>
											<Tooltip>
												<TooltipTrigger asChild>
													<button
														type='button'
														onClick={() => handleReset(field.name)}
														className='hover:bg-muted text-muted-foreground hover:text-foreground rounded p-1
															transition-colors'
													>
														<RotateCcwIcon className='h-3.5 w-3.5' />
													</button>
												</TooltipTrigger>
												<TooltipContent>Reset to default</TooltipContent>
											</Tooltip>
										</div>
									</>
								) : (
									<>
										<span className='text-sm font-medium'>{displayName}</span>
										{canEdit && (
											<Tooltip>
												<TooltipTrigger asChild>
													<button
														type='button'
														onClick={() => handleStartEdit(field.name, displayName)}
														disabled={disabled}
														className='hover:bg-muted text-muted-foreground hover:text-foreground rounded p-1 opacity-60
															transition-all hover:opacity-100 disabled:cursor-not-allowed disabled:opacity-30
															disabled:hover:bg-transparent'
													>
														<PencilIcon className='h-3 w-3' />
													</button>
												</TooltipTrigger>
												<TooltipContent>Edit field name</TooltipContent>
											</Tooltip>
										)}
									</>
								)}
								<span className='bg-muted text-muted-foreground rounded px-1.5 py-0.5 font-mono text-[10px] font-medium'>
									{field.type}
								</span>
							</div>

							{/* Bottom row: description */}
							<p className='text-muted-foreground text-xs'>{field.description}</p>
						</div>
					);
				})}
			</div>
		</div>
	);
}
