/**
 * Custom query operations
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import { QueryBuilder, buildCustomDocument } from '../query-builder';
import type { InferSelectResult, StrictSelect } from '../select-types';
import type { AppCapabilityConnection, OrgCapabilityConnection } from '../input-types';
import { connectionFieldsMap } from '../input-types';
export interface AppCapabilitiesGetPaddedMaskVariables {
  mask?: string;
}
export interface OrgCapabilitiesGetPaddedMaskVariables {
  mask?: string;
}
export interface OrgIsManagerOfVariables {
  targetEntityId?: string;
  managerId?: string;
  userId?: string;
  maxDepth?: number;
}
export interface AppCapabilitiesGetMaskVariables {
  ids?: string[];
}
export interface OrgCapabilitiesGetMaskVariables {
  ids?: string[];
}
export interface GetOrganizationIdVariables {
  entityType?: string;
  entityId?: string;
}
export interface AppCapabilitiesGetMaskByNamesVariables {
  names?: string[];
}
export interface OrgCapabilitiesGetMaskByNamesVariables {
  names?: string[];
}
export interface AppCapabilitiesGetByMaskVariables {
  mask?: string;
  /** Only read the first `n` values of the set. */
  first?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
}
export interface OrgCapabilitiesGetByMaskVariables {
  mask?: string;
  /** Only read the first `n` values of the set. */
  first?: number;
  /**
   * Skip the first `n` values from our `after` cursor, an alternative to cursor
   * based pagination. May not be used with `last`.
   */
  offset?: number;
  /** Read all values in the set after (below) this cursor. */
  after?: string;
}
export function createQueryOperations(client: OrmClient) {
  return {
    appCapabilitiesGetPaddedMask: (
      args: AppCapabilitiesGetPaddedMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appCapabilitiesGetPaddedMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppCapabilitiesGetPaddedMask',
        fieldName: 'appCapabilitiesGetPaddedMask',
        ...buildCustomDocument(
          'query',
          'AppCapabilitiesGetPaddedMask',
          'appCapabilitiesGetPaddedMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgCapabilitiesGetPaddedMask: (
      args: OrgCapabilitiesGetPaddedMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgCapabilitiesGetPaddedMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgCapabilitiesGetPaddedMask',
        fieldName: 'orgCapabilitiesGetPaddedMask',
        ...buildCustomDocument(
          'query',
          'OrgCapabilitiesGetPaddedMask',
          'orgCapabilitiesGetPaddedMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgIsManagerOf: (
      args: OrgIsManagerOfVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgIsManagerOf: boolean | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgIsManagerOf',
        fieldName: 'orgIsManagerOf',
        ...buildCustomDocument(
          'query',
          'OrgIsManagerOf',
          'orgIsManagerOf',
          options?.select,
          args,
          [
            {
              name: 'targetEntityId',
              type: 'UUID',
            },
            {
              name: 'managerId',
              type: 'UUID',
            },
            {
              name: 'userId',
              type: 'UUID',
            },
            {
              name: 'maxDepth',
              type: 'Int',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appCapabilitiesGetMask: (
      args: AppCapabilitiesGetMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appCapabilitiesGetMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppCapabilitiesGetMask',
        fieldName: 'appCapabilitiesGetMask',
        ...buildCustomDocument(
          'query',
          'AppCapabilitiesGetMask',
          'appCapabilitiesGetMask',
          options?.select,
          args,
          [
            {
              name: 'ids',
              type: '[UUID]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgCapabilitiesGetMask: (
      args: OrgCapabilitiesGetMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgCapabilitiesGetMask: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgCapabilitiesGetMask',
        fieldName: 'orgCapabilitiesGetMask',
        ...buildCustomDocument(
          'query',
          'OrgCapabilitiesGetMask',
          'orgCapabilitiesGetMask',
          options?.select,
          args,
          [
            {
              name: 'ids',
              type: '[UUID]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    getOrganizationId: (
      args: GetOrganizationIdVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        getOrganizationId: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'GetOrganizationId',
        fieldName: 'getOrganizationId',
        ...buildCustomDocument(
          'query',
          'GetOrganizationId',
          'getOrganizationId',
          options?.select,
          args,
          [
            {
              name: 'entityType',
              type: 'String',
            },
            {
              name: 'entityId',
              type: 'UUID',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appCapabilitiesGetMaskByNames: (
      args: AppCapabilitiesGetMaskByNamesVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appCapabilitiesGetMaskByNames: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppCapabilitiesGetMaskByNames',
        fieldName: 'appCapabilitiesGetMaskByNames',
        ...buildCustomDocument(
          'query',
          'AppCapabilitiesGetMaskByNames',
          'appCapabilitiesGetMaskByNames',
          options?.select,
          args,
          [
            {
              name: 'names',
              type: '[String]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgCapabilitiesGetMaskByNames: (
      args: OrgCapabilitiesGetMaskByNamesVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgCapabilitiesGetMaskByNames: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgCapabilitiesGetMaskByNames',
        fieldName: 'orgCapabilitiesGetMaskByNames',
        ...buildCustomDocument(
          'query',
          'OrgCapabilitiesGetMaskByNames',
          'orgCapabilitiesGetMaskByNames',
          options?.select,
          args,
          [
            {
              name: 'names',
              type: '[String]',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    appCapabilitiesGetByMask: (
      args: AppCapabilitiesGetByMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        appCapabilitiesGetByMask: AppCapabilityConnection | null;
      }>({
        client,
        operation: 'query',
        operationName: 'AppCapabilitiesGetByMask',
        fieldName: 'appCapabilitiesGetByMask',
        ...buildCustomDocument(
          'query',
          'AppCapabilitiesGetByMask',
          'appCapabilitiesGetByMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
            {
              name: 'first',
              type: 'Int',
            },
            {
              name: 'offset',
              type: 'Int',
            },
            {
              name: 'after',
              type: 'Cursor',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    orgCapabilitiesGetByMask: (
      args: OrgCapabilitiesGetByMaskVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        orgCapabilitiesGetByMask: OrgCapabilityConnection | null;
      }>({
        client,
        operation: 'query',
        operationName: 'OrgCapabilitiesGetByMask',
        fieldName: 'orgCapabilitiesGetByMask',
        ...buildCustomDocument(
          'query',
          'OrgCapabilitiesGetByMask',
          'orgCapabilitiesGetByMask',
          options?.select,
          args,
          [
            {
              name: 'mask',
              type: 'BitString',
            },
            {
              name: 'first',
              type: 'Int',
            },
            {
              name: 'offset',
              type: 'Int',
            },
            {
              name: 'after',
              type: 'Cursor',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
  };
}
