/**
 * Custom query hook for getMfaStatus
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { GetMfaStatusRecordSelect, GetMfaStatusRecord } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { GetMfaStatusRecordSelect } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const getMfaStatusQueryKey = customQueryKeys.getMfaStatus;
/**
 * Query hook for getMfaStatus
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useGetMfaStatusQuery({ selection: { fields: { id: true } } });
 *
 * if (data?.getMfaStatus) {
 *   console.log(data.getMfaStatus);
 * }
 * ```
 */
export function useGetMfaStatusQuery<
  S extends GetMfaStatusRecordSelect,
  TData = {
    getMfaStatus: InferSelectResult<GetMfaStatusRecord, S> | null;
  },
>(
  params: {
    selection: {
      fields: S & GetMfaStatusRecordSelect;
    } & HookStrictSelect<NoInfer<S>, GetMfaStatusRecordSelect>;
  } & Omit<
    UseQueryOptions<
      {
        getMfaStatus: InferSelectResult<GetMfaStatusRecord, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useGetMfaStatusQuery(
  params: {
    selection: SelectionConfig<GetMfaStatusRecordSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<GetMfaStatusRecordSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: getMfaStatusQueryKey(),
    queryFn: () =>
      getClient()
        .query.getMfaStatus({
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch getMfaStatus without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchGetMfaStatusQuery({ selection: { fields: { id: true } } });
 * ```
 */
export async function fetchGetMfaStatusQuery<S extends GetMfaStatusRecordSelect>(params: {
  selection: {
    fields: S & GetMfaStatusRecordSelect;
  } & HookStrictSelect<NoInfer<S>, GetMfaStatusRecordSelect>;
}): Promise<{
  getMfaStatus: InferSelectResult<GetMfaStatusRecord, S> | null;
}>;
export async function fetchGetMfaStatusQuery(params: {
  selection: SelectionConfig<GetMfaStatusRecordSelect>;
}) {
  const args = buildSelectionArgs<GetMfaStatusRecordSelect>(params.selection);
  return getClient()
    .query.getMfaStatus({
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch getMfaStatus for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchGetMfaStatusQuery(queryClient, { selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchGetMfaStatusQuery<S extends GetMfaStatusRecordSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S & GetMfaStatusRecordSelect;
    } & HookStrictSelect<NoInfer<S>, GetMfaStatusRecordSelect>;
  }
): Promise<void>;
export async function prefetchGetMfaStatusQuery(
  queryClient: QueryClient,
  params: {
    selection: SelectionConfig<GetMfaStatusRecordSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<GetMfaStatusRecordSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: getMfaStatusQueryKey(),
    queryFn: () =>
      getClient()
        .query.getMfaStatus({
          select: args.select,
        })
        .unwrap(),
  });
}
