/**
 * Custom query hook for isVerificationExempt
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { IsVerificationExemptVariables } from '../../orm/query';
export type { IsVerificationExemptVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const isVerificationExemptQueryKey = customQueryKeys.isVerificationExempt;
/**
 * Query hook for isVerificationExempt
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useIsVerificationExemptQuery({ variables: { userId } });
 *
 * if (data?.isVerificationExempt) {
 *   console.log(data.isVerificationExempt);
 * }
 * ```
 */
export function useIsVerificationExemptQuery<
  TData = {
    isVerificationExempt: boolean | null;
  },
>(
  params?: {
    variables?: IsVerificationExemptVariables;
  } & Omit<
    UseQueryOptions<
      {
        isVerificationExempt: boolean | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useIsVerificationExemptQuery<
  TData = {
    isVerificationExempt: boolean | null;
  },
>(
  params?: {
    variables?: IsVerificationExemptVariables;
  } & Omit<
    UseQueryOptions<
      {
        isVerificationExempt: boolean | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: isVerificationExemptQueryKey(variables),
    queryFn: () => getClient().query.isVerificationExempt(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch isVerificationExempt without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchIsVerificationExemptQuery({ variables: { userId } });
 * ```
 */
export async function fetchIsVerificationExemptQuery(params?: {
  variables?: IsVerificationExemptVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.isVerificationExempt(variables).unwrap();
}
/**
 * Prefetch isVerificationExempt for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchIsVerificationExemptQuery(queryClient, { variables: { userId } });
 * ```
 */
export async function prefetchIsVerificationExemptQuery(
  queryClient: QueryClient,
  params?: {
    variables?: IsVerificationExemptVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: isVerificationExemptQueryKey(variables),
    queryFn: () => getClient().query.isVerificationExempt(variables).unwrap(),
  });
}
