/**
 * Per-user security settings for MFA configuration (separate from user_settings preferences)
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { userSettingsSecurityKeys } from '../query-keys';
import type {
  UserSettingsSecuritySelect,
  UserSettingsSecurityWithRelations,
  UserSettingsSecurityFilter,
  UserSettingsSecurityOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  UserSettingsSecuritySelect,
  UserSettingsSecurityWithRelations,
  UserSettingsSecurityFilter,
  UserSettingsSecurityOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const userSettingsSecuritiesQueryKey = userSettingsSecurityKeys.list;
/**
 * Per-user security settings for MFA configuration (separate from user_settings preferences)
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useUserSettingsSecuritiesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useUserSettingsSecuritiesQuery<
  S extends UserSettingsSecuritySelect,
  TData = {
    userSettingsSecurities: ConnectionResult<
      InferSelectResult<UserSettingsSecurityWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, UserSettingsSecurityFilter, UserSettingsSecurityOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, UserSettingsSecuritySelect>;
  } & Omit<
    UseQueryOptions<
      {
        userSettingsSecurities: ConnectionResult<
          InferSelectResult<UserSettingsSecurityWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useUserSettingsSecuritiesQuery(
  params: {
    selection: ListSelectionConfig<
      UserSettingsSecuritySelect,
      UserSettingsSecurityFilter,
      UserSettingsSecurityOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    UserSettingsSecuritySelect,
    UserSettingsSecurityFilter,
    UserSettingsSecurityOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: userSettingsSecurityKeys.list(args),
    queryFn: () => getClient().userSettingsSecurity.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Per-user security settings for MFA configuration (separate from user_settings preferences)
 *
 * @example
 * ```ts
 * const data = await fetchUserSettingsSecuritiesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchUserSettingsSecuritiesQuery<
  S extends UserSettingsSecuritySelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, UserSettingsSecurityFilter, UserSettingsSecurityOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, UserSettingsSecuritySelect>;
}): Promise<{
  userSettingsSecurities: ConnectionResult<InferSelectResult<UserSettingsSecurityWithRelations, S>>;
}>;
export async function fetchUserSettingsSecuritiesQuery(params: {
  selection: ListSelectionConfig<
    UserSettingsSecuritySelect,
    UserSettingsSecurityFilter,
    UserSettingsSecurityOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    UserSettingsSecuritySelect,
    UserSettingsSecurityFilter,
    UserSettingsSecurityOrderBy
  >(params.selection);
  return getClient().userSettingsSecurity.findMany(args).unwrap();
}
/**
 * Per-user security settings for MFA configuration (separate from user_settings preferences)
 *
 * @example
 * ```ts
 * await prefetchUserSettingsSecuritiesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchUserSettingsSecuritiesQuery<S extends UserSettingsSecuritySelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, UserSettingsSecurityFilter, UserSettingsSecurityOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, UserSettingsSecuritySelect>;
  }
): Promise<void>;
export async function prefetchUserSettingsSecuritiesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      UserSettingsSecuritySelect,
      UserSettingsSecurityFilter,
      UserSettingsSecurityOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    UserSettingsSecuritySelect,
    UserSettingsSecurityFilter,
    UserSettingsSecurityOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: userSettingsSecurityKeys.list(args),
    queryFn: () => getClient().userSettingsSecurity.findMany(args).unwrap(),
  });
}
