-- Revert: schemas/myapp_memberships_public/tables/org_permission_default_permissions/indexes/org_permission_default_permissions_updated_at_idx


DROP INDEX myapp_memberships_public.org_permission_default_permissions_updated_at_idx;


