-- Revert: schemas/myapp_memberships_public/tables/app_permission_default_grants/indexes/app_permission_default_grants_created_at_idx


DROP INDEX myapp_memberships_public.app_permission_default_grants_created_at_idx;


