-- Revert: schemas/myapp_memberships_public/tables/app_permission_default_grants/indexes/app_permission_default_grants_permission_id_idx


DROP INDEX myapp_memberships_public.app_permission_default_grants_permission_id_idx;


