/**
 * AppCapabilityDefaultCapability model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppCapabilityDefaultCapability,
  AppCapabilityDefaultCapabilityWithRelations,
  AppCapabilityDefaultCapabilitySelect,
  AppCapabilityDefaultCapabilityFilter,
  AppCapabilityDefaultCapabilityOrderBy,
  CreateAppCapabilityDefaultCapabilityInput,
  UpdateAppCapabilityDefaultCapabilityInput,
  AppCapabilityDefaultCapabilityPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppCapabilityDefaultCapabilityModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppCapabilityDefaultCapabilitySelect>(
    args: FindManyArgs<
      S,
      AppCapabilityDefaultCapabilityFilter,
      AppCapabilityDefaultCapabilityOrderBy
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultCapabilitySelect>
  ): QueryBuilder<{
    appCapabilityDefaultCapabilities: ConnectionResult<
      InferSelectResult<AppCapabilityDefaultCapabilityWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapabilityDefaultCapability',
      'appCapabilityDefaultCapabilities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppCapabilityDefaultCapabilityFilter',
      'AppCapabilityDefaultCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefaultCapability',
      fieldName: 'appCapabilityDefaultCapabilities',
      document,
      variables,
    });
  }
  findFirst<S extends AppCapabilityDefaultCapabilitySelect>(
    args: FindFirstArgs<
      S,
      AppCapabilityDefaultCapabilityFilter,
      AppCapabilityDefaultCapabilityOrderBy
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultCapabilitySelect>
  ): QueryBuilder<{
    appCapabilityDefaultCapability: InferSelectResult<
      AppCapabilityDefaultCapabilityWithRelations,
      S
    > | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppCapabilityDefaultCapability',
      'appCapabilityDefaultCapabilities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppCapabilityDefaultCapabilityFilter',
      'AppCapabilityDefaultCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefaultCapability',
      fieldName: 'appCapabilityDefaultCapability',
      document,
      variables,
      transform: (data: {
        appCapabilityDefaultCapabilities?: {
          nodes?: InferSelectResult<AppCapabilityDefaultCapabilityWithRelations, S>[];
        };
      }) => ({
        appCapabilityDefaultCapability: data.appCapabilityDefaultCapabilities?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppCapabilityDefaultCapabilitySelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultCapabilitySelect>
  ): QueryBuilder<{
    appCapabilityDefaultCapability: InferSelectResult<
      AppCapabilityDefaultCapabilityWithRelations,
      S
    > | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapabilityDefaultCapability',
      'appCapabilityDefaultCapabilities',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppCapabilityDefaultCapabilityFilter',
      'AppCapabilityDefaultCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefaultCapability',
      fieldName: 'appCapabilityDefaultCapability',
      document,
      variables,
      transform: (data: {
        appCapabilityDefaultCapabilities?: {
          nodes?: InferSelectResult<AppCapabilityDefaultCapabilityWithRelations, S>[];
        };
      }) => ({
        appCapabilityDefaultCapability: data.appCapabilityDefaultCapabilities?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppCapabilityDefaultCapabilitySelect>(
    args: CreateArgs<
      S,
      CreateAppCapabilityDefaultCapabilityInput['appCapabilityDefaultCapability']
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultCapabilitySelect>
  ): QueryBuilder<{
    createAppCapabilityDefaultCapability: {
      appCapabilityDefaultCapability: InferSelectResult<
        AppCapabilityDefaultCapabilityWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppCapabilityDefaultCapability',
      'createAppCapabilityDefaultCapability',
      'appCapabilityDefaultCapability',
      args.select,
      args.data,
      'CreateAppCapabilityDefaultCapabilityInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefaultCapability',
      fieldName: 'createAppCapabilityDefaultCapability',
      document,
      variables,
    });
  }
  update<S extends AppCapabilityDefaultCapabilitySelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppCapabilityDefaultCapabilityPatch
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultCapabilitySelect>
  ): QueryBuilder<{
    updateAppCapabilityDefaultCapability: {
      appCapabilityDefaultCapability: InferSelectResult<
        AppCapabilityDefaultCapabilityWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppCapabilityDefaultCapability',
      'updateAppCapabilityDefaultCapability',
      'appCapabilityDefaultCapability',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppCapabilityDefaultCapabilityInput',
      'id',
      'appCapabilityDefaultCapabilityPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefaultCapability',
      fieldName: 'updateAppCapabilityDefaultCapability',
      document,
      variables,
    });
  }
  delete<S extends AppCapabilityDefaultCapabilitySelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultCapabilitySelect>
  ): QueryBuilder<{
    deleteAppCapabilityDefaultCapability: {
      appCapabilityDefaultCapability: InferSelectResult<
        AppCapabilityDefaultCapabilityWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppCapabilityDefaultCapability',
      'deleteAppCapabilityDefaultCapability',
      'appCapabilityDefaultCapability',
      {
        id: args.where.id,
      },
      'DeleteAppCapabilityDefaultCapabilityInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefaultCapability',
      fieldName: 'deleteAppCapabilityDefaultCapability',
      document,
      variables,
    });
  }
}
