/**
 * AppCapability model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppCapability,
  AppCapabilityWithRelations,
  AppCapabilitySelect,
  AppCapabilityFilter,
  AppCapabilityOrderBy,
  CreateAppCapabilityInput,
  UpdateAppCapabilityInput,
  AppCapabilityPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppCapabilityModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppCapabilitySelect>(
    args: FindManyArgs<S, AppCapabilityFilter, AppCapabilityOrderBy> & {
      select: S;
    } & StrictSelect<S, AppCapabilitySelect>
  ): QueryBuilder<{
    appCapabilities: ConnectionResult<InferSelectResult<AppCapabilityWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapability',
      'appCapabilities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppCapabilityFilter',
      'AppCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapability',
      fieldName: 'appCapabilities',
      document,
      variables,
    });
  }
  findFirst<S extends AppCapabilitySelect>(
    args: FindFirstArgs<S, AppCapabilityFilter, AppCapabilityOrderBy> & {
      select: S;
    } & StrictSelect<S, AppCapabilitySelect>
  ): QueryBuilder<{
    appCapability: InferSelectResult<AppCapabilityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppCapability',
      'appCapabilities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppCapabilityFilter',
      'AppCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapability',
      fieldName: 'appCapability',
      document,
      variables,
      transform: (data: {
        appCapabilities?: {
          nodes?: InferSelectResult<AppCapabilityWithRelations, S>[];
        };
      }) => ({
        appCapability: data.appCapabilities?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppCapabilitySelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppCapabilitySelect>
  ): QueryBuilder<{
    appCapability: InferSelectResult<AppCapabilityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapability',
      'appCapabilities',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppCapabilityFilter',
      'AppCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapability',
      fieldName: 'appCapability',
      document,
      variables,
      transform: (data: {
        appCapabilities?: {
          nodes?: InferSelectResult<AppCapabilityWithRelations, S>[];
        };
      }) => ({
        appCapability: data.appCapabilities?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppCapabilitySelect>(
    args: CreateArgs<S, CreateAppCapabilityInput['appCapability']> & {
      select: S;
    } & StrictSelect<S, AppCapabilitySelect>
  ): QueryBuilder<{
    createAppCapability: {
      appCapability: InferSelectResult<AppCapabilityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppCapability',
      'createAppCapability',
      'appCapability',
      args.select,
      args.data,
      'CreateAppCapabilityInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapability',
      fieldName: 'createAppCapability',
      document,
      variables,
    });
  }
  update<S extends AppCapabilitySelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppCapabilityPatch
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilitySelect>
  ): QueryBuilder<{
    updateAppCapability: {
      appCapability: InferSelectResult<AppCapabilityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppCapability',
      'updateAppCapability',
      'appCapability',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppCapabilityInput',
      'id',
      'appCapabilityPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapability',
      fieldName: 'updateAppCapability',
      document,
      variables,
    });
  }
  delete<S extends AppCapabilitySelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilitySelect>
  ): QueryBuilder<{
    deleteAppCapability: {
      appCapability: InferSelectResult<AppCapabilityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppCapability',
      'deleteAppCapability',
      'appCapability',
      {
        id: args.where.id,
      },
      'DeleteAppCapabilityInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapability',
      fieldName: 'deleteAppCapability',
      document,
      variables,
    });
  }
}
