/**
 * AppCapabilityDefaultGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppCapabilityDefaultGrant,
  AppCapabilityDefaultGrantWithRelations,
  AppCapabilityDefaultGrantSelect,
  AppCapabilityDefaultGrantFilter,
  AppCapabilityDefaultGrantOrderBy,
  CreateAppCapabilityDefaultGrantInput,
  UpdateAppCapabilityDefaultGrantInput,
  AppCapabilityDefaultGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppCapabilityDefaultGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppCapabilityDefaultGrantSelect>(
    args: FindManyArgs<S, AppCapabilityDefaultGrantFilter, AppCapabilityDefaultGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultGrantSelect>
  ): QueryBuilder<{
    appCapabilityDefaultGrants: ConnectionResult<
      InferSelectResult<AppCapabilityDefaultGrantWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapabilityDefaultGrant',
      'appCapabilityDefaultGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppCapabilityDefaultGrantFilter',
      'AppCapabilityDefaultGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefaultGrant',
      fieldName: 'appCapabilityDefaultGrants',
      document,
      variables,
    });
  }
  findFirst<S extends AppCapabilityDefaultGrantSelect>(
    args: FindFirstArgs<S, AppCapabilityDefaultGrantFilter, AppCapabilityDefaultGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultGrantSelect>
  ): QueryBuilder<{
    appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppCapabilityDefaultGrant',
      'appCapabilityDefaultGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppCapabilityDefaultGrantFilter',
      'AppCapabilityDefaultGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefaultGrant',
      fieldName: 'appCapabilityDefaultGrant',
      document,
      variables,
      transform: (data: {
        appCapabilityDefaultGrants?: {
          nodes?: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S>[];
        };
      }) => ({
        appCapabilityDefaultGrant: data.appCapabilityDefaultGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppCapabilityDefaultGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultGrantSelect>
  ): QueryBuilder<{
    appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapabilityDefaultGrant',
      'appCapabilityDefaultGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppCapabilityDefaultGrantFilter',
      'AppCapabilityDefaultGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefaultGrant',
      fieldName: 'appCapabilityDefaultGrant',
      document,
      variables,
      transform: (data: {
        appCapabilityDefaultGrants?: {
          nodes?: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S>[];
        };
      }) => ({
        appCapabilityDefaultGrant: data.appCapabilityDefaultGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppCapabilityDefaultGrantSelect>(
    args: CreateArgs<S, CreateAppCapabilityDefaultGrantInput['appCapabilityDefaultGrant']> & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultGrantSelect>
  ): QueryBuilder<{
    createAppCapabilityDefaultGrant: {
      appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppCapabilityDefaultGrant',
      'createAppCapabilityDefaultGrant',
      'appCapabilityDefaultGrant',
      args.select,
      args.data,
      'CreateAppCapabilityDefaultGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefaultGrant',
      fieldName: 'createAppCapabilityDefaultGrant',
      document,
      variables,
    });
  }
  update<S extends AppCapabilityDefaultGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppCapabilityDefaultGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultGrantSelect>
  ): QueryBuilder<{
    updateAppCapabilityDefaultGrant: {
      appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppCapabilityDefaultGrant',
      'updateAppCapabilityDefaultGrant',
      'appCapabilityDefaultGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppCapabilityDefaultGrantInput',
      'id',
      'appCapabilityDefaultGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefaultGrant',
      fieldName: 'updateAppCapabilityDefaultGrant',
      document,
      variables,
    });
  }
  delete<S extends AppCapabilityDefaultGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultGrantSelect>
  ): QueryBuilder<{
    deleteAppCapabilityDefaultGrant: {
      appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppCapabilityDefaultGrant',
      'deleteAppCapabilityDefaultGrant',
      'appCapabilityDefaultGrant',
      {
        id: args.where.id,
      },
      'DeleteAppCapabilityDefaultGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefaultGrant',
      fieldName: 'deleteAppCapabilityDefaultGrant',
      document,
      variables,
    });
  }
}
