/**
 * AppCapabilityDefault model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppCapabilityDefault,
  AppCapabilityDefaultWithRelations,
  AppCapabilityDefaultSelect,
  AppCapabilityDefaultFilter,
  AppCapabilityDefaultOrderBy,
  CreateAppCapabilityDefaultInput,
  UpdateAppCapabilityDefaultInput,
  AppCapabilityDefaultPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppCapabilityDefaultModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppCapabilityDefaultSelect>(
    args: FindManyArgs<S, AppCapabilityDefaultFilter, AppCapabilityDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultSelect>
  ): QueryBuilder<{
    appCapabilityDefaults: ConnectionResult<
      InferSelectResult<AppCapabilityDefaultWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapabilityDefault',
      'appCapabilityDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppCapabilityDefaultFilter',
      'AppCapabilityDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefault',
      fieldName: 'appCapabilityDefaults',
      document,
      variables,
    });
  }
  findFirst<S extends AppCapabilityDefaultSelect>(
    args: FindFirstArgs<S, AppCapabilityDefaultFilter, AppCapabilityDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultSelect>
  ): QueryBuilder<{
    appCapabilityDefault: InferSelectResult<AppCapabilityDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppCapabilityDefault',
      'appCapabilityDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppCapabilityDefaultFilter',
      'AppCapabilityDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefault',
      fieldName: 'appCapabilityDefault',
      document,
      variables,
      transform: (data: {
        appCapabilityDefaults?: {
          nodes?: InferSelectResult<AppCapabilityDefaultWithRelations, S>[];
        };
      }) => ({
        appCapabilityDefault: data.appCapabilityDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppCapabilityDefaultSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultSelect>
  ): QueryBuilder<{
    appCapabilityDefault: InferSelectResult<AppCapabilityDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppCapabilityDefault',
      'appCapabilityDefaults',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppCapabilityDefaultFilter',
      'AppCapabilityDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppCapabilityDefault',
      fieldName: 'appCapabilityDefault',
      document,
      variables,
      transform: (data: {
        appCapabilityDefaults?: {
          nodes?: InferSelectResult<AppCapabilityDefaultWithRelations, S>[];
        };
      }) => ({
        appCapabilityDefault: data.appCapabilityDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppCapabilityDefaultSelect>(
    args: CreateArgs<S, CreateAppCapabilityDefaultInput['appCapabilityDefault']> & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultSelect>
  ): QueryBuilder<{
    createAppCapabilityDefault: {
      appCapabilityDefault: InferSelectResult<AppCapabilityDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppCapabilityDefault',
      'createAppCapabilityDefault',
      'appCapabilityDefault',
      args.select,
      args.data,
      'CreateAppCapabilityDefaultInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefault',
      fieldName: 'createAppCapabilityDefault',
      document,
      variables,
    });
  }
  update<S extends AppCapabilityDefaultSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppCapabilityDefaultPatch
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultSelect>
  ): QueryBuilder<{
    updateAppCapabilityDefault: {
      appCapabilityDefault: InferSelectResult<AppCapabilityDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppCapabilityDefault',
      'updateAppCapabilityDefault',
      'appCapabilityDefault',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppCapabilityDefaultInput',
      'id',
      'appCapabilityDefaultPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefault',
      fieldName: 'updateAppCapabilityDefault',
      document,
      variables,
    });
  }
  delete<S extends AppCapabilityDefaultSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppCapabilityDefaultSelect>
  ): QueryBuilder<{
    deleteAppCapabilityDefault: {
      appCapabilityDefault: InferSelectResult<AppCapabilityDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppCapabilityDefault',
      'deleteAppCapabilityDefault',
      'appCapabilityDefault',
      {
        id: args.where.id,
      },
      'DeleteAppCapabilityDefaultInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppCapabilityDefault',
      fieldName: 'deleteAppCapabilityDefault',
      document,
      variables,
    });
  }
}
