/**
 * AppMembership model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppMembership,
  AppMembershipWithRelations,
  AppMembershipSelect,
  AppMembershipFilter,
  AppMembershipOrderBy,
  CreateAppMembershipInput,
  UpdateAppMembershipInput,
  AppMembershipPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppMembershipModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppMembershipSelect>(
    args: FindManyArgs<S, AppMembershipFilter, AppMembershipOrderBy> & {
      select: S;
    } & StrictSelect<S, AppMembershipSelect>
  ): QueryBuilder<{
    appMemberships: ConnectionResult<InferSelectResult<AppMembershipWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppMembership',
      'appMemberships',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppMembershipFilter',
      'AppMembershipOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppMembership',
      fieldName: 'appMemberships',
      document,
      variables,
    });
  }
  findFirst<S extends AppMembershipSelect>(
    args: FindFirstArgs<S, AppMembershipFilter, AppMembershipOrderBy> & {
      select: S;
    } & StrictSelect<S, AppMembershipSelect>
  ): QueryBuilder<{
    appMembership: InferSelectResult<AppMembershipWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppMembership',
      'appMemberships',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppMembershipFilter',
      'AppMembershipOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppMembership',
      fieldName: 'appMembership',
      document,
      variables,
      transform: (data: {
        appMemberships?: {
          nodes?: InferSelectResult<AppMembershipWithRelations, S>[];
        };
      }) => ({
        appMembership: data.appMemberships?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppMembershipSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppMembershipSelect>
  ): QueryBuilder<{
    appMembership: InferSelectResult<AppMembershipWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppMembership',
      'appMemberships',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppMembershipFilter',
      'AppMembershipOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppMembership',
      fieldName: 'appMembership',
      document,
      variables,
      transform: (data: {
        appMemberships?: {
          nodes?: InferSelectResult<AppMembershipWithRelations, S>[];
        };
      }) => ({
        appMembership: data.appMemberships?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppMembershipSelect>(
    args: CreateArgs<S, CreateAppMembershipInput['appMembership']> & {
      select: S;
    } & StrictSelect<S, AppMembershipSelect>
  ): QueryBuilder<{
    createAppMembership: {
      appMembership: InferSelectResult<AppMembershipWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppMembership',
      'createAppMembership',
      'appMembership',
      args.select,
      args.data,
      'CreateAppMembershipInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppMembership',
      fieldName: 'createAppMembership',
      document,
      variables,
    });
  }
  update<S extends AppMembershipSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppMembershipPatch
    > & {
      select: S;
    } & StrictSelect<S, AppMembershipSelect>
  ): QueryBuilder<{
    updateAppMembership: {
      appMembership: InferSelectResult<AppMembershipWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppMembership',
      'updateAppMembership',
      'appMembership',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppMembershipInput',
      'id',
      'appMembershipPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppMembership',
      fieldName: 'updateAppMembership',
      document,
      variables,
    });
  }
  delete<S extends AppMembershipSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppMembershipSelect>
  ): QueryBuilder<{
    deleteAppMembership: {
      appMembership: InferSelectResult<AppMembershipWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppMembership',
      'deleteAppMembership',
      'appMembership',
      {
        id: args.where.id,
      },
      'DeleteAppMembershipInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppMembership',
      fieldName: 'deleteAppMembership',
      document,
      variables,
    });
  }
}
