/**
 * AppProfileGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppProfileGrant,
  AppProfileGrantWithRelations,
  AppProfileGrantSelect,
  AppProfileGrantFilter,
  AppProfileGrantOrderBy,
  CreateAppProfileGrantInput,
  UpdateAppProfileGrantInput,
  AppProfileGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppProfileGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppProfileGrantSelect>(
    args: FindManyArgs<S, AppProfileGrantFilter, AppProfileGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfileGrantSelect>
  ): QueryBuilder<{
    appProfileGrants: ConnectionResult<InferSelectResult<AppProfileGrantWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfileGrant',
      'appProfileGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppProfileGrantFilter',
      'AppProfileGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileGrant',
      fieldName: 'appProfileGrants',
      document,
      variables,
    });
  }
  findFirst<S extends AppProfileGrantSelect>(
    args: FindFirstArgs<S, AppProfileGrantFilter, AppProfileGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfileGrantSelect>
  ): QueryBuilder<{
    appProfileGrant: InferSelectResult<AppProfileGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppProfileGrant',
      'appProfileGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppProfileGrantFilter',
      'AppProfileGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileGrant',
      fieldName: 'appProfileGrant',
      document,
      variables,
      transform: (data: {
        appProfileGrants?: {
          nodes?: InferSelectResult<AppProfileGrantWithRelations, S>[];
        };
      }) => ({
        appProfileGrant: data.appProfileGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppProfileGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppProfileGrantSelect>
  ): QueryBuilder<{
    appProfileGrant: InferSelectResult<AppProfileGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfileGrant',
      'appProfileGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppProfileGrantFilter',
      'AppProfileGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileGrant',
      fieldName: 'appProfileGrant',
      document,
      variables,
      transform: (data: {
        appProfileGrants?: {
          nodes?: InferSelectResult<AppProfileGrantWithRelations, S>[];
        };
      }) => ({
        appProfileGrant: data.appProfileGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppProfileGrantSelect>(
    args: CreateArgs<S, CreateAppProfileGrantInput['appProfileGrant']> & {
      select: S;
    } & StrictSelect<S, AppProfileGrantSelect>
  ): QueryBuilder<{
    createAppProfileGrant: {
      appProfileGrant: InferSelectResult<AppProfileGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppProfileGrant',
      'createAppProfileGrant',
      'appProfileGrant',
      args.select,
      args.data,
      'CreateAppProfileGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileGrant',
      fieldName: 'createAppProfileGrant',
      document,
      variables,
    });
  }
  update<S extends AppProfileGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppProfileGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, AppProfileGrantSelect>
  ): QueryBuilder<{
    updateAppProfileGrant: {
      appProfileGrant: InferSelectResult<AppProfileGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppProfileGrant',
      'updateAppProfileGrant',
      'appProfileGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppProfileGrantInput',
      'id',
      'appProfileGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileGrant',
      fieldName: 'updateAppProfileGrant',
      document,
      variables,
    });
  }
  delete<S extends AppProfileGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppProfileGrantSelect>
  ): QueryBuilder<{
    deleteAppProfileGrant: {
      appProfileGrant: InferSelectResult<AppProfileGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppProfileGrant',
      'deleteAppProfileGrant',
      'appProfileGrant',
      {
        id: args.where.id,
      },
      'DeleteAppProfileGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileGrant',
      fieldName: 'deleteAppProfileGrant',
      document,
      variables,
    });
  }
}
