/**
 * AppProfileDefinitionGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppProfileDefinitionGrant,
  AppProfileDefinitionGrantWithRelations,
  AppProfileDefinitionGrantSelect,
  AppProfileDefinitionGrantFilter,
  AppProfileDefinitionGrantOrderBy,
  CreateAppProfileDefinitionGrantInput,
  UpdateAppProfileDefinitionGrantInput,
  AppProfileDefinitionGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppProfileDefinitionGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppProfileDefinitionGrantSelect>(
    args: FindManyArgs<S, AppProfileDefinitionGrantFilter, AppProfileDefinitionGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    appProfileDefinitionGrants: ConnectionResult<
      InferSelectResult<AppProfileDefinitionGrantWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfileDefinitionGrant',
      'appProfileDefinitionGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppProfileDefinitionGrantFilter',
      'AppProfileDefinitionGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileDefinitionGrant',
      fieldName: 'appProfileDefinitionGrants',
      document,
      variables,
    });
  }
  findFirst<S extends AppProfileDefinitionGrantSelect>(
    args: FindFirstArgs<S, AppProfileDefinitionGrantFilter, AppProfileDefinitionGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    appProfileDefinitionGrant: InferSelectResult<AppProfileDefinitionGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppProfileDefinitionGrant',
      'appProfileDefinitionGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppProfileDefinitionGrantFilter',
      'AppProfileDefinitionGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileDefinitionGrant',
      fieldName: 'appProfileDefinitionGrant',
      document,
      variables,
      transform: (data: {
        appProfileDefinitionGrants?: {
          nodes?: InferSelectResult<AppProfileDefinitionGrantWithRelations, S>[];
        };
      }) => ({
        appProfileDefinitionGrant: data.appProfileDefinitionGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppProfileDefinitionGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    appProfileDefinitionGrant: InferSelectResult<AppProfileDefinitionGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfileDefinitionGrant',
      'appProfileDefinitionGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppProfileDefinitionGrantFilter',
      'AppProfileDefinitionGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileDefinitionGrant',
      fieldName: 'appProfileDefinitionGrant',
      document,
      variables,
      transform: (data: {
        appProfileDefinitionGrants?: {
          nodes?: InferSelectResult<AppProfileDefinitionGrantWithRelations, S>[];
        };
      }) => ({
        appProfileDefinitionGrant: data.appProfileDefinitionGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppProfileDefinitionGrantSelect>(
    args: CreateArgs<S, CreateAppProfileDefinitionGrantInput['appProfileDefinitionGrant']> & {
      select: S;
    } & StrictSelect<S, AppProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    createAppProfileDefinitionGrant: {
      appProfileDefinitionGrant: InferSelectResult<AppProfileDefinitionGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppProfileDefinitionGrant',
      'createAppProfileDefinitionGrant',
      'appProfileDefinitionGrant',
      args.select,
      args.data,
      'CreateAppProfileDefinitionGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileDefinitionGrant',
      fieldName: 'createAppProfileDefinitionGrant',
      document,
      variables,
    });
  }
  update<S extends AppProfileDefinitionGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppProfileDefinitionGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, AppProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    updateAppProfileDefinitionGrant: {
      appProfileDefinitionGrant: InferSelectResult<AppProfileDefinitionGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppProfileDefinitionGrant',
      'updateAppProfileDefinitionGrant',
      'appProfileDefinitionGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppProfileDefinitionGrantInput',
      'id',
      'appProfileDefinitionGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileDefinitionGrant',
      fieldName: 'updateAppProfileDefinitionGrant',
      document,
      variables,
    });
  }
  delete<S extends AppProfileDefinitionGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    deleteAppProfileDefinitionGrant: {
      appProfileDefinitionGrant: InferSelectResult<AppProfileDefinitionGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppProfileDefinitionGrant',
      'deleteAppProfileDefinitionGrant',
      'appProfileDefinitionGrant',
      {
        id: args.where.id,
      },
      'DeleteAppProfileDefinitionGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileDefinitionGrant',
      fieldName: 'deleteAppProfileDefinitionGrant',
      document,
      variables,
    });
  }
}
