/**
 * AppProfileTemplate model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppProfileTemplate,
  AppProfileTemplateWithRelations,
  AppProfileTemplateSelect,
  AppProfileTemplateFilter,
  AppProfileTemplateOrderBy,
  CreateAppProfileTemplateInput,
  UpdateAppProfileTemplateInput,
  AppProfileTemplatePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppProfileTemplateModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppProfileTemplateSelect>(
    args: FindManyArgs<S, AppProfileTemplateFilter, AppProfileTemplateOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfileTemplateSelect>
  ): QueryBuilder<{
    appProfileTemplates: ConnectionResult<InferSelectResult<AppProfileTemplateWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfileTemplate',
      'appProfileTemplates',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppProfileTemplateFilter',
      'AppProfileTemplateOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileTemplate',
      fieldName: 'appProfileTemplates',
      document,
      variables,
    });
  }
  findFirst<S extends AppProfileTemplateSelect>(
    args: FindFirstArgs<S, AppProfileTemplateFilter, AppProfileTemplateOrderBy> & {
      select: S;
    } & StrictSelect<S, AppProfileTemplateSelect>
  ): QueryBuilder<{
    appProfileTemplate: InferSelectResult<AppProfileTemplateWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppProfileTemplate',
      'appProfileTemplates',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppProfileTemplateFilter',
      'AppProfileTemplateOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileTemplate',
      fieldName: 'appProfileTemplate',
      document,
      variables,
      transform: (data: {
        appProfileTemplates?: {
          nodes?: InferSelectResult<AppProfileTemplateWithRelations, S>[];
        };
      }) => ({
        appProfileTemplate: data.appProfileTemplates?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppProfileTemplateSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppProfileTemplateSelect>
  ): QueryBuilder<{
    appProfileTemplate: InferSelectResult<AppProfileTemplateWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppProfileTemplate',
      'appProfileTemplates',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppProfileTemplateFilter',
      'AppProfileTemplateOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppProfileTemplate',
      fieldName: 'appProfileTemplate',
      document,
      variables,
      transform: (data: {
        appProfileTemplates?: {
          nodes?: InferSelectResult<AppProfileTemplateWithRelations, S>[];
        };
      }) => ({
        appProfileTemplate: data.appProfileTemplates?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppProfileTemplateSelect>(
    args: CreateArgs<S, CreateAppProfileTemplateInput['appProfileTemplate']> & {
      select: S;
    } & StrictSelect<S, AppProfileTemplateSelect>
  ): QueryBuilder<{
    createAppProfileTemplate: {
      appProfileTemplate: InferSelectResult<AppProfileTemplateWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppProfileTemplate',
      'createAppProfileTemplate',
      'appProfileTemplate',
      args.select,
      args.data,
      'CreateAppProfileTemplateInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileTemplate',
      fieldName: 'createAppProfileTemplate',
      document,
      variables,
    });
  }
  update<S extends AppProfileTemplateSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppProfileTemplatePatch
    > & {
      select: S;
    } & StrictSelect<S, AppProfileTemplateSelect>
  ): QueryBuilder<{
    updateAppProfileTemplate: {
      appProfileTemplate: InferSelectResult<AppProfileTemplateWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppProfileTemplate',
      'updateAppProfileTemplate',
      'appProfileTemplate',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppProfileTemplateInput',
      'id',
      'appProfileTemplatePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileTemplate',
      fieldName: 'updateAppProfileTemplate',
      document,
      variables,
    });
  }
  delete<S extends AppProfileTemplateSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppProfileTemplateSelect>
  ): QueryBuilder<{
    deleteAppProfileTemplate: {
      appProfileTemplate: InferSelectResult<AppProfileTemplateWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppProfileTemplate',
      'deleteAppProfileTemplate',
      'appProfileTemplate',
      {
        id: args.where.id,
      },
      'DeleteAppProfileTemplateInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppProfileTemplate',
      fieldName: 'deleteAppProfileTemplate',
      document,
      variables,
    });
  }
}
