/**
 * MembershipType model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  MembershipType,
  MembershipTypeWithRelations,
  MembershipTypeSelect,
  MembershipTypeFilter,
  MembershipTypeOrderBy,
  CreateMembershipTypeInput,
  UpdateMembershipTypeInput,
  MembershipTypePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class MembershipTypeModel {
  constructor(private client: OrmClient) {}
  findMany<S extends MembershipTypeSelect>(
    args: FindManyArgs<S, MembershipTypeFilter, MembershipTypeOrderBy> & {
      select: S;
    } & StrictSelect<S, MembershipTypeSelect>
  ): QueryBuilder<{
    membershipTypes: ConnectionResult<InferSelectResult<MembershipTypeWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'MembershipType',
      'membershipTypes',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'MembershipTypeFilter',
      'MembershipTypeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'MembershipType',
      fieldName: 'membershipTypes',
      document,
      variables,
    });
  }
  findFirst<S extends MembershipTypeSelect>(
    args: FindFirstArgs<S, MembershipTypeFilter, MembershipTypeOrderBy> & {
      select: S;
    } & StrictSelect<S, MembershipTypeSelect>
  ): QueryBuilder<{
    membershipType: InferSelectResult<MembershipTypeWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'MembershipType',
      'membershipTypes',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'MembershipTypeFilter',
      'MembershipTypeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'MembershipType',
      fieldName: 'membershipType',
      document,
      variables,
      transform: (data: {
        membershipTypes?: {
          nodes?: InferSelectResult<MembershipTypeWithRelations, S>[];
        };
      }) => ({
        membershipType: data.membershipTypes?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends MembershipTypeSelect>(
    args: {
      id: number;
      select: S;
    } & StrictSelect<S, MembershipTypeSelect>
  ): QueryBuilder<{
    membershipType: InferSelectResult<MembershipTypeWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'MembershipType',
      'membershipTypes',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'MembershipTypeFilter',
      'MembershipTypeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'MembershipType',
      fieldName: 'membershipType',
      document,
      variables,
      transform: (data: {
        membershipTypes?: {
          nodes?: InferSelectResult<MembershipTypeWithRelations, S>[];
        };
      }) => ({
        membershipType: data.membershipTypes?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends MembershipTypeSelect>(
    args: CreateArgs<S, CreateMembershipTypeInput['membershipType']> & {
      select: S;
    } & StrictSelect<S, MembershipTypeSelect>
  ): QueryBuilder<{
    createMembershipType: {
      membershipType: InferSelectResult<MembershipTypeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'MembershipType',
      'createMembershipType',
      'membershipType',
      args.select,
      args.data,
      'CreateMembershipTypeInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'MembershipType',
      fieldName: 'createMembershipType',
      document,
      variables,
    });
  }
  update<S extends MembershipTypeSelect>(
    args: UpdateArgs<
      S,
      {
        id: number;
      },
      MembershipTypePatch
    > & {
      select: S;
    } & StrictSelect<S, MembershipTypeSelect>
  ): QueryBuilder<{
    updateMembershipType: {
      membershipType: InferSelectResult<MembershipTypeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'MembershipType',
      'updateMembershipType',
      'membershipType',
      args.select,
      args.where.id,
      args.data,
      'UpdateMembershipTypeInput',
      'id',
      'membershipTypePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'MembershipType',
      fieldName: 'updateMembershipType',
      document,
      variables,
    });
  }
  delete<S extends MembershipTypeSelect>(
    args: DeleteArgs<
      {
        id: number;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, MembershipTypeSelect>
  ): QueryBuilder<{
    deleteMembershipType: {
      membershipType: InferSelectResult<MembershipTypeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'MembershipType',
      'deleteMembershipType',
      'membershipType',
      {
        id: args.where.id,
      },
      'DeleteMembershipTypeInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'MembershipType',
      fieldName: 'deleteMembershipType',
      document,
      variables,
    });
  }
}
