/**
 * MyPendingOrgInvitesRecord model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  MyPendingOrgInvitesRecord,
  MyPendingOrgInvitesRecordWithRelations,
  MyPendingOrgInvitesRecordSelect,
  MyPendingOrgInvitesRecordFilter,
  MyPendingOrgInvitesRecordsOrderBy,
  CreateMyPendingOrgInvitesRecordInput,
  UpdateMyPendingOrgInvitesRecordInput,
  MyPendingOrgInvitesRecordPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class MyPendingOrgInvitesRecordModel {
  constructor(private client: OrmClient) {}
  findMany<S extends MyPendingOrgInvitesRecordSelect>(
    args: FindManyArgs<S, MyPendingOrgInvitesRecordFilter, MyPendingOrgInvitesRecordsOrderBy> & {
      select: S;
    } & StrictSelect<S, MyPendingOrgInvitesRecordSelect>
  ): QueryBuilder<{
    myPendingOrgInvites: ConnectionResult<
      InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'MyPendingOrgInvitesRecord',
      'myPendingOrgInvites',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'MyPendingOrgInvitesRecordFilter',
      'MyPendingOrgInvitesRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'MyPendingOrgInvitesRecord',
      fieldName: 'myPendingOrgInvites',
      document,
      variables,
    });
  }
  findFirst<S extends MyPendingOrgInvitesRecordSelect>(
    args: FindFirstArgs<S, MyPendingOrgInvitesRecordFilter, MyPendingOrgInvitesRecordsOrderBy> & {
      select: S;
    } & StrictSelect<S, MyPendingOrgInvitesRecordSelect>
  ): QueryBuilder<{
    myPendingOrgInvitesRecord: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'MyPendingOrgInvitesRecord',
      'myPendingOrgInvites',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'MyPendingOrgInvitesRecordFilter',
      'MyPendingOrgInvitesRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'MyPendingOrgInvitesRecord',
      fieldName: 'myPendingOrgInvitesRecord',
      document,
      variables,
      transform: (data: {
        myPendingOrgInvites?: {
          nodes?: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>[];
        };
      }) => ({
        myPendingOrgInvitesRecord: data.myPendingOrgInvites?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends MyPendingOrgInvitesRecordSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, MyPendingOrgInvitesRecordSelect>
  ): QueryBuilder<{
    myPendingOrgInvitesRecord: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'MyPendingOrgInvitesRecord',
      'myPendingOrgInvites',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'MyPendingOrgInvitesRecordFilter',
      'MyPendingOrgInvitesRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'MyPendingOrgInvitesRecord',
      fieldName: 'myPendingOrgInvitesRecord',
      document,
      variables,
      transform: (data: {
        myPendingOrgInvites?: {
          nodes?: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>[];
        };
      }) => ({
        myPendingOrgInvitesRecord: data.myPendingOrgInvites?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends MyPendingOrgInvitesRecordSelect>(
    args: CreateArgs<S, CreateMyPendingOrgInvitesRecordInput['myPendingOrgInvitesRecord']> & {
      select: S;
    } & StrictSelect<S, MyPendingOrgInvitesRecordSelect>
  ): QueryBuilder<{
    createMyPendingOrgInvitesRecord: {
      myPendingOrgInvitesRecord: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'MyPendingOrgInvitesRecord',
      'createMyPendingOrgInvitesRecord',
      'myPendingOrgInvitesRecord',
      args.select,
      args.data,
      'CreateMyPendingOrgInvitesRecordInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'MyPendingOrgInvitesRecord',
      fieldName: 'createMyPendingOrgInvitesRecord',
      document,
      variables,
    });
  }
}
