/**
 * OrgClaimedInvite model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgClaimedInvite,
  OrgClaimedInviteWithRelations,
  OrgClaimedInviteSelect,
  OrgClaimedInviteFilter,
  OrgClaimedInviteOrderBy,
  CreateOrgClaimedInviteInput,
  UpdateOrgClaimedInviteInput,
  OrgClaimedInvitePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgClaimedInviteModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgClaimedInviteSelect>(
    args: FindManyArgs<S, OrgClaimedInviteFilter, OrgClaimedInviteOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgClaimedInviteSelect>
  ): QueryBuilder<{
    orgClaimedInvites: ConnectionResult<InferSelectResult<OrgClaimedInviteWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgClaimedInvite',
      'orgClaimedInvites',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgClaimedInviteFilter',
      'OrgClaimedInviteOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgClaimedInvite',
      fieldName: 'orgClaimedInvites',
      document,
      variables,
    });
  }
  findFirst<S extends OrgClaimedInviteSelect>(
    args: FindFirstArgs<S, OrgClaimedInviteFilter, OrgClaimedInviteOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgClaimedInviteSelect>
  ): QueryBuilder<{
    orgClaimedInvite: InferSelectResult<OrgClaimedInviteWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgClaimedInvite',
      'orgClaimedInvites',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgClaimedInviteFilter',
      'OrgClaimedInviteOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgClaimedInvite',
      fieldName: 'orgClaimedInvite',
      document,
      variables,
      transform: (data: {
        orgClaimedInvites?: {
          nodes?: InferSelectResult<OrgClaimedInviteWithRelations, S>[];
        };
      }) => ({
        orgClaimedInvite: data.orgClaimedInvites?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgClaimedInviteSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgClaimedInviteSelect>
  ): QueryBuilder<{
    orgClaimedInvite: InferSelectResult<OrgClaimedInviteWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgClaimedInvite',
      'orgClaimedInvites',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgClaimedInviteFilter',
      'OrgClaimedInviteOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgClaimedInvite',
      fieldName: 'orgClaimedInvite',
      document,
      variables,
      transform: (data: {
        orgClaimedInvites?: {
          nodes?: InferSelectResult<OrgClaimedInviteWithRelations, S>[];
        };
      }) => ({
        orgClaimedInvite: data.orgClaimedInvites?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgClaimedInviteSelect>(
    args: CreateArgs<S, CreateOrgClaimedInviteInput['orgClaimedInvite']> & {
      select: S;
    } & StrictSelect<S, OrgClaimedInviteSelect>
  ): QueryBuilder<{
    createOrgClaimedInvite: {
      orgClaimedInvite: InferSelectResult<OrgClaimedInviteWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgClaimedInvite',
      'createOrgClaimedInvite',
      'orgClaimedInvite',
      args.select,
      args.data,
      'CreateOrgClaimedInviteInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgClaimedInvite',
      fieldName: 'createOrgClaimedInvite',
      document,
      variables,
    });
  }
  update<S extends OrgClaimedInviteSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgClaimedInvitePatch
    > & {
      select: S;
    } & StrictSelect<S, OrgClaimedInviteSelect>
  ): QueryBuilder<{
    updateOrgClaimedInvite: {
      orgClaimedInvite: InferSelectResult<OrgClaimedInviteWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgClaimedInvite',
      'updateOrgClaimedInvite',
      'orgClaimedInvite',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgClaimedInviteInput',
      'id',
      'orgClaimedInvitePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgClaimedInvite',
      fieldName: 'updateOrgClaimedInvite',
      document,
      variables,
    });
  }
  delete<S extends OrgClaimedInviteSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgClaimedInviteSelect>
  ): QueryBuilder<{
    deleteOrgClaimedInvite: {
      orgClaimedInvite: InferSelectResult<OrgClaimedInviteWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgClaimedInvite',
      'deleteOrgClaimedInvite',
      'orgClaimedInvite',
      {
        id: args.where.id,
      },
      'DeleteOrgClaimedInviteInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgClaimedInvite',
      fieldName: 'deleteOrgClaimedInvite',
      document,
      variables,
    });
  }
}
