/**
 * OrgCapability model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgCapability,
  OrgCapabilityWithRelations,
  OrgCapabilitySelect,
  OrgCapabilityFilter,
  OrgCapabilityOrderBy,
  CreateOrgCapabilityInput,
  UpdateOrgCapabilityInput,
  OrgCapabilityPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgCapabilityModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgCapabilitySelect>(
    args: FindManyArgs<S, OrgCapabilityFilter, OrgCapabilityOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgCapabilitySelect>
  ): QueryBuilder<{
    orgCapabilities: ConnectionResult<InferSelectResult<OrgCapabilityWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgCapability',
      'orgCapabilities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgCapabilityFilter',
      'OrgCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgCapability',
      fieldName: 'orgCapabilities',
      document,
      variables,
    });
  }
  findFirst<S extends OrgCapabilitySelect>(
    args: FindFirstArgs<S, OrgCapabilityFilter, OrgCapabilityOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgCapabilitySelect>
  ): QueryBuilder<{
    orgCapability: InferSelectResult<OrgCapabilityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgCapability',
      'orgCapabilities',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgCapabilityFilter',
      'OrgCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgCapability',
      fieldName: 'orgCapability',
      document,
      variables,
      transform: (data: {
        orgCapabilities?: {
          nodes?: InferSelectResult<OrgCapabilityWithRelations, S>[];
        };
      }) => ({
        orgCapability: data.orgCapabilities?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgCapabilitySelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgCapabilitySelect>
  ): QueryBuilder<{
    orgCapability: InferSelectResult<OrgCapabilityWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgCapability',
      'orgCapabilities',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgCapabilityFilter',
      'OrgCapabilityOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgCapability',
      fieldName: 'orgCapability',
      document,
      variables,
      transform: (data: {
        orgCapabilities?: {
          nodes?: InferSelectResult<OrgCapabilityWithRelations, S>[];
        };
      }) => ({
        orgCapability: data.orgCapabilities?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgCapabilitySelect>(
    args: CreateArgs<S, CreateOrgCapabilityInput['orgCapability']> & {
      select: S;
    } & StrictSelect<S, OrgCapabilitySelect>
  ): QueryBuilder<{
    createOrgCapability: {
      orgCapability: InferSelectResult<OrgCapabilityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgCapability',
      'createOrgCapability',
      'orgCapability',
      args.select,
      args.data,
      'CreateOrgCapabilityInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgCapability',
      fieldName: 'createOrgCapability',
      document,
      variables,
    });
  }
  update<S extends OrgCapabilitySelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgCapabilityPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgCapabilitySelect>
  ): QueryBuilder<{
    updateOrgCapability: {
      orgCapability: InferSelectResult<OrgCapabilityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgCapability',
      'updateOrgCapability',
      'orgCapability',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgCapabilityInput',
      'id',
      'orgCapabilityPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgCapability',
      fieldName: 'updateOrgCapability',
      document,
      variables,
    });
  }
  delete<S extends OrgCapabilitySelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgCapabilitySelect>
  ): QueryBuilder<{
    deleteOrgCapability: {
      orgCapability: InferSelectResult<OrgCapabilityWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgCapability',
      'deleteOrgCapability',
      'orgCapability',
      {
        id: args.where.id,
      },
      'DeleteOrgCapabilityInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgCapability',
      fieldName: 'deleteOrgCapability',
      document,
      variables,
    });
  }
}
