/**
 * OrgChartEdge model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgChartEdge,
  OrgChartEdgeWithRelations,
  OrgChartEdgeSelect,
  OrgChartEdgeFilter,
  OrgChartEdgeOrderBy,
  CreateOrgChartEdgeInput,
  UpdateOrgChartEdgeInput,
  OrgChartEdgePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgChartEdgeModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgChartEdgeSelect>(
    args: FindManyArgs<S, OrgChartEdgeFilter, OrgChartEdgeOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeSelect>
  ): QueryBuilder<{
    orgChartEdges: ConnectionResult<InferSelectResult<OrgChartEdgeWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgChartEdge',
      'orgChartEdges',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgChartEdgeFilter',
      'OrgChartEdgeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgChartEdge',
      fieldName: 'orgChartEdges',
      document,
      variables,
    });
  }
  findFirst<S extends OrgChartEdgeSelect>(
    args: FindFirstArgs<S, OrgChartEdgeFilter, OrgChartEdgeOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeSelect>
  ): QueryBuilder<{
    orgChartEdge: InferSelectResult<OrgChartEdgeWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgChartEdge',
      'orgChartEdges',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgChartEdgeFilter',
      'OrgChartEdgeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgChartEdge',
      fieldName: 'orgChartEdge',
      document,
      variables,
      transform: (data: {
        orgChartEdges?: {
          nodes?: InferSelectResult<OrgChartEdgeWithRelations, S>[];
        };
      }) => ({
        orgChartEdge: data.orgChartEdges?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgChartEdgeSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgChartEdgeSelect>
  ): QueryBuilder<{
    orgChartEdge: InferSelectResult<OrgChartEdgeWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgChartEdge',
      'orgChartEdges',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgChartEdgeFilter',
      'OrgChartEdgeOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgChartEdge',
      fieldName: 'orgChartEdge',
      document,
      variables,
      transform: (data: {
        orgChartEdges?: {
          nodes?: InferSelectResult<OrgChartEdgeWithRelations, S>[];
        };
      }) => ({
        orgChartEdge: data.orgChartEdges?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgChartEdgeSelect>(
    args: CreateArgs<S, CreateOrgChartEdgeInput['orgChartEdge']> & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeSelect>
  ): QueryBuilder<{
    createOrgChartEdge: {
      orgChartEdge: InferSelectResult<OrgChartEdgeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgChartEdge',
      'createOrgChartEdge',
      'orgChartEdge',
      args.select,
      args.data,
      'CreateOrgChartEdgeInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgChartEdge',
      fieldName: 'createOrgChartEdge',
      document,
      variables,
    });
  }
  update<S extends OrgChartEdgeSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgChartEdgePatch
    > & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeSelect>
  ): QueryBuilder<{
    updateOrgChartEdge: {
      orgChartEdge: InferSelectResult<OrgChartEdgeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgChartEdge',
      'updateOrgChartEdge',
      'orgChartEdge',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgChartEdgeInput',
      'id',
      'orgChartEdgePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgChartEdge',
      fieldName: 'updateOrgChartEdge',
      document,
      variables,
    });
  }
  delete<S extends OrgChartEdgeSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeSelect>
  ): QueryBuilder<{
    deleteOrgChartEdge: {
      orgChartEdge: InferSelectResult<OrgChartEdgeWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgChartEdge',
      'deleteOrgChartEdge',
      'orgChartEdge',
      {
        id: args.where.id,
      },
      'DeleteOrgChartEdgeInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgChartEdge',
      fieldName: 'deleteOrgChartEdge',
      document,
      variables,
    });
  }
}
