/**
 * OrgChartEdgeGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgChartEdgeGrant,
  OrgChartEdgeGrantWithRelations,
  OrgChartEdgeGrantSelect,
  OrgChartEdgeGrantFilter,
  OrgChartEdgeGrantOrderBy,
  CreateOrgChartEdgeGrantInput,
  UpdateOrgChartEdgeGrantInput,
  OrgChartEdgeGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgChartEdgeGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgChartEdgeGrantSelect>(
    args: FindManyArgs<S, OrgChartEdgeGrantFilter, OrgChartEdgeGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeGrantSelect>
  ): QueryBuilder<{
    orgChartEdgeGrants: ConnectionResult<InferSelectResult<OrgChartEdgeGrantWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgChartEdgeGrant',
      'orgChartEdgeGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgChartEdgeGrantFilter',
      'OrgChartEdgeGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgChartEdgeGrant',
      fieldName: 'orgChartEdgeGrants',
      document,
      variables,
    });
  }
  findFirst<S extends OrgChartEdgeGrantSelect>(
    args: FindFirstArgs<S, OrgChartEdgeGrantFilter, OrgChartEdgeGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeGrantSelect>
  ): QueryBuilder<{
    orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgChartEdgeGrant',
      'orgChartEdgeGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgChartEdgeGrantFilter',
      'OrgChartEdgeGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgChartEdgeGrant',
      fieldName: 'orgChartEdgeGrant',
      document,
      variables,
      transform: (data: {
        orgChartEdgeGrants?: {
          nodes?: InferSelectResult<OrgChartEdgeGrantWithRelations, S>[];
        };
      }) => ({
        orgChartEdgeGrant: data.orgChartEdgeGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgChartEdgeGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgChartEdgeGrantSelect>
  ): QueryBuilder<{
    orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgChartEdgeGrant',
      'orgChartEdgeGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgChartEdgeGrantFilter',
      'OrgChartEdgeGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgChartEdgeGrant',
      fieldName: 'orgChartEdgeGrant',
      document,
      variables,
      transform: (data: {
        orgChartEdgeGrants?: {
          nodes?: InferSelectResult<OrgChartEdgeGrantWithRelations, S>[];
        };
      }) => ({
        orgChartEdgeGrant: data.orgChartEdgeGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgChartEdgeGrantSelect>(
    args: CreateArgs<S, CreateOrgChartEdgeGrantInput['orgChartEdgeGrant']> & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeGrantSelect>
  ): QueryBuilder<{
    createOrgChartEdgeGrant: {
      orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgChartEdgeGrant',
      'createOrgChartEdgeGrant',
      'orgChartEdgeGrant',
      args.select,
      args.data,
      'CreateOrgChartEdgeGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgChartEdgeGrant',
      fieldName: 'createOrgChartEdgeGrant',
      document,
      variables,
    });
  }
  update<S extends OrgChartEdgeGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgChartEdgeGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeGrantSelect>
  ): QueryBuilder<{
    updateOrgChartEdgeGrant: {
      orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgChartEdgeGrant',
      'updateOrgChartEdgeGrant',
      'orgChartEdgeGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgChartEdgeGrantInput',
      'id',
      'orgChartEdgeGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgChartEdgeGrant',
      fieldName: 'updateOrgChartEdgeGrant',
      document,
      variables,
    });
  }
  delete<S extends OrgChartEdgeGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgChartEdgeGrantSelect>
  ): QueryBuilder<{
    deleteOrgChartEdgeGrant: {
      orgChartEdgeGrant: InferSelectResult<OrgChartEdgeGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgChartEdgeGrant',
      'deleteOrgChartEdgeGrant',
      'orgChartEdgeGrant',
      {
        id: args.where.id,
      },
      'DeleteOrgChartEdgeGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgChartEdgeGrant',
      fieldName: 'deleteOrgChartEdgeGrant',
      document,
      variables,
    });
  }
}
