/**
 * OrgGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgGrant,
  OrgGrantWithRelations,
  OrgGrantSelect,
  OrgGrantFilter,
  OrgGrantOrderBy,
  CreateOrgGrantInput,
  UpdateOrgGrantInput,
  OrgGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgGrantSelect>(
    args: FindManyArgs<S, OrgGrantFilter, OrgGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgGrantSelect>
  ): QueryBuilder<{
    orgGrants: ConnectionResult<InferSelectResult<OrgGrantWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgGrant',
      'orgGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgGrantFilter',
      'OrgGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgGrant',
      fieldName: 'orgGrants',
      document,
      variables,
    });
  }
  findFirst<S extends OrgGrantSelect>(
    args: FindFirstArgs<S, OrgGrantFilter, OrgGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgGrantSelect>
  ): QueryBuilder<{
    orgGrant: InferSelectResult<OrgGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgGrant',
      'orgGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgGrantFilter',
      'OrgGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgGrant',
      fieldName: 'orgGrant',
      document,
      variables,
      transform: (data: {
        orgGrants?: {
          nodes?: InferSelectResult<OrgGrantWithRelations, S>[];
        };
      }) => ({
        orgGrant: data.orgGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgGrantSelect>
  ): QueryBuilder<{
    orgGrant: InferSelectResult<OrgGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgGrant',
      'orgGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgGrantFilter',
      'OrgGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgGrant',
      fieldName: 'orgGrant',
      document,
      variables,
      transform: (data: {
        orgGrants?: {
          nodes?: InferSelectResult<OrgGrantWithRelations, S>[];
        };
      }) => ({
        orgGrant: data.orgGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgGrantSelect>(
    args: CreateArgs<S, CreateOrgGrantInput['orgGrant']> & {
      select: S;
    } & StrictSelect<S, OrgGrantSelect>
  ): QueryBuilder<{
    createOrgGrant: {
      orgGrant: InferSelectResult<OrgGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgGrant',
      'createOrgGrant',
      'orgGrant',
      args.select,
      args.data,
      'CreateOrgGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgGrant',
      fieldName: 'createOrgGrant',
      document,
      variables,
    });
  }
  update<S extends OrgGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgGrantSelect>
  ): QueryBuilder<{
    updateOrgGrant: {
      orgGrant: InferSelectResult<OrgGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgGrant',
      'updateOrgGrant',
      'orgGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgGrantInput',
      'id',
      'orgGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgGrant',
      fieldName: 'updateOrgGrant',
      document,
      variables,
    });
  }
  delete<S extends OrgGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgGrantSelect>
  ): QueryBuilder<{
    deleteOrgGrant: {
      orgGrant: InferSelectResult<OrgGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgGrant',
      'deleteOrgGrant',
      'orgGrant',
      {
        id: args.where.id,
      },
      'DeleteOrgGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgGrant',
      fieldName: 'deleteOrgGrant',
      document,
      variables,
    });
  }
}
