/**
 * OrgInvite model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgInvite,
  OrgInviteWithRelations,
  OrgInviteSelect,
  OrgInviteFilter,
  OrgInviteOrderBy,
  CreateOrgInviteInput,
  UpdateOrgInviteInput,
  OrgInvitePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgInviteModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgInviteSelect>(
    args: FindManyArgs<S, OrgInviteFilter, OrgInviteOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgInviteSelect>
  ): QueryBuilder<{
    orgInvites: ConnectionResult<InferSelectResult<OrgInviteWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgInvite',
      'orgInvites',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgInviteFilter',
      'OrgInviteOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgInvite',
      fieldName: 'orgInvites',
      document,
      variables,
    });
  }
  findFirst<S extends OrgInviteSelect>(
    args: FindFirstArgs<S, OrgInviteFilter, OrgInviteOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgInviteSelect>
  ): QueryBuilder<{
    orgInvite: InferSelectResult<OrgInviteWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgInvite',
      'orgInvites',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgInviteFilter',
      'OrgInviteOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgInvite',
      fieldName: 'orgInvite',
      document,
      variables,
      transform: (data: {
        orgInvites?: {
          nodes?: InferSelectResult<OrgInviteWithRelations, S>[];
        };
      }) => ({
        orgInvite: data.orgInvites?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgInviteSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgInviteSelect>
  ): QueryBuilder<{
    orgInvite: InferSelectResult<OrgInviteWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgInvite',
      'orgInvites',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgInviteFilter',
      'OrgInviteOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgInvite',
      fieldName: 'orgInvite',
      document,
      variables,
      transform: (data: {
        orgInvites?: {
          nodes?: InferSelectResult<OrgInviteWithRelations, S>[];
        };
      }) => ({
        orgInvite: data.orgInvites?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgInviteSelect>(
    args: CreateArgs<S, CreateOrgInviteInput['orgInvite']> & {
      select: S;
    } & StrictSelect<S, OrgInviteSelect>
  ): QueryBuilder<{
    createOrgInvite: {
      orgInvite: InferSelectResult<OrgInviteWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgInvite',
      'createOrgInvite',
      'orgInvite',
      args.select,
      args.data,
      'CreateOrgInviteInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgInvite',
      fieldName: 'createOrgInvite',
      document,
      variables,
    });
  }
  update<S extends OrgInviteSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgInvitePatch
    > & {
      select: S;
    } & StrictSelect<S, OrgInviteSelect>
  ): QueryBuilder<{
    updateOrgInvite: {
      orgInvite: InferSelectResult<OrgInviteWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgInvite',
      'updateOrgInvite',
      'orgInvite',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgInviteInput',
      'id',
      'orgInvitePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgInvite',
      fieldName: 'updateOrgInvite',
      document,
      variables,
    });
  }
  delete<S extends OrgInviteSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgInviteSelect>
  ): QueryBuilder<{
    deleteOrgInvite: {
      orgInvite: InferSelectResult<OrgInviteWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgInvite',
      'deleteOrgInvite',
      'orgInvite',
      {
        id: args.where.id,
      },
      'DeleteOrgInviteInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgInvite',
      fieldName: 'deleteOrgInvite',
      document,
      variables,
    });
  }
}
