/**
 * OrgMembershipDefault model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgMembershipDefault,
  OrgMembershipDefaultWithRelations,
  OrgMembershipDefaultSelect,
  OrgMembershipDefaultFilter,
  OrgMembershipDefaultOrderBy,
  CreateOrgMembershipDefaultInput,
  UpdateOrgMembershipDefaultInput,
  OrgMembershipDefaultPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgMembershipDefaultModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgMembershipDefaultSelect>(
    args: FindManyArgs<S, OrgMembershipDefaultFilter, OrgMembershipDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgMembershipDefaultSelect>
  ): QueryBuilder<{
    orgMembershipDefaults: ConnectionResult<
      InferSelectResult<OrgMembershipDefaultWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMembershipDefault',
      'orgMembershipDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgMembershipDefaultFilter',
      'OrgMembershipDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipDefault',
      fieldName: 'orgMembershipDefaults',
      document,
      variables,
    });
  }
  findFirst<S extends OrgMembershipDefaultSelect>(
    args: FindFirstArgs<S, OrgMembershipDefaultFilter, OrgMembershipDefaultOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgMembershipDefaultSelect>
  ): QueryBuilder<{
    orgMembershipDefault: InferSelectResult<OrgMembershipDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgMembershipDefault',
      'orgMembershipDefaults',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgMembershipDefaultFilter',
      'OrgMembershipDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipDefault',
      fieldName: 'orgMembershipDefault',
      document,
      variables,
      transform: (data: {
        orgMembershipDefaults?: {
          nodes?: InferSelectResult<OrgMembershipDefaultWithRelations, S>[];
        };
      }) => ({
        orgMembershipDefault: data.orgMembershipDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgMembershipDefaultSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgMembershipDefaultSelect>
  ): QueryBuilder<{
    orgMembershipDefault: InferSelectResult<OrgMembershipDefaultWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMembershipDefault',
      'orgMembershipDefaults',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgMembershipDefaultFilter',
      'OrgMembershipDefaultOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipDefault',
      fieldName: 'orgMembershipDefault',
      document,
      variables,
      transform: (data: {
        orgMembershipDefaults?: {
          nodes?: InferSelectResult<OrgMembershipDefaultWithRelations, S>[];
        };
      }) => ({
        orgMembershipDefault: data.orgMembershipDefaults?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgMembershipDefaultSelect>(
    args: CreateArgs<S, CreateOrgMembershipDefaultInput['orgMembershipDefault']> & {
      select: S;
    } & StrictSelect<S, OrgMembershipDefaultSelect>
  ): QueryBuilder<{
    createOrgMembershipDefault: {
      orgMembershipDefault: InferSelectResult<OrgMembershipDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgMembershipDefault',
      'createOrgMembershipDefault',
      'orgMembershipDefault',
      args.select,
      args.data,
      'CreateOrgMembershipDefaultInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipDefault',
      fieldName: 'createOrgMembershipDefault',
      document,
      variables,
    });
  }
  update<S extends OrgMembershipDefaultSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgMembershipDefaultPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgMembershipDefaultSelect>
  ): QueryBuilder<{
    updateOrgMembershipDefault: {
      orgMembershipDefault: InferSelectResult<OrgMembershipDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgMembershipDefault',
      'updateOrgMembershipDefault',
      'orgMembershipDefault',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgMembershipDefaultInput',
      'id',
      'orgMembershipDefaultPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipDefault',
      fieldName: 'updateOrgMembershipDefault',
      document,
      variables,
    });
  }
  delete<S extends OrgMembershipDefaultSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgMembershipDefaultSelect>
  ): QueryBuilder<{
    deleteOrgMembershipDefault: {
      orgMembershipDefault: InferSelectResult<OrgMembershipDefaultWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgMembershipDefault',
      'deleteOrgMembershipDefault',
      'orgMembershipDefault',
      {
        id: args.where.id,
      },
      'DeleteOrgMembershipDefaultInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipDefault',
      fieldName: 'deleteOrgMembershipDefault',
      document,
      variables,
    });
  }
}
