/**
 * OrgMemberProfile model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgMemberProfile,
  OrgMemberProfileWithRelations,
  OrgMemberProfileSelect,
  OrgMemberProfileFilter,
  OrgMemberProfileOrderBy,
  CreateOrgMemberProfileInput,
  UpdateOrgMemberProfileInput,
  OrgMemberProfilePatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgMemberProfileModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgMemberProfileSelect>(
    args: FindManyArgs<S, OrgMemberProfileFilter, OrgMemberProfileOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgMemberProfileSelect>
  ): QueryBuilder<{
    orgMemberProfiles: ConnectionResult<InferSelectResult<OrgMemberProfileWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMemberProfile',
      'orgMemberProfiles',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgMemberProfileFilter',
      'OrgMemberProfileOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMemberProfile',
      fieldName: 'orgMemberProfiles',
      document,
      variables,
    });
  }
  findFirst<S extends OrgMemberProfileSelect>(
    args: FindFirstArgs<S, OrgMemberProfileFilter, OrgMemberProfileOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgMemberProfileSelect>
  ): QueryBuilder<{
    orgMemberProfile: InferSelectResult<OrgMemberProfileWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgMemberProfile',
      'orgMemberProfiles',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgMemberProfileFilter',
      'OrgMemberProfileOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMemberProfile',
      fieldName: 'orgMemberProfile',
      document,
      variables,
      transform: (data: {
        orgMemberProfiles?: {
          nodes?: InferSelectResult<OrgMemberProfileWithRelations, S>[];
        };
      }) => ({
        orgMemberProfile: data.orgMemberProfiles?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgMemberProfileSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgMemberProfileSelect>
  ): QueryBuilder<{
    orgMemberProfile: InferSelectResult<OrgMemberProfileWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMemberProfile',
      'orgMemberProfiles',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgMemberProfileFilter',
      'OrgMemberProfileOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMemberProfile',
      fieldName: 'orgMemberProfile',
      document,
      variables,
      transform: (data: {
        orgMemberProfiles?: {
          nodes?: InferSelectResult<OrgMemberProfileWithRelations, S>[];
        };
      }) => ({
        orgMemberProfile: data.orgMemberProfiles?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgMemberProfileSelect>(
    args: CreateArgs<S, CreateOrgMemberProfileInput['orgMemberProfile']> & {
      select: S;
    } & StrictSelect<S, OrgMemberProfileSelect>
  ): QueryBuilder<{
    createOrgMemberProfile: {
      orgMemberProfile: InferSelectResult<OrgMemberProfileWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgMemberProfile',
      'createOrgMemberProfile',
      'orgMemberProfile',
      args.select,
      args.data,
      'CreateOrgMemberProfileInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMemberProfile',
      fieldName: 'createOrgMemberProfile',
      document,
      variables,
    });
  }
  update<S extends OrgMemberProfileSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgMemberProfilePatch
    > & {
      select: S;
    } & StrictSelect<S, OrgMemberProfileSelect>
  ): QueryBuilder<{
    updateOrgMemberProfile: {
      orgMemberProfile: InferSelectResult<OrgMemberProfileWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgMemberProfile',
      'updateOrgMemberProfile',
      'orgMemberProfile',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgMemberProfileInput',
      'id',
      'orgMemberProfilePatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMemberProfile',
      fieldName: 'updateOrgMemberProfile',
      document,
      variables,
    });
  }
  delete<S extends OrgMemberProfileSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgMemberProfileSelect>
  ): QueryBuilder<{
    deleteOrgMemberProfile: {
      orgMemberProfile: InferSelectResult<OrgMemberProfileWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgMemberProfile',
      'deleteOrgMemberProfile',
      'orgMemberProfile',
      {
        id: args.where.id,
      },
      'DeleteOrgMemberProfileInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMemberProfile',
      fieldName: 'deleteOrgMemberProfile',
      document,
      variables,
    });
  }
}
