/**
 * OrgMembershipSetting model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgMembershipSetting,
  OrgMembershipSettingWithRelations,
  OrgMembershipSettingSelect,
  OrgMembershipSettingFilter,
  OrgMembershipSettingOrderBy,
  CreateOrgMembershipSettingInput,
  UpdateOrgMembershipSettingInput,
  OrgMembershipSettingPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgMembershipSettingModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgMembershipSettingSelect>(
    args: FindManyArgs<S, OrgMembershipSettingFilter, OrgMembershipSettingOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgMembershipSettingSelect>
  ): QueryBuilder<{
    orgMembershipSettings: ConnectionResult<
      InferSelectResult<OrgMembershipSettingWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMembershipSetting',
      'orgMembershipSettings',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgMembershipSettingFilter',
      'OrgMembershipSettingOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipSetting',
      fieldName: 'orgMembershipSettings',
      document,
      variables,
    });
  }
  findFirst<S extends OrgMembershipSettingSelect>(
    args: FindFirstArgs<S, OrgMembershipSettingFilter, OrgMembershipSettingOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgMembershipSettingSelect>
  ): QueryBuilder<{
    orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgMembershipSetting',
      'orgMembershipSettings',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgMembershipSettingFilter',
      'OrgMembershipSettingOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipSetting',
      fieldName: 'orgMembershipSetting',
      document,
      variables,
      transform: (data: {
        orgMembershipSettings?: {
          nodes?: InferSelectResult<OrgMembershipSettingWithRelations, S>[];
        };
      }) => ({
        orgMembershipSetting: data.orgMembershipSettings?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgMembershipSettingSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgMembershipSettingSelect>
  ): QueryBuilder<{
    orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMembershipSetting',
      'orgMembershipSettings',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgMembershipSettingFilter',
      'OrgMembershipSettingOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipSetting',
      fieldName: 'orgMembershipSetting',
      document,
      variables,
      transform: (data: {
        orgMembershipSettings?: {
          nodes?: InferSelectResult<OrgMembershipSettingWithRelations, S>[];
        };
      }) => ({
        orgMembershipSetting: data.orgMembershipSettings?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgMembershipSettingSelect>(
    args: CreateArgs<S, CreateOrgMembershipSettingInput['orgMembershipSetting']> & {
      select: S;
    } & StrictSelect<S, OrgMembershipSettingSelect>
  ): QueryBuilder<{
    createOrgMembershipSetting: {
      orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgMembershipSetting',
      'createOrgMembershipSetting',
      'orgMembershipSetting',
      args.select,
      args.data,
      'CreateOrgMembershipSettingInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipSetting',
      fieldName: 'createOrgMembershipSetting',
      document,
      variables,
    });
  }
  update<S extends OrgMembershipSettingSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgMembershipSettingPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgMembershipSettingSelect>
  ): QueryBuilder<{
    updateOrgMembershipSetting: {
      orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgMembershipSetting',
      'updateOrgMembershipSetting',
      'orgMembershipSetting',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgMembershipSettingInput',
      'id',
      'orgMembershipSettingPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipSetting',
      fieldName: 'updateOrgMembershipSetting',
      document,
      variables,
    });
  }
  delete<S extends OrgMembershipSettingSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgMembershipSettingSelect>
  ): QueryBuilder<{
    deleteOrgMembershipSetting: {
      orgMembershipSetting: InferSelectResult<OrgMembershipSettingWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgMembershipSetting',
      'deleteOrgMembershipSetting',
      'orgMembershipSetting',
      {
        id: args.where.id,
      },
      'DeleteOrgMembershipSettingInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipSetting',
      fieldName: 'deleteOrgMembershipSetting',
      document,
      variables,
    });
  }
}
