/**
 * OrgProfileDefinitionGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgProfileDefinitionGrant,
  OrgProfileDefinitionGrantWithRelations,
  OrgProfileDefinitionGrantSelect,
  OrgProfileDefinitionGrantFilter,
  OrgProfileDefinitionGrantOrderBy,
  CreateOrgProfileDefinitionGrantInput,
  UpdateOrgProfileDefinitionGrantInput,
  OrgProfileDefinitionGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgProfileDefinitionGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgProfileDefinitionGrantSelect>(
    args: FindManyArgs<S, OrgProfileDefinitionGrantFilter, OrgProfileDefinitionGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    orgProfileDefinitionGrants: ConnectionResult<
      InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgProfileDefinitionGrant',
      'orgProfileDefinitionGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgProfileDefinitionGrantFilter',
      'OrgProfileDefinitionGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfileDefinitionGrant',
      fieldName: 'orgProfileDefinitionGrants',
      document,
      variables,
    });
  }
  findFirst<S extends OrgProfileDefinitionGrantSelect>(
    args: FindFirstArgs<S, OrgProfileDefinitionGrantFilter, OrgProfileDefinitionGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    orgProfileDefinitionGrant: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgProfileDefinitionGrant',
      'orgProfileDefinitionGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgProfileDefinitionGrantFilter',
      'OrgProfileDefinitionGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfileDefinitionGrant',
      fieldName: 'orgProfileDefinitionGrant',
      document,
      variables,
      transform: (data: {
        orgProfileDefinitionGrants?: {
          nodes?: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>[];
        };
      }) => ({
        orgProfileDefinitionGrant: data.orgProfileDefinitionGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgProfileDefinitionGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    orgProfileDefinitionGrant: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgProfileDefinitionGrant',
      'orgProfileDefinitionGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgProfileDefinitionGrantFilter',
      'OrgProfileDefinitionGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfileDefinitionGrant',
      fieldName: 'orgProfileDefinitionGrant',
      document,
      variables,
      transform: (data: {
        orgProfileDefinitionGrants?: {
          nodes?: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>[];
        };
      }) => ({
        orgProfileDefinitionGrant: data.orgProfileDefinitionGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgProfileDefinitionGrantSelect>(
    args: CreateArgs<S, CreateOrgProfileDefinitionGrantInput['orgProfileDefinitionGrant']> & {
      select: S;
    } & StrictSelect<S, OrgProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    createOrgProfileDefinitionGrant: {
      orgProfileDefinitionGrant: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgProfileDefinitionGrant',
      'createOrgProfileDefinitionGrant',
      'orgProfileDefinitionGrant',
      args.select,
      args.data,
      'CreateOrgProfileDefinitionGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfileDefinitionGrant',
      fieldName: 'createOrgProfileDefinitionGrant',
      document,
      variables,
    });
  }
  update<S extends OrgProfileDefinitionGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgProfileDefinitionGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    updateOrgProfileDefinitionGrant: {
      orgProfileDefinitionGrant: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgProfileDefinitionGrant',
      'updateOrgProfileDefinitionGrant',
      'orgProfileDefinitionGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgProfileDefinitionGrantInput',
      'id',
      'orgProfileDefinitionGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfileDefinitionGrant',
      fieldName: 'updateOrgProfileDefinitionGrant',
      document,
      variables,
    });
  }
  delete<S extends OrgProfileDefinitionGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgProfileDefinitionGrantSelect>
  ): QueryBuilder<{
    deleteOrgProfileDefinitionGrant: {
      orgProfileDefinitionGrant: InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgProfileDefinitionGrant',
      'deleteOrgProfileDefinitionGrant',
      'orgProfileDefinitionGrant',
      {
        id: args.where.id,
      },
      'DeleteOrgProfileDefinitionGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfileDefinitionGrant',
      fieldName: 'deleteOrgProfileDefinitionGrant',
      document,
      variables,
    });
  }
}
