/**
 * OrgProfileGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgProfileGrant,
  OrgProfileGrantWithRelations,
  OrgProfileGrantSelect,
  OrgProfileGrantFilter,
  OrgProfileGrantOrderBy,
  CreateOrgProfileGrantInput,
  UpdateOrgProfileGrantInput,
  OrgProfileGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgProfileGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgProfileGrantSelect>(
    args: FindManyArgs<S, OrgProfileGrantFilter, OrgProfileGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgProfileGrantSelect>
  ): QueryBuilder<{
    orgProfileGrants: ConnectionResult<InferSelectResult<OrgProfileGrantWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgProfileGrant',
      'orgProfileGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgProfileGrantFilter',
      'OrgProfileGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfileGrant',
      fieldName: 'orgProfileGrants',
      document,
      variables,
    });
  }
  findFirst<S extends OrgProfileGrantSelect>(
    args: FindFirstArgs<S, OrgProfileGrantFilter, OrgProfileGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgProfileGrantSelect>
  ): QueryBuilder<{
    orgProfileGrant: InferSelectResult<OrgProfileGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgProfileGrant',
      'orgProfileGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'OrgProfileGrantFilter',
      'OrgProfileGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfileGrant',
      fieldName: 'orgProfileGrant',
      document,
      variables,
      transform: (data: {
        orgProfileGrants?: {
          nodes?: InferSelectResult<OrgProfileGrantWithRelations, S>[];
        };
      }) => ({
        orgProfileGrant: data.orgProfileGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends OrgProfileGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, OrgProfileGrantSelect>
  ): QueryBuilder<{
    orgProfileGrant: InferSelectResult<OrgProfileGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgProfileGrant',
      'orgProfileGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'OrgProfileGrantFilter',
      'OrgProfileGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgProfileGrant',
      fieldName: 'orgProfileGrant',
      document,
      variables,
      transform: (data: {
        orgProfileGrants?: {
          nodes?: InferSelectResult<OrgProfileGrantWithRelations, S>[];
        };
      }) => ({
        orgProfileGrant: data.orgProfileGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends OrgProfileGrantSelect>(
    args: CreateArgs<S, CreateOrgProfileGrantInput['orgProfileGrant']> & {
      select: S;
    } & StrictSelect<S, OrgProfileGrantSelect>
  ): QueryBuilder<{
    createOrgProfileGrant: {
      orgProfileGrant: InferSelectResult<OrgProfileGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgProfileGrant',
      'createOrgProfileGrant',
      'orgProfileGrant',
      args.select,
      args.data,
      'CreateOrgProfileGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfileGrant',
      fieldName: 'createOrgProfileGrant',
      document,
      variables,
    });
  }
  update<S extends OrgProfileGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      OrgProfileGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, OrgProfileGrantSelect>
  ): QueryBuilder<{
    updateOrgProfileGrant: {
      orgProfileGrant: InferSelectResult<OrgProfileGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'OrgProfileGrant',
      'updateOrgProfileGrant',
      'orgProfileGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateOrgProfileGrantInput',
      'id',
      'orgProfileGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfileGrant',
      fieldName: 'updateOrgProfileGrant',
      document,
      variables,
    });
  }
  delete<S extends OrgProfileGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, OrgProfileGrantSelect>
  ): QueryBuilder<{
    deleteOrgProfileGrant: {
      orgProfileGrant: InferSelectResult<OrgProfileGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'OrgProfileGrant',
      'deleteOrgProfileGrant',
      'orgProfileGrant',
      {
        id: args.where.id,
      },
      'DeleteOrgProfileGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgProfileGrant',
      fieldName: 'deleteOrgProfileGrant',
      document,
      variables,
    });
  }
}
