/**
 * ORM Client - createClient factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from './client';
import type { OrmClientConfig } from './client';
import { PrincipalModel } from './models/principal';
import { PrincipalEntityModel } from './models/principalEntity';
import { PrincipalScopeOverrideModel } from './models/principalScopeOverride';
import { EmailModel } from './models/email';
import { PhoneNumberModel } from './models/phoneNumber';
import { WebauthnCredentialModel } from './models/webauthnCredential';
import { AuditLogAuthModel } from './models/auditLogAuth';
import { IdentityProviderModel } from './models/identityProvider';
import { RoleTypeModel } from './models/roleType';
import { UserConnectedAccountModel } from './models/userConnectedAccount';
import { UserSettingsSecurityModel } from './models/userSettingsSecurity';
import { OrgApiKeyListModel } from './models/orgApiKeyList';
import { UserModel } from './models/user';
import { createQueryOperations } from './query';
import { createMutationOperations } from './mutation';
export type { OrmClientConfig, QueryResult, GraphQLError, GraphQLAdapter } from './client';
export { GraphQLRequestError, FetchAdapter } from './client';
export { QueryBuilder } from './query-builder';
export * from './select-types';
export * from './models';
export { createQueryOperations } from './query';
export { createMutationOperations } from './mutation';
/**
 * Create an ORM client instance
 *
 * @example
 * ```typescript
 * const db = createClient({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer token' },
 * });
 *
 * // Query users
 * const users = await db.user.findMany({
 *   select: { id: true, name: true },
 *   first: 10,
 * }).execute();
 *
 * // Create a user
 * const newUser = await db.user.create({
 *   data: { name: 'John', email: 'john@example.com' },
 *   select: { id: true },
 * }).execute();
 * ```
 */
export function createClient(config: OrmClientConfig) {
  const client = new OrmClient(config);
  return {
    principal: new PrincipalModel(client),
    principalEntity: new PrincipalEntityModel(client),
    principalScopeOverride: new PrincipalScopeOverrideModel(client),
    email: new EmailModel(client),
    phoneNumber: new PhoneNumberModel(client),
    webauthnCredential: new WebauthnCredentialModel(client),
    auditLogAuth: new AuditLogAuthModel(client),
    identityProvider: new IdentityProviderModel(client),
    roleType: new RoleTypeModel(client),
    userConnectedAccount: new UserConnectedAccountModel(client),
    userSettingsSecurity: new UserSettingsSecurityModel(client),
    orgApiKeyList: new OrgApiKeyListModel(client),
    user: new UserModel(client),
    query: createQueryOperations(client),
    mutation: createMutationOperations(client),
  };
}
