/**
 * GraphQL SDK
 * @generated by @constructive-io/graphql-codegen
 *
 * Tables: Principal, PrincipalEntity, PrincipalScopeOverride, Email, PhoneNumber, WebauthnCredential, AuditLogAuth, IdentityProvider, RoleType, UserConnectedAccount, UserSettingsSecurity, OrgApiKeyList, User
 *
 * Usage:
 *
 * 1. Configure the client:
 * ```ts
 * import { configure } from './generated';
 *
 * configure({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer <token>' },
 * });
 * ```
 *
 * 2. Use the hooks:
 * ```tsx
 * import { useCarsQuery, useCreateCarMutation } from './generated';
 *
 * function MyComponent() {
 *   const { data, isLoading } = useCarsQuery({
 *     selection: { fields: { id: true }, first: 10 },
 *   });
 *   const { mutate } = useCreateCarMutation({
 *     selection: { fields: { id: true } },
 *   });
 *   // ...
 * }
 * ```
 */
export * from './client';
export * from './query-keys';
export * from './mutation-keys';
export * from './invalidation';
export * from './queries';
export * from './mutations';
