-- Revert: schemas/myapp_memberships_public/tables/org_permission_default_grants/constraints/org_permission_default_grants_entity_id_fkey/constraint


ALTER TABLE myapp_memberships_public.org_permission_default_grants 
  DROP CONSTRAINT org_permission_default_grants_entity_id_fkey;


