-- Revert: schemas/myapp_events_public/tables/app_level_requirements/indexes/app_level_requirements_name_level_priority_idx


DROP INDEX myapp_events_public.app_level_requirements_name_level_priority_idx;


