-- Revert: schemas/myapp_memberships_public/tables/app_membership_defaults/indexes/app_membership_defaults_created_by_idx


DROP INDEX myapp_memberships_public.app_membership_defaults_created_by_idx;


