-- Revert: schemas/myapp_memberships_public/tables/app_membership_defaults/indexes/app_membership_defaults_updated_at_idx


DROP INDEX myapp_memberships_public.app_membership_defaults_updated_at_idx;


