/**
 * Centralized mutation key factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

// ============================================================================
// Mutation keys for tracking in-flight mutations
//
// Benefits:
// - Track mutation state with useIsMutating
// - Implement optimistic updates with proper rollback
// - Deduplicate identical mutations
// - Coordinate related mutations
// ============================================================================

// ============================================================================
// Entity Mutation Keys
// ============================================================================

export const orgGetManagersRecordMutationKeys = {
  /** All orgGetManagersRecord mutation keys */ all: ['mutation', 'orggetmanagersrecord'] as const,
  /** Create orgGetManagersRecord mutation key */ create: () =>
    ['mutation', 'orggetmanagersrecord', 'create'] as const,
  /** Update orgGetManagersRecord mutation key */ update: (id: string | number) =>
    ['mutation', 'orggetmanagersrecord', 'update', id] as const,
  /** Delete orgGetManagersRecord mutation key */ delete: (id: string | number) =>
    ['mutation', 'orggetmanagersrecord', 'delete', id] as const,
} as const;
export const orgGetSubordinatesRecordMutationKeys = {
  /** All orgGetSubordinatesRecord mutation keys */ all: [
    'mutation',
    'orggetsubordinatesrecord',
  ] as const,
  /** Create orgGetSubordinatesRecord mutation key */ create: () =>
    ['mutation', 'orggetsubordinatesrecord', 'create'] as const,
  /** Update orgGetSubordinatesRecord mutation key */ update: (id: string | number) =>
    ['mutation', 'orggetsubordinatesrecord', 'update', id] as const,
  /** Delete orgGetSubordinatesRecord mutation key */ delete: (id: string | number) =>
    ['mutation', 'orggetsubordinatesrecord', 'delete', id] as const,
} as const;
export const myPendingAppInvitesRecordMutationKeys = {
  /** All myPendingAppInvitesRecord mutation keys */ all: [
    'mutation',
    'mypendingappinvitesrecord',
  ] as const,
  /** Create myPendingAppInvitesRecord mutation key */ create: () =>
    ['mutation', 'mypendingappinvitesrecord', 'create'] as const,
  /** Update myPendingAppInvitesRecord mutation key */ update: (id: string | number) =>
    ['mutation', 'mypendingappinvitesrecord', 'update', id] as const,
  /** Delete myPendingAppInvitesRecord mutation key */ delete: (id: string | number) =>
    ['mutation', 'mypendingappinvitesrecord', 'delete', id] as const,
} as const;
export const myPendingOrgInvitesRecordMutationKeys = {
  /** All myPendingOrgInvitesRecord mutation keys */ all: [
    'mutation',
    'mypendingorginvitesrecord',
  ] as const,
  /** Create myPendingOrgInvitesRecord mutation key */ create: () =>
    ['mutation', 'mypendingorginvitesrecord', 'create'] as const,
  /** Update myPendingOrgInvitesRecord mutation key */ update: (id: string | number) =>
    ['mutation', 'mypendingorginvitesrecord', 'update', id] as const,
  /** Delete myPendingOrgInvitesRecord mutation key */ delete: (id: string | number) =>
    ['mutation', 'mypendingorginvitesrecord', 'delete', id] as const,
} as const;
export const appCapabilityMutationKeys = {
  /** All appCapability mutation keys */ all: ['mutation', 'appcapability'] as const,
  /** Create appCapability mutation key */ create: () =>
    ['mutation', 'appcapability', 'create'] as const,
  /** Update appCapability mutation key */ update: (id: string | number) =>
    ['mutation', 'appcapability', 'update', id] as const,
  /** Delete appCapability mutation key */ delete: (id: string | number) =>
    ['mutation', 'appcapability', 'delete', id] as const,
} as const;
export const appCapabilityDefaultGrantMutationKeys = {
  /** All appCapabilityDefaultGrant mutation keys */ all: [
    'mutation',
    'appcapabilitydefaultgrant',
  ] as const,
  /** Create appCapabilityDefaultGrant mutation key */ create: () =>
    ['mutation', 'appcapabilitydefaultgrant', 'create'] as const,
  /** Update appCapabilityDefaultGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'appcapabilitydefaultgrant', 'update', id] as const,
  /** Delete appCapabilityDefaultGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'appcapabilitydefaultgrant', 'delete', id] as const,
} as const;
export const appProfileCapabilityMutationKeys = {
  /** All appProfileCapability mutation keys */ all: ['mutation', 'appprofilecapability'] as const,
  /** Create appProfileCapability mutation key */ create: () =>
    ['mutation', 'appprofilecapability', 'create'] as const,
  /** Update appProfileCapability mutation key */ update: (id: string | number) =>
    ['mutation', 'appprofilecapability', 'update', id] as const,
  /** Delete appProfileCapability mutation key */ delete: (id: string | number) =>
    ['mutation', 'appprofilecapability', 'delete', id] as const,
} as const;
export const appMembershipMutationKeys = {
  /** All appMembership mutation keys */ all: ['mutation', 'appmembership'] as const,
  /** Create appMembership mutation key */ create: () =>
    ['mutation', 'appmembership', 'create'] as const,
  /** Update appMembership mutation key */ update: (id: string | number) =>
    ['mutation', 'appmembership', 'update', id] as const,
  /** Delete appMembership mutation key */ delete: (id: string | number) =>
    ['mutation', 'appmembership', 'delete', id] as const,
} as const;
export const appProfileGrantMutationKeys = {
  /** All appProfileGrant mutation keys */ all: ['mutation', 'appprofilegrant'] as const,
  /** Create appProfileGrant mutation key */ create: () =>
    ['mutation', 'appprofilegrant', 'create'] as const,
  /** Update appProfileGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'appprofilegrant', 'update', id] as const,
  /** Delete appProfileGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'appprofilegrant', 'delete', id] as const,
} as const;
export const appMembershipProfileMutationKeys = {
  /** All appMembershipProfile mutation keys */ all: ['mutation', 'appmembershipprofile'] as const,
  /** Create appMembershipProfile mutation key */ create: () =>
    ['mutation', 'appmembershipprofile', 'create'] as const,
  /** Update appMembershipProfile mutation key */ update: (id: string | number) =>
    ['mutation', 'appmembershipprofile', 'update', id] as const,
  /** Delete appMembershipProfile mutation key */ delete: (id: string | number) =>
    ['mutation', 'appmembershipprofile', 'delete', id] as const,
} as const;
export const appProfileDefinitionGrantMutationKeys = {
  /** All appProfileDefinitionGrant mutation keys */ all: [
    'mutation',
    'appprofiledefinitiongrant',
  ] as const,
  /** Create appProfileDefinitionGrant mutation key */ create: () =>
    ['mutation', 'appprofiledefinitiongrant', 'create'] as const,
  /** Update appProfileDefinitionGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'appprofiledefinitiongrant', 'update', id] as const,
  /** Delete appProfileDefinitionGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'appprofiledefinitiongrant', 'delete', id] as const,
} as const;
export const appInviteMutationKeys = {
  /** All appInvite mutation keys */ all: ['mutation', 'appinvite'] as const,
  /** Create appInvite mutation key */ create: () => ['mutation', 'appinvite', 'create'] as const,
  /** Update appInvite mutation key */ update: (id: string | number) =>
    ['mutation', 'appinvite', 'update', id] as const,
  /** Delete appInvite mutation key */ delete: (id: string | number) =>
    ['mutation', 'appinvite', 'delete', id] as const,
} as const;
export const orgCapabilityMutationKeys = {
  /** All orgCapability mutation keys */ all: ['mutation', 'orgcapability'] as const,
  /** Create orgCapability mutation key */ create: () =>
    ['mutation', 'orgcapability', 'create'] as const,
  /** Update orgCapability mutation key */ update: (id: string | number) =>
    ['mutation', 'orgcapability', 'update', id] as const,
  /** Delete orgCapability mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgcapability', 'delete', id] as const,
} as const;
export const orgCapabilityDefaultCapabilityMutationKeys = {
  /** All orgCapabilityDefaultCapability mutation keys */ all: [
    'mutation',
    'orgcapabilitydefaultcapability',
  ] as const,
  /** Create orgCapabilityDefaultCapability mutation key */ create: () =>
    ['mutation', 'orgcapabilitydefaultcapability', 'create'] as const,
  /** Update orgCapabilityDefaultCapability mutation key */ update: (id: string | number) =>
    ['mutation', 'orgcapabilitydefaultcapability', 'update', id] as const,
  /** Delete orgCapabilityDefaultCapability mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgcapabilitydefaultcapability', 'delete', id] as const,
} as const;
export const orgCapabilityDefaultGrantMutationKeys = {
  /** All orgCapabilityDefaultGrant mutation keys */ all: [
    'mutation',
    'orgcapabilitydefaultgrant',
  ] as const,
  /** Create orgCapabilityDefaultGrant mutation key */ create: () =>
    ['mutation', 'orgcapabilitydefaultgrant', 'create'] as const,
  /** Update orgCapabilityDefaultGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orgcapabilitydefaultgrant', 'update', id] as const,
  /** Delete orgCapabilityDefaultGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgcapabilitydefaultgrant', 'delete', id] as const,
} as const;
export const orgProfileCapabilityMutationKeys = {
  /** All orgProfileCapability mutation keys */ all: ['mutation', 'orgprofilecapability'] as const,
  /** Create orgProfileCapability mutation key */ create: () =>
    ['mutation', 'orgprofilecapability', 'create'] as const,
  /** Update orgProfileCapability mutation key */ update: (id: string | number) =>
    ['mutation', 'orgprofilecapability', 'update', id] as const,
  /** Delete orgProfileCapability mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgprofilecapability', 'delete', id] as const,
} as const;
export const orgMembershipMutationKeys = {
  /** All orgMembership mutation keys */ all: ['mutation', 'orgmembership'] as const,
  /** Create orgMembership mutation key */ create: () =>
    ['mutation', 'orgmembership', 'create'] as const,
  /** Update orgMembership mutation key */ update: (id: string | number) =>
    ['mutation', 'orgmembership', 'update', id] as const,
  /** Delete orgMembership mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgmembership', 'delete', id] as const,
} as const;
export const orgProfileGrantMutationKeys = {
  /** All orgProfileGrant mutation keys */ all: ['mutation', 'orgprofilegrant'] as const,
  /** Create orgProfileGrant mutation key */ create: () =>
    ['mutation', 'orgprofilegrant', 'create'] as const,
  /** Update orgProfileGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orgprofilegrant', 'update', id] as const,
  /** Delete orgProfileGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgprofilegrant', 'delete', id] as const,
} as const;
export const orgMembershipProfileMutationKeys = {
  /** All orgMembershipProfile mutation keys */ all: ['mutation', 'orgmembershipprofile'] as const,
  /** Create orgMembershipProfile mutation key */ create: () =>
    ['mutation', 'orgmembershipprofile', 'create'] as const,
  /** Update orgMembershipProfile mutation key */ update: (id: string | number) =>
    ['mutation', 'orgmembershipprofile', 'update', id] as const,
  /** Delete orgMembershipProfile mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgmembershipprofile', 'delete', id] as const,
} as const;
export const orgProfileDefinitionGrantMutationKeys = {
  /** All orgProfileDefinitionGrant mutation keys */ all: [
    'mutation',
    'orgprofiledefinitiongrant',
  ] as const,
  /** Create orgProfileDefinitionGrant mutation key */ create: () =>
    ['mutation', 'orgprofiledefinitiongrant', 'create'] as const,
  /** Update orgProfileDefinitionGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orgprofiledefinitiongrant', 'update', id] as const,
  /** Delete orgProfileDefinitionGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgprofiledefinitiongrant', 'delete', id] as const,
} as const;
export const orgInviteMutationKeys = {
  /** All orgInvite mutation keys */ all: ['mutation', 'orginvite'] as const,
  /** Create orgInvite mutation key */ create: () => ['mutation', 'orginvite', 'create'] as const,
  /** Update orgInvite mutation key */ update: (id: string | number) =>
    ['mutation', 'orginvite', 'update', id] as const,
  /** Delete orgInvite mutation key */ delete: (id: string | number) =>
    ['mutation', 'orginvite', 'delete', id] as const,
} as const;
export const orgMemberMutationKeys = {
  /** All orgMember mutation keys */ all: ['mutation', 'orgmember'] as const,
  /** Create orgMember mutation key */ create: () => ['mutation', 'orgmember', 'create'] as const,
  /** Update orgMember mutation key */ update: (id: string | number) =>
    ['mutation', 'orgmember', 'update', id] as const,
  /** Delete orgMember mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgmember', 'delete', id] as const,
} as const;
export const appCapabilityDefaultMutationKeys = {
  /** All appCapabilityDefault mutation keys */ all: ['mutation', 'appcapabilitydefault'] as const,
  /** Create appCapabilityDefault mutation key */ create: () =>
    ['mutation', 'appcapabilitydefault', 'create'] as const,
  /** Update appCapabilityDefault mutation key */ update: (id: string | number) =>
    ['mutation', 'appcapabilitydefault', 'update', id] as const,
  /** Delete appCapabilityDefault mutation key */ delete: (id: string | number) =>
    ['mutation', 'appcapabilitydefault', 'delete', id] as const,
} as const;
export const orgCapabilityDefaultMutationKeys = {
  /** All orgCapabilityDefault mutation keys */ all: ['mutation', 'orgcapabilitydefault'] as const,
  /** Create orgCapabilityDefault mutation key */ create: () =>
    ['mutation', 'orgcapabilitydefault', 'create'] as const,
  /** Update orgCapabilityDefault mutation key */ update: (id: string | number) =>
    ['mutation', 'orgcapabilitydefault', 'update', id] as const,
  /** Delete orgCapabilityDefault mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgcapabilitydefault', 'delete', id] as const,
} as const;
export const appCapabilityDefaultCapabilityMutationKeys = {
  /** All appCapabilityDefaultCapability mutation keys */ all: [
    'mutation',
    'appcapabilitydefaultcapability',
  ] as const,
  /** Create appCapabilityDefaultCapability mutation key */ create: () =>
    ['mutation', 'appcapabilitydefaultcapability', 'create'] as const,
  /** Update appCapabilityDefaultCapability mutation key */ update: (id: string | number) =>
    ['mutation', 'appcapabilitydefaultcapability', 'update', id] as const,
  /** Delete appCapabilityDefaultCapability mutation key */ delete: (id: string | number) =>
    ['mutation', 'appcapabilitydefaultcapability', 'delete', id] as const,
} as const;
export const appAdminGrantMutationKeys = {
  /** All appAdminGrant mutation keys */ all: ['mutation', 'appadmingrant'] as const,
  /** Create appAdminGrant mutation key */ create: () =>
    ['mutation', 'appadmingrant', 'create'] as const,
  /** Update appAdminGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'appadmingrant', 'update', id] as const,
  /** Delete appAdminGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'appadmingrant', 'delete', id] as const,
} as const;
export const appOwnerGrantMutationKeys = {
  /** All appOwnerGrant mutation keys */ all: ['mutation', 'appownergrant'] as const,
  /** Create appOwnerGrant mutation key */ create: () =>
    ['mutation', 'appownergrant', 'create'] as const,
  /** Update appOwnerGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'appownergrant', 'update', id] as const,
  /** Delete appOwnerGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'appownergrant', 'delete', id] as const,
} as const;
export const orgAdminGrantMutationKeys = {
  /** All orgAdminGrant mutation keys */ all: ['mutation', 'orgadmingrant'] as const,
  /** Create orgAdminGrant mutation key */ create: () =>
    ['mutation', 'orgadmingrant', 'create'] as const,
  /** Update orgAdminGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orgadmingrant', 'update', id] as const,
  /** Delete orgAdminGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgadmingrant', 'delete', id] as const,
} as const;
export const orgOwnerGrantMutationKeys = {
  /** All orgOwnerGrant mutation keys */ all: ['mutation', 'orgownergrant'] as const,
  /** Create orgOwnerGrant mutation key */ create: () =>
    ['mutation', 'orgownergrant', 'create'] as const,
  /** Update orgOwnerGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orgownergrant', 'update', id] as const,
  /** Delete orgOwnerGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgownergrant', 'delete', id] as const,
} as const;
export const orgChartEdgeGrantMutationKeys = {
  /** All orgChartEdgeGrant mutation keys */ all: ['mutation', 'orgchartedgegrant'] as const,
  /** Create orgChartEdgeGrant mutation key */ create: () =>
    ['mutation', 'orgchartedgegrant', 'create'] as const,
  /** Update orgChartEdgeGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orgchartedgegrant', 'update', id] as const,
  /** Delete orgChartEdgeGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgchartedgegrant', 'delete', id] as const,
} as const;
export const appClaimedInviteMutationKeys = {
  /** All appClaimedInvite mutation keys */ all: ['mutation', 'appclaimedinvite'] as const,
  /** Create appClaimedInvite mutation key */ create: () =>
    ['mutation', 'appclaimedinvite', 'create'] as const,
  /** Update appClaimedInvite mutation key */ update: (id: string | number) =>
    ['mutation', 'appclaimedinvite', 'update', id] as const,
  /** Delete appClaimedInvite mutation key */ delete: (id: string | number) =>
    ['mutation', 'appclaimedinvite', 'delete', id] as const,
} as const;
export const membershipTypeMutationKeys = {
  /** All membershipType mutation keys */ all: ['mutation', 'membershiptype'] as const,
  /** Create membershipType mutation key */ create: () =>
    ['mutation', 'membershiptype', 'create'] as const,
  /** Update membershipType mutation key */ update: (id: string | number) =>
    ['mutation', 'membershiptype', 'update', id] as const,
  /** Delete membershipType mutation key */ delete: (id: string | number) =>
    ['mutation', 'membershiptype', 'delete', id] as const,
} as const;
export const appGrantMutationKeys = {
  /** All appGrant mutation keys */ all: ['mutation', 'appgrant'] as const,
  /** Create appGrant mutation key */ create: () => ['mutation', 'appgrant', 'create'] as const,
  /** Update appGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'appgrant', 'update', id] as const,
  /** Delete appGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'appgrant', 'delete', id] as const,
} as const;
export const orgClaimedInviteMutationKeys = {
  /** All orgClaimedInvite mutation keys */ all: ['mutation', 'orgclaimedinvite'] as const,
  /** Create orgClaimedInvite mutation key */ create: () =>
    ['mutation', 'orgclaimedinvite', 'create'] as const,
  /** Update orgClaimedInvite mutation key */ update: (id: string | number) =>
    ['mutation', 'orgclaimedinvite', 'update', id] as const,
  /** Delete orgClaimedInvite mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgclaimedinvite', 'delete', id] as const,
} as const;
export const orgGrantMutationKeys = {
  /** All orgGrant mutation keys */ all: ['mutation', 'orggrant'] as const,
  /** Create orgGrant mutation key */ create: () => ['mutation', 'orggrant', 'create'] as const,
  /** Update orgGrant mutation key */ update: (id: string | number) =>
    ['mutation', 'orggrant', 'update', id] as const,
  /** Delete orgGrant mutation key */ delete: (id: string | number) =>
    ['mutation', 'orggrant', 'delete', id] as const,
} as const;
export const orgChartEdgeMutationKeys = {
  /** All orgChartEdge mutation keys */ all: ['mutation', 'orgchartedge'] as const,
  /** Create orgChartEdge mutation key */ create: () =>
    ['mutation', 'orgchartedge', 'create'] as const,
  /** Update orgChartEdge mutation key */ update: (id: string | number) =>
    ['mutation', 'orgchartedge', 'update', id] as const,
  /** Delete orgChartEdge mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgchartedge', 'delete', id] as const,
} as const;
export const appProfileTemplateMutationKeys = {
  /** All appProfileTemplate mutation keys */ all: ['mutation', 'appprofiletemplate'] as const,
  /** Create appProfileTemplate mutation key */ create: () =>
    ['mutation', 'appprofiletemplate', 'create'] as const,
  /** Update appProfileTemplate mutation key */ update: (id: string | number) =>
    ['mutation', 'appprofiletemplate', 'update', id] as const,
  /** Delete appProfileTemplate mutation key */ delete: (id: string | number) =>
    ['mutation', 'appprofiletemplate', 'delete', id] as const,
} as const;
export const orgProfileTemplateMutationKeys = {
  /** All orgProfileTemplate mutation keys */ all: ['mutation', 'orgprofiletemplate'] as const,
  /** Create orgProfileTemplate mutation key */ create: () =>
    ['mutation', 'orgprofiletemplate', 'create'] as const,
  /** Update orgProfileTemplate mutation key */ update: (id: string | number) =>
    ['mutation', 'orgprofiletemplate', 'update', id] as const,
  /** Delete orgProfileTemplate mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgprofiletemplate', 'delete', id] as const,
} as const;
export const appMembershipDefaultMutationKeys = {
  /** All appMembershipDefault mutation keys */ all: ['mutation', 'appmembershipdefault'] as const,
  /** Create appMembershipDefault mutation key */ create: () =>
    ['mutation', 'appmembershipdefault', 'create'] as const,
  /** Update appMembershipDefault mutation key */ update: (id: string | number) =>
    ['mutation', 'appmembershipdefault', 'update', id] as const,
  /** Delete appMembershipDefault mutation key */ delete: (id: string | number) =>
    ['mutation', 'appmembershipdefault', 'delete', id] as const,
} as const;
export const orgMembershipDefaultMutationKeys = {
  /** All orgMembershipDefault mutation keys */ all: ['mutation', 'orgmembershipdefault'] as const,
  /** Create orgMembershipDefault mutation key */ create: () =>
    ['mutation', 'orgmembershipdefault', 'create'] as const,
  /** Update orgMembershipDefault mutation key */ update: (id: string | number) =>
    ['mutation', 'orgmembershipdefault', 'update', id] as const,
  /** Delete orgMembershipDefault mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgmembershipdefault', 'delete', id] as const,
} as const;
export const appProfileMutationKeys = {
  /** All appProfile mutation keys */ all: ['mutation', 'appprofile'] as const,
  /** Create appProfile mutation key */ create: () => ['mutation', 'appprofile', 'create'] as const,
  /** Update appProfile mutation key */ update: (id: string | number) =>
    ['mutation', 'appprofile', 'update', id] as const,
  /** Delete appProfile mutation key */ delete: (id: string | number) =>
    ['mutation', 'appprofile', 'delete', id] as const,
} as const;
export const orgProfileMutationKeys = {
  /** All orgProfile mutation keys */ all: ['mutation', 'orgprofile'] as const,
  /** Create orgProfile mutation key */ create: () => ['mutation', 'orgprofile', 'create'] as const,
  /** Update orgProfile mutation key */ update: (id: string | number) =>
    ['mutation', 'orgprofile', 'update', id] as const,
  /** Delete orgProfile mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgprofile', 'delete', id] as const,
} as const;
export const orgMemberProfileMutationKeys = {
  /** All orgMemberProfile mutation keys */ all: ['mutation', 'orgmemberprofile'] as const,
  /** Create orgMemberProfile mutation key */ create: () =>
    ['mutation', 'orgmemberprofile', 'create'] as const,
  /** Update orgMemberProfile mutation key */ update: (id: string | number) =>
    ['mutation', 'orgmemberprofile', 'update', id] as const,
  /** Delete orgMemberProfile mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgmemberprofile', 'delete', id] as const,
} as const;
export const orgMembershipSettingMutationKeys = {
  /** All orgMembershipSetting mutation keys */ all: ['mutation', 'orgmembershipsetting'] as const,
  /** Create orgMembershipSetting mutation key */ create: () =>
    ['mutation', 'orgmembershipsetting', 'create'] as const,
  /** Update orgMembershipSetting mutation key */ update: (id: string | number) =>
    ['mutation', 'orgmembershipsetting', 'update', id] as const,
  /** Delete orgMembershipSetting mutation key */ delete: (id: string | number) =>
    ['mutation', 'orgmembershipsetting', 'delete', id] as const,
} as const;

// ============================================================================
// Custom Mutation Keys
// ============================================================================

export const customMutationKeys = {
  /** Mutation key for acceptAppInvite */ acceptAppInvite: (identifier?: string) =>
    identifier
      ? (['mutation', 'acceptAppInvite', identifier] as const)
      : (['mutation', 'acceptAppInvite'] as const),
  /** Mutation key for acceptOrgInvite */ acceptOrgInvite: (identifier?: string) =>
    identifier
      ? (['mutation', 'acceptOrgInvite', identifier] as const)
      : (['mutation', 'acceptOrgInvite'] as const),
  /** Mutation key for submitAppInviteCode */ submitAppInviteCode: (identifier?: string) =>
    identifier
      ? (['mutation', 'submitAppInviteCode', identifier] as const)
      : (['mutation', 'submitAppInviteCode'] as const),
  /** Mutation key for submitOrgInviteCode */ submitOrgInviteCode: (identifier?: string) =>
    identifier
      ? (['mutation', 'submitOrgInviteCode', identifier] as const)
      : (['mutation', 'submitOrgInviteCode'] as const),
  /** Mutation key for provisionAppUser */ provisionAppUser: (identifier?: string) =>
    identifier
      ? (['mutation', 'provisionAppUser', identifier] as const)
      : (['mutation', 'provisionAppUser'] as const),
  /** Mutation key for provisionOrgUser */ provisionOrgUser: (identifier?: string) =>
    identifier
      ? (['mutation', 'provisionOrgUser', identifier] as const)
      : (['mutation', 'provisionOrgUser'] as const),
  /** Mutation key for provisionAppUsersBulk */ provisionAppUsersBulk: (identifier?: string) =>
    identifier
      ? (['mutation', 'provisionAppUsersBulk', identifier] as const)
      : (['mutation', 'provisionAppUsersBulk'] as const),
  /** Mutation key for provisionOrgUsersBulk */ provisionOrgUsersBulk: (identifier?: string) =>
    identifier
      ? (['mutation', 'provisionOrgUsersBulk', identifier] as const)
      : (['mutation', 'provisionOrgUsersBulk'] as const),
  /** Mutation key for provisionBucket */ provisionBucket: (identifier?: string) =>
    identifier
      ? (['mutation', 'provisionBucket', identifier] as const)
      : (['mutation', 'provisionBucket'] as const),
} as const;
/**

// ============================================================================
// Unified Mutation Key Store
// ============================================================================

 * Unified mutation key store
 * 
 * Use this for tracking in-flight mutations with useIsMutating.
 * 
 * @example
 * ```ts
 * import { useIsMutating } from '@tanstack/react-query';
 * import { mutationKeys } from './generated';
 * 
 * // Check if any user mutations are in progress
 * const isMutatingUser = useIsMutating({ mutationKey: mutationKeys.user.all });
 * 
 * // Check if a specific user is being updated
 * const isUpdating = useIsMutating({ mutationKey: mutationKeys.user.update(userId) });
 * ```
 */
export const mutationKeys = {
  orgGetManagersRecord: orgGetManagersRecordMutationKeys,
  orgGetSubordinatesRecord: orgGetSubordinatesRecordMutationKeys,
  myPendingAppInvitesRecord: myPendingAppInvitesRecordMutationKeys,
  myPendingOrgInvitesRecord: myPendingOrgInvitesRecordMutationKeys,
  appCapability: appCapabilityMutationKeys,
  appCapabilityDefaultGrant: appCapabilityDefaultGrantMutationKeys,
  appProfileCapability: appProfileCapabilityMutationKeys,
  appMembership: appMembershipMutationKeys,
  appProfileGrant: appProfileGrantMutationKeys,
  appMembershipProfile: appMembershipProfileMutationKeys,
  appProfileDefinitionGrant: appProfileDefinitionGrantMutationKeys,
  appInvite: appInviteMutationKeys,
  orgCapability: orgCapabilityMutationKeys,
  orgCapabilityDefaultCapability: orgCapabilityDefaultCapabilityMutationKeys,
  orgCapabilityDefaultGrant: orgCapabilityDefaultGrantMutationKeys,
  orgProfileCapability: orgProfileCapabilityMutationKeys,
  orgMembership: orgMembershipMutationKeys,
  orgProfileGrant: orgProfileGrantMutationKeys,
  orgMembershipProfile: orgMembershipProfileMutationKeys,
  orgProfileDefinitionGrant: orgProfileDefinitionGrantMutationKeys,
  orgInvite: orgInviteMutationKeys,
  orgMember: orgMemberMutationKeys,
  appCapabilityDefault: appCapabilityDefaultMutationKeys,
  orgCapabilityDefault: orgCapabilityDefaultMutationKeys,
  appCapabilityDefaultCapability: appCapabilityDefaultCapabilityMutationKeys,
  appAdminGrant: appAdminGrantMutationKeys,
  appOwnerGrant: appOwnerGrantMutationKeys,
  orgAdminGrant: orgAdminGrantMutationKeys,
  orgOwnerGrant: orgOwnerGrantMutationKeys,
  orgChartEdgeGrant: orgChartEdgeGrantMutationKeys,
  appClaimedInvite: appClaimedInviteMutationKeys,
  membershipType: membershipTypeMutationKeys,
  appGrant: appGrantMutationKeys,
  orgClaimedInvite: orgClaimedInviteMutationKeys,
  orgGrant: orgGrantMutationKeys,
  orgChartEdge: orgChartEdgeMutationKeys,
  appProfileTemplate: appProfileTemplateMutationKeys,
  orgProfileTemplate: orgProfileTemplateMutationKeys,
  appMembershipDefault: appMembershipDefaultMutationKeys,
  orgMembershipDefault: orgMembershipDefaultMutationKeys,
  appProfile: appProfileMutationKeys,
  orgProfile: orgProfileMutationKeys,
  orgMemberProfile: orgMemberProfileMutationKeys,
  orgMembershipSetting: orgMembershipSettingMutationKeys,
  custom: customMutationKeys,
} as const;
