-- Revert: schemas/myapp_memberships_public/tables/app_permission_default_permissions/indexes/app_permission_default_permissions_updated_at_idx


DROP INDEX myapp_memberships_public.app_permission_default_permissions_updated_at_idx;


