/**
 * Custom query operations
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import { QueryBuilder, buildCustomDocument } from '../query-builder';
import type { InferSelectResult, StrictSelect } from '../select-types';
import type {
  GetMfaStatusRecord,
  User,
  GetMfaStatusRecordSelect,
  UserSelect,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export interface IsVerificationExemptVariables {
  userId?: string;
}
export interface RequireStepUpVariables {
  stepUpType?: string;
}
export function createQueryOperations(client: OrmClient) {
  return {
    currentUserId: (options?: { select?: Record<string, unknown> }) =>
      new QueryBuilder<{
        currentUserId: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentUserId',
        fieldName: 'currentUserId',
        ...buildCustomDocument(
          'query',
          'CurrentUserId',
          'currentUserId',
          options?.select,
          undefined,
          [],
          connectionFieldsMap,
          undefined
        ),
      }),
    currentUserAgent: (options?: { select?: Record<string, unknown> }) =>
      new QueryBuilder<{
        currentUserAgent: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentUserAgent',
        fieldName: 'currentUserAgent',
        ...buildCustomDocument(
          'query',
          'CurrentUserAgent',
          'currentUserAgent',
          options?.select,
          undefined,
          [],
          connectionFieldsMap,
          undefined
        ),
      }),
    currentIpAddress: (options?: { select?: Record<string, unknown> }) =>
      new QueryBuilder<{
        currentIpAddress: string | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentIpAddress',
        fieldName: 'currentIpAddress',
        ...buildCustomDocument(
          'query',
          'CurrentIpAddress',
          'currentIpAddress',
          options?.select,
          undefined,
          [],
          connectionFieldsMap,
          undefined
        ),
      }),
    isVerificationExempt: (
      args: IsVerificationExemptVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        isVerificationExempt: boolean | null;
      }>({
        client,
        operation: 'query',
        operationName: 'IsVerificationExempt',
        fieldName: 'isVerificationExempt',
        ...buildCustomDocument(
          'query',
          'IsVerificationExempt',
          'isVerificationExempt',
          options?.select,
          args,
          [
            {
              name: 'userId',
              type: 'UUID',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    requireStepUp: (
      args: RequireStepUpVariables,
      options?: {
        select?: Record<string, unknown>;
      }
    ) =>
      new QueryBuilder<{
        requireStepUp: boolean | null;
      }>({
        client,
        operation: 'query',
        operationName: 'RequireStepUp',
        fieldName: 'requireStepUp',
        ...buildCustomDocument(
          'query',
          'RequireStepUp',
          'requireStepUp',
          options?.select,
          args,
          [
            {
              name: 'stepUpType',
              type: 'String',
            },
          ],
          connectionFieldsMap,
          undefined
        ),
      }),
    getMfaStatus: <S extends GetMfaStatusRecordSelect>(
      options: {
        select: S;
      } & StrictSelect<S, GetMfaStatusRecordSelect>
    ) =>
      new QueryBuilder<{
        getMfaStatus: InferSelectResult<GetMfaStatusRecord, S> | null;
      }>({
        client,
        operation: 'query',
        operationName: 'GetMfaStatus',
        fieldName: 'getMfaStatus',
        ...buildCustomDocument(
          'query',
          'GetMfaStatus',
          'getMfaStatus',
          options.select,
          undefined,
          [],
          connectionFieldsMap,
          'GetMfaStatusRecord'
        ),
      }),
    currentUser: <S extends UserSelect>(
      options: {
        select: S;
      } & StrictSelect<S, UserSelect>
    ) =>
      new QueryBuilder<{
        currentUser: InferSelectResult<User, S> | null;
      }>({
        client,
        operation: 'query',
        operationName: 'CurrentUser',
        fieldName: 'currentUser',
        ...buildCustomDocument(
          'query',
          'CurrentUser',
          'currentUser',
          options.select,
          undefined,
          [],
          connectionFieldsMap,
          'User'
        ),
      }),
  };
}
