-- Revert: schemas/myapp_memberships_public/tables/app_membership_defaults/triggers/app_membership_defaults_insert_trg


DROP TRIGGER app_membership_defaults_insert_trg ON myapp_memberships_public.app_membership_defaults;


