/**
 * Join table linking profiles to individual capabilities they include
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appProfileCapabilityKeys } from '../query-keys';
import type {
  AppProfileCapabilitySelect,
  AppProfileCapabilityWithRelations,
  AppProfileCapabilityFilter,
  AppProfileCapabilityOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppProfileCapabilitySelect,
  AppProfileCapabilityWithRelations,
  AppProfileCapabilityFilter,
  AppProfileCapabilityOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appProfileCapabilitiesQueryKey = appProfileCapabilityKeys.list;
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppProfileCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppProfileCapabilitiesQuery<
  S extends AppProfileCapabilitySelect,
  TData = {
    appProfileCapabilities: ConnectionResult<
      InferSelectResult<AppProfileCapabilityWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, AppProfileCapabilityFilter, AppProfileCapabilityOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, AppProfileCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        appProfileCapabilities: ConnectionResult<
          InferSelectResult<AppProfileCapabilityWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppProfileCapabilitiesQuery(
  params: {
    selection: ListSelectionConfig<
      AppProfileCapabilitySelect,
      AppProfileCapabilityFilter,
      AppProfileCapabilityOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    AppProfileCapabilitySelect,
    AppProfileCapabilityFilter,
    AppProfileCapabilityOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appProfileCapabilityKeys.list(args),
    queryFn: () => getClient().appProfileCapability.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```ts
 * const data = await fetchAppProfileCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppProfileCapabilitiesQuery<
  S extends AppProfileCapabilitySelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, AppProfileCapabilityFilter, AppProfileCapabilityOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, AppProfileCapabilitySelect>;
}): Promise<{
  appProfileCapabilities: ConnectionResult<InferSelectResult<AppProfileCapabilityWithRelations, S>>;
}>;
export async function fetchAppProfileCapabilitiesQuery(params: {
  selection: ListSelectionConfig<
    AppProfileCapabilitySelect,
    AppProfileCapabilityFilter,
    AppProfileCapabilityOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    AppProfileCapabilitySelect,
    AppProfileCapabilityFilter,
    AppProfileCapabilityOrderBy
  >(params.selection);
  return getClient().appProfileCapability.findMany(args).unwrap();
}
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```ts
 * await prefetchAppProfileCapabilitiesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppProfileCapabilitiesQuery<S extends AppProfileCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, AppProfileCapabilityFilter, AppProfileCapabilityOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, AppProfileCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchAppProfileCapabilitiesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      AppProfileCapabilitySelect,
      AppProfileCapabilityFilter,
      AppProfileCapabilityOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    AppProfileCapabilitySelect,
    AppProfileCapabilityFilter,
    AppProfileCapabilityOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appProfileCapabilityKeys.list(args),
    queryFn: () => getClient().appProfileCapability.findMany(args).unwrap(),
  });
}
