/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appCapabilityKeys } from '../query-keys';
import type {
  AppCapabilitySelect,
  AppCapabilityWithRelations,
  AppCapabilityFilter,
  AppCapabilityOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppCapabilitySelect,
  AppCapabilityWithRelations,
  AppCapabilityFilter,
  AppCapabilityOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilitiesQueryKey = appCapabilityKeys.list;
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppCapabilitiesQuery<
  S extends AppCapabilitySelect,
  TData = {
    appCapabilities: ConnectionResult<InferSelectResult<AppCapabilityWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppCapabilityFilter, AppCapabilityOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilities: ConnectionResult<InferSelectResult<AppCapabilityWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilitiesQuery(
  params: {
    selection: ListSelectionConfig<AppCapabilitySelect, AppCapabilityFilter, AppCapabilityOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    AppCapabilitySelect,
    AppCapabilityFilter,
    AppCapabilityOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appCapabilityKeys.list(args),
    queryFn: () => getClient().appCapability.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppCapabilitiesQuery<S extends AppCapabilitySelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppCapabilityFilter, AppCapabilityOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppCapabilitySelect>;
}): Promise<{
  appCapabilities: ConnectionResult<InferSelectResult<AppCapabilityWithRelations, S>>;
}>;
export async function fetchAppCapabilitiesQuery(params: {
  selection: ListSelectionConfig<AppCapabilitySelect, AppCapabilityFilter, AppCapabilityOrderBy>;
}) {
  const args = buildListSelectionArgs<
    AppCapabilitySelect,
    AppCapabilityFilter,
    AppCapabilityOrderBy
  >(params.selection);
  return getClient().appCapability.findMany(args).unwrap();
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * await prefetchAppCapabilitiesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppCapabilitiesQuery<S extends AppCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppCapabilityFilter, AppCapabilityOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchAppCapabilitiesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppCapabilitySelect, AppCapabilityFilter, AppCapabilityOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    AppCapabilitySelect,
    AppCapabilityFilter,
    AppCapabilityOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appCapabilityKeys.list(args),
    queryFn: () => getClient().appCapability.findMany(args).unwrap(),
  });
}
