/**
 * Audit log of capability additions and removals from the defaults bitmask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appCapabilityDefaultGrantKeys } from '../query-keys';
import type {
  AppCapabilityDefaultGrantSelect,
  AppCapabilityDefaultGrantWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  AppCapabilityDefaultGrantSelect,
  AppCapabilityDefaultGrantWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilityDefaultGrantQueryKey = appCapabilityDefaultGrantKeys.detail;
/**
 * Audit log of capability additions and removals from the defaults bitmask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilityDefaultGrantQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppCapabilityDefaultGrantQuery<
  S extends AppCapabilityDefaultGrantSelect,
  TData = {
    appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppCapabilityDefaultGrantSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilityDefaultGrant: InferSelectResult<
          AppCapabilityDefaultGrantWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilityDefaultGrantQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppCapabilityDefaultGrantSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppCapabilityDefaultGrantSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appCapabilityDefaultGrantKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appCapabilityDefaultGrant.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Audit log of capability additions and removals from the defaults bitmask
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilityDefaultGrantQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppCapabilityDefaultGrantQuery<
  S extends AppCapabilityDefaultGrantSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppCapabilityDefaultGrantSelect>;
}): Promise<{
  appCapabilityDefaultGrant: InferSelectResult<AppCapabilityDefaultGrantWithRelations, S> | null;
}>;
export async function fetchAppCapabilityDefaultGrantQuery(params: {
  id: string;
  selection: SelectionConfig<AppCapabilityDefaultGrantSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppCapabilityDefaultGrantSelect>(params.selection);
  return getClient()
    .appCapabilityDefaultGrant.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Audit log of capability additions and removals from the defaults bitmask
 *
 * @example
 * ```ts
 * await prefetchAppCapabilityDefaultGrantQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppCapabilityDefaultGrantQuery<
  S extends AppCapabilityDefaultGrantSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppCapabilityDefaultGrantSelect>;
  }
): Promise<void>;
export async function prefetchAppCapabilityDefaultGrantQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppCapabilityDefaultGrantSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppCapabilityDefaultGrantSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appCapabilityDefaultGrantKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appCapabilityDefaultGrant.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
