/**
 * Custom query hook for appCapabilitiesGetMaskByNames
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { AppCapabilitiesGetMaskByNamesVariables } from '../../orm/query';
export type { AppCapabilitiesGetMaskByNamesVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilitiesGetMaskByNamesQueryKey = customQueryKeys.appCapabilitiesGetMaskByNames;
/**
 * Query hook for appCapabilitiesGetMaskByNames
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilitiesGetMaskByNamesQuery({ variables: { names } });
 *
 * if (data?.appCapabilitiesGetMaskByNames) {
 *   console.log(data.appCapabilitiesGetMaskByNames);
 * }
 * ```
 */
export function useAppCapabilitiesGetMaskByNamesQuery<
  TData = {
    appCapabilitiesGetMaskByNames: string | null;
  },
>(
  params?: {
    variables?: AppCapabilitiesGetMaskByNamesVariables;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilitiesGetMaskByNames: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilitiesGetMaskByNamesQuery<
  TData = {
    appCapabilitiesGetMaskByNames: string | null;
  },
>(
  params?: {
    variables?: AppCapabilitiesGetMaskByNamesVariables;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilitiesGetMaskByNames: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: appCapabilitiesGetMaskByNamesQueryKey(variables),
    queryFn: () => getClient().query.appCapabilitiesGetMaskByNames(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch appCapabilitiesGetMaskByNames without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilitiesGetMaskByNamesQuery({ variables: { names } });
 * ```
 */
export async function fetchAppCapabilitiesGetMaskByNamesQuery(params?: {
  variables?: AppCapabilitiesGetMaskByNamesVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.appCapabilitiesGetMaskByNames(variables).unwrap();
}
/**
 * Prefetch appCapabilitiesGetMaskByNames for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppCapabilitiesGetMaskByNamesQuery(queryClient, { variables: { names } });
 * ```
 */
export async function prefetchAppCapabilitiesGetMaskByNamesQuery(
  queryClient: QueryClient,
  params?: {
    variables?: AppCapabilitiesGetMaskByNamesVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: appCapabilitiesGetMaskByNamesQueryKey(variables),
    queryFn: () => getClient().query.appCapabilitiesGetMaskByNames(variables).unwrap(),
  });
}
