/**
 * Join table linking profiles to individual capabilities they include
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appProfileCapabilityKeys } from '../query-keys';
import type {
  AppProfileCapabilitySelect,
  AppProfileCapabilityWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  AppProfileCapabilitySelect,
  AppProfileCapabilityWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appProfileCapabilityQueryKey = appProfileCapabilityKeys.detail;
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppProfileCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppProfileCapabilityQuery<
  S extends AppProfileCapabilitySelect,
  TData = {
    appProfileCapability: InferSelectResult<AppProfileCapabilityWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppProfileCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        appProfileCapability: InferSelectResult<AppProfileCapabilityWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppProfileCapabilityQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppProfileCapabilitySelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppProfileCapabilitySelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appProfileCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appProfileCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```ts
 * const data = await fetchAppProfileCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppProfileCapabilityQuery<S extends AppProfileCapabilitySelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppProfileCapabilitySelect>;
}): Promise<{
  appProfileCapability: InferSelectResult<AppProfileCapabilityWithRelations, S> | null;
}>;
export async function fetchAppProfileCapabilityQuery(params: {
  id: string;
  selection: SelectionConfig<AppProfileCapabilitySelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppProfileCapabilitySelect>(params.selection);
  return getClient()
    .appProfileCapability.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```ts
 * await prefetchAppProfileCapabilityQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppProfileCapabilityQuery<S extends AppProfileCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppProfileCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchAppProfileCapabilityQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppProfileCapabilitySelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppProfileCapabilitySelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appProfileCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appProfileCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
