/**
 * Stores the default capability bitmask assigned to new members upon joining
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appCapabilityDefaultKeys } from '../query-keys';
import type {
  AppCapabilityDefaultSelect,
  AppCapabilityDefaultWithRelations,
  AppCapabilityDefaultFilter,
  AppCapabilityDefaultOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppCapabilityDefaultSelect,
  AppCapabilityDefaultWithRelations,
  AppCapabilityDefaultFilter,
  AppCapabilityDefaultOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilityDefaultsQueryKey = appCapabilityDefaultKeys.list;
/**
 * Stores the default capability bitmask assigned to new members upon joining
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilityDefaultsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppCapabilityDefaultsQuery<
  S extends AppCapabilityDefaultSelect,
  TData = {
    appCapabilityDefaults: ConnectionResult<
      InferSelectResult<AppCapabilityDefaultWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, AppCapabilityDefaultFilter, AppCapabilityDefaultOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, AppCapabilityDefaultSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilityDefaults: ConnectionResult<
          InferSelectResult<AppCapabilityDefaultWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilityDefaultsQuery(
  params: {
    selection: ListSelectionConfig<
      AppCapabilityDefaultSelect,
      AppCapabilityDefaultFilter,
      AppCapabilityDefaultOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    AppCapabilityDefaultSelect,
    AppCapabilityDefaultFilter,
    AppCapabilityDefaultOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appCapabilityDefaultKeys.list(args),
    queryFn: () => getClient().appCapabilityDefault.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Stores the default capability bitmask assigned to new members upon joining
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilityDefaultsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppCapabilityDefaultsQuery<
  S extends AppCapabilityDefaultSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, AppCapabilityDefaultFilter, AppCapabilityDefaultOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, AppCapabilityDefaultSelect>;
}): Promise<{
  appCapabilityDefaults: ConnectionResult<InferSelectResult<AppCapabilityDefaultWithRelations, S>>;
}>;
export async function fetchAppCapabilityDefaultsQuery(params: {
  selection: ListSelectionConfig<
    AppCapabilityDefaultSelect,
    AppCapabilityDefaultFilter,
    AppCapabilityDefaultOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    AppCapabilityDefaultSelect,
    AppCapabilityDefaultFilter,
    AppCapabilityDefaultOrderBy
  >(params.selection);
  return getClient().appCapabilityDefault.findMany(args).unwrap();
}
/**
 * Stores the default capability bitmask assigned to new members upon joining
 *
 * @example
 * ```ts
 * await prefetchAppCapabilityDefaultsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppCapabilityDefaultsQuery<S extends AppCapabilityDefaultSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, AppCapabilityDefaultFilter, AppCapabilityDefaultOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, AppCapabilityDefaultSelect>;
  }
): Promise<void>;
export async function prefetchAppCapabilityDefaultsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      AppCapabilityDefaultSelect,
      AppCapabilityDefaultFilter,
      AppCapabilityDefaultOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    AppCapabilityDefaultSelect,
    AppCapabilityDefaultFilter,
    AppCapabilityDefaultOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appCapabilityDefaultKeys.list(args),
    queryFn: () => getClient().appCapabilityDefault.findMany(args).unwrap(),
  });
}
