/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appProfileKeys } from '../query-keys';
import type {
  AppProfileSelect,
  AppProfileWithRelations,
  AppProfileFilter,
  AppProfileOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppProfileSelect,
  AppProfileWithRelations,
  AppProfileFilter,
  AppProfileOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appProfilesQueryKey = appProfileKeys.list;
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppProfilesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppProfilesQuery<
  S extends AppProfileSelect,
  TData = {
    appProfiles: ConnectionResult<InferSelectResult<AppProfileWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppProfileFilter, AppProfileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppProfileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appProfiles: ConnectionResult<InferSelectResult<AppProfileWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppProfilesQuery(
  params: {
    selection: ListSelectionConfig<AppProfileSelect, AppProfileFilter, AppProfileOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<AppProfileSelect, AppProfileFilter, AppProfileOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appProfileKeys.list(args),
    queryFn: () => getClient().appProfile.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```ts
 * const data = await fetchAppProfilesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppProfilesQuery<S extends AppProfileSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AppProfileFilter, AppProfileOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AppProfileSelect>;
}): Promise<{
  appProfiles: ConnectionResult<InferSelectResult<AppProfileWithRelations, S>>;
}>;
export async function fetchAppProfilesQuery(params: {
  selection: ListSelectionConfig<AppProfileSelect, AppProfileFilter, AppProfileOrderBy>;
}) {
  const args = buildListSelectionArgs<AppProfileSelect, AppProfileFilter, AppProfileOrderBy>(
    params.selection
  );
  return getClient().appProfile.findMany(args).unwrap();
}
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```ts
 * await prefetchAppProfilesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppProfilesQuery<S extends AppProfileSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AppProfileFilter, AppProfileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AppProfileSelect>;
  }
): Promise<void>;
export async function prefetchAppProfilesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AppProfileSelect, AppProfileFilter, AppProfileOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<AppProfileSelect, AppProfileFilter, AppProfileOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: appProfileKeys.list(args),
    queryFn: () => getClient().appProfile.findMany(args).unwrap(),
  });
}
