/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appCapabilityKeys } from '../query-keys';
import type { AppCapabilitySelect, AppCapabilityWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppCapabilitySelect, AppCapabilityWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilityQueryKey = appCapabilityKeys.detail;
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppCapabilityQuery<
  S extends AppCapabilitySelect,
  TData = {
    appCapability: InferSelectResult<AppCapabilityWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        appCapability: InferSelectResult<AppCapabilityWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilityQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppCapabilitySelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppCapabilitySelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppCapabilityQuery<S extends AppCapabilitySelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppCapabilitySelect>;
}): Promise<{
  appCapability: InferSelectResult<AppCapabilityWithRelations, S> | null;
}>;
export async function fetchAppCapabilityQuery(params: {
  id: string;
  selection: SelectionConfig<AppCapabilitySelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppCapabilitySelect>(params.selection);
  return getClient()
    .appCapability.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * await prefetchAppCapabilityQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppCapabilityQuery<S extends AppCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchAppCapabilityQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppCapabilitySelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppCapabilitySelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
