/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { appCapabilityDefaultCapabilityKeys } from '../query-keys';
import type {
  AppCapabilityDefaultCapabilitySelect,
  AppCapabilityDefaultCapabilityWithRelations,
  AppCapabilityDefaultCapabilityFilter,
  AppCapabilityDefaultCapabilityOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AppCapabilityDefaultCapabilitySelect,
  AppCapabilityDefaultCapabilityWithRelations,
  AppCapabilityDefaultCapabilityFilter,
  AppCapabilityDefaultCapabilityOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilityDefaultCapabilitiesQueryKey = appCapabilityDefaultCapabilityKeys.list;
/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilityDefaultCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAppCapabilityDefaultCapabilitiesQuery<
  S extends AppCapabilityDefaultCapabilitySelect,
  TData = {
    appCapabilityDefaultCapabilities: ConnectionResult<
      InferSelectResult<AppCapabilityDefaultCapabilityWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<
        S,
        AppCapabilityDefaultCapabilityFilter,
        AppCapabilityDefaultCapabilityOrderBy
      >,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, AppCapabilityDefaultCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilityDefaultCapabilities: ConnectionResult<
          InferSelectResult<AppCapabilityDefaultCapabilityWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilityDefaultCapabilitiesQuery(
  params: {
    selection: ListSelectionConfig<
      AppCapabilityDefaultCapabilitySelect,
      AppCapabilityDefaultCapabilityFilter,
      AppCapabilityDefaultCapabilityOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    AppCapabilityDefaultCapabilitySelect,
    AppCapabilityDefaultCapabilityFilter,
    AppCapabilityDefaultCapabilityOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appCapabilityDefaultCapabilityKeys.list(args),
    queryFn: () => getClient().appCapabilityDefaultCapability.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilityDefaultCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAppCapabilityDefaultCapabilitiesQuery<
  S extends AppCapabilityDefaultCapabilitySelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<
      S,
      AppCapabilityDefaultCapabilityFilter,
      AppCapabilityDefaultCapabilityOrderBy
    >,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, AppCapabilityDefaultCapabilitySelect>;
}): Promise<{
  appCapabilityDefaultCapabilities: ConnectionResult<
    InferSelectResult<AppCapabilityDefaultCapabilityWithRelations, S>
  >;
}>;
export async function fetchAppCapabilityDefaultCapabilitiesQuery(params: {
  selection: ListSelectionConfig<
    AppCapabilityDefaultCapabilitySelect,
    AppCapabilityDefaultCapabilityFilter,
    AppCapabilityDefaultCapabilityOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    AppCapabilityDefaultCapabilitySelect,
    AppCapabilityDefaultCapabilityFilter,
    AppCapabilityDefaultCapabilityOrderBy
  >(params.selection);
  return getClient().appCapabilityDefaultCapability.findMany(args).unwrap();
}
/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 *
 * @example
 * ```ts
 * await prefetchAppCapabilityDefaultCapabilitiesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAppCapabilityDefaultCapabilitiesQuery<
  S extends AppCapabilityDefaultCapabilitySelect,
>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<
        S,
        AppCapabilityDefaultCapabilityFilter,
        AppCapabilityDefaultCapabilityOrderBy
      >,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, AppCapabilityDefaultCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchAppCapabilityDefaultCapabilitiesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      AppCapabilityDefaultCapabilitySelect,
      AppCapabilityDefaultCapabilityFilter,
      AppCapabilityDefaultCapabilityOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    AppCapabilityDefaultCapabilitySelect,
    AppCapabilityDefaultCapabilityFilter,
    AppCapabilityDefaultCapabilityOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appCapabilityDefaultCapabilityKeys.list(args),
    queryFn: () => getClient().appCapabilityDefaultCapability.findMany(args).unwrap(),
  });
}
