/**
 * Custom query hook for appCapabilitiesGetMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { AppCapabilitiesGetMaskVariables } from '../../orm/query';
export type { AppCapabilitiesGetMaskVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const appCapabilitiesGetMaskQueryKey = customQueryKeys.appCapabilitiesGetMask;
/**
 * Query hook for appCapabilitiesGetMask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppCapabilitiesGetMaskQuery({ variables: { ids } });
 *
 * if (data?.appCapabilitiesGetMask) {
 *   console.log(data.appCapabilitiesGetMask);
 * }
 * ```
 */
export function useAppCapabilitiesGetMaskQuery<
  TData = {
    appCapabilitiesGetMask: string | null;
  },
>(
  params?: {
    variables?: AppCapabilitiesGetMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilitiesGetMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppCapabilitiesGetMaskQuery<
  TData = {
    appCapabilitiesGetMask: string | null;
  },
>(
  params?: {
    variables?: AppCapabilitiesGetMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        appCapabilitiesGetMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: appCapabilitiesGetMaskQueryKey(variables),
    queryFn: () => getClient().query.appCapabilitiesGetMask(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch appCapabilitiesGetMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppCapabilitiesGetMaskQuery({ variables: { ids } });
 * ```
 */
export async function fetchAppCapabilitiesGetMaskQuery(params?: {
  variables?: AppCapabilitiesGetMaskVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.appCapabilitiesGetMask(variables).unwrap();
}
/**
 * Prefetch appCapabilitiesGetMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppCapabilitiesGetMaskQuery(queryClient, { variables: { ids } });
 * ```
 */
export async function prefetchAppCapabilitiesGetMaskQuery(
  queryClient: QueryClient,
  params?: {
    variables?: AppCapabilitiesGetMaskVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: appCapabilitiesGetMaskQueryKey(variables),
    queryFn: () => getClient().query.appCapabilitiesGetMask(variables).unwrap(),
  });
}
