/**
 * Single item query hook for MyPendingOrgInvitesRecord
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { myPendingOrgInvitesRecordKeys } from '../query-keys';
import type {
  MyPendingOrgInvitesRecordSelect,
  MyPendingOrgInvitesRecordWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  MyPendingOrgInvitesRecordSelect,
  MyPendingOrgInvitesRecordWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const myPendingOrgInvitesRecordQueryKey = myPendingOrgInvitesRecordKeys.detail;
/**
 * Query hook for fetching a single MyPendingOrgInvitesRecord
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useMyPendingOrgInvitesRecordQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useMyPendingOrgInvitesRecordQuery<
  S extends MyPendingOrgInvitesRecordSelect,
  TData = {
    myPendingOrgInvitesRecord: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, MyPendingOrgInvitesRecordSelect>;
  } & Omit<
    UseQueryOptions<
      {
        myPendingOrgInvitesRecord: InferSelectResult<
          MyPendingOrgInvitesRecordWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useMyPendingOrgInvitesRecordQuery(
  params: {
    id: string;
    selection: SelectionConfig<MyPendingOrgInvitesRecordSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<MyPendingOrgInvitesRecordSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: myPendingOrgInvitesRecordKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .myPendingOrgInvitesRecord.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single MyPendingOrgInvitesRecord without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchMyPendingOrgInvitesRecordQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchMyPendingOrgInvitesRecordQuery<
  S extends MyPendingOrgInvitesRecordSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, MyPendingOrgInvitesRecordSelect>;
}): Promise<{
  myPendingOrgInvitesRecord: InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S> | null;
}>;
export async function fetchMyPendingOrgInvitesRecordQuery(params: {
  id: string;
  selection: SelectionConfig<MyPendingOrgInvitesRecordSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<MyPendingOrgInvitesRecordSelect>(params.selection);
  return getClient()
    .myPendingOrgInvitesRecord.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single MyPendingOrgInvitesRecord for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchMyPendingOrgInvitesRecordQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchMyPendingOrgInvitesRecordQuery<
  S extends MyPendingOrgInvitesRecordSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, MyPendingOrgInvitesRecordSelect>;
  }
): Promise<void>;
export async function prefetchMyPendingOrgInvitesRecordQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<MyPendingOrgInvitesRecordSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<MyPendingOrgInvitesRecordSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: myPendingOrgInvitesRecordKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .myPendingOrgInvitesRecord.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
