/**
 * List query hook for MyPendingOrgInvitesRecord
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { myPendingOrgInvitesRecordKeys } from '../query-keys';
import type {
  MyPendingOrgInvitesRecordSelect,
  MyPendingOrgInvitesRecordWithRelations,
  MyPendingOrgInvitesRecordFilter,
  MyPendingOrgInvitesRecordsOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  MyPendingOrgInvitesRecordSelect,
  MyPendingOrgInvitesRecordWithRelations,
  MyPendingOrgInvitesRecordFilter,
  MyPendingOrgInvitesRecordsOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const myPendingOrgInvitesQueryKey = myPendingOrgInvitesRecordKeys.list;
/**
 * Query hook for fetching MyPendingOrgInvitesRecord list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useMyPendingOrgInvitesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useMyPendingOrgInvitesQuery<
  S extends MyPendingOrgInvitesRecordSelect,
  TData = {
    myPendingOrgInvites: ConnectionResult<
      InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, MyPendingOrgInvitesRecordFilter, MyPendingOrgInvitesRecordsOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, MyPendingOrgInvitesRecordSelect>;
  } & Omit<
    UseQueryOptions<
      {
        myPendingOrgInvites: ConnectionResult<
          InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useMyPendingOrgInvitesQuery(
  params: {
    selection: ListSelectionConfig<
      MyPendingOrgInvitesRecordSelect,
      MyPendingOrgInvitesRecordFilter,
      MyPendingOrgInvitesRecordsOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    MyPendingOrgInvitesRecordSelect,
    MyPendingOrgInvitesRecordFilter,
    MyPendingOrgInvitesRecordsOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: myPendingOrgInvitesRecordKeys.list(args),
    queryFn: () => getClient().myPendingOrgInvitesRecord.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch MyPendingOrgInvitesRecord list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchMyPendingOrgInvitesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchMyPendingOrgInvitesQuery<
  S extends MyPendingOrgInvitesRecordSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, MyPendingOrgInvitesRecordFilter, MyPendingOrgInvitesRecordsOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, MyPendingOrgInvitesRecordSelect>;
}): Promise<{
  myPendingOrgInvites: ConnectionResult<
    InferSelectResult<MyPendingOrgInvitesRecordWithRelations, S>
  >;
}>;
export async function fetchMyPendingOrgInvitesQuery(params: {
  selection: ListSelectionConfig<
    MyPendingOrgInvitesRecordSelect,
    MyPendingOrgInvitesRecordFilter,
    MyPendingOrgInvitesRecordsOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    MyPendingOrgInvitesRecordSelect,
    MyPendingOrgInvitesRecordFilter,
    MyPendingOrgInvitesRecordsOrderBy
  >(params.selection);
  return getClient().myPendingOrgInvitesRecord.findMany(args).unwrap();
}
/**
 * Prefetch MyPendingOrgInvitesRecord list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchMyPendingOrgInvitesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchMyPendingOrgInvitesQuery<S extends MyPendingOrgInvitesRecordSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, MyPendingOrgInvitesRecordFilter, MyPendingOrgInvitesRecordsOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, MyPendingOrgInvitesRecordSelect>;
  }
): Promise<void>;
export async function prefetchMyPendingOrgInvitesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      MyPendingOrgInvitesRecordSelect,
      MyPendingOrgInvitesRecordFilter,
      MyPendingOrgInvitesRecordsOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    MyPendingOrgInvitesRecordSelect,
    MyPendingOrgInvitesRecordFilter,
    MyPendingOrgInvitesRecordsOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: myPendingOrgInvitesRecordKeys.list(args),
    queryFn: () => getClient().myPendingOrgInvitesRecord.findMany(args).unwrap(),
  });
}
