/**
 * List query hook for MyPendingAppInvitesRecord
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { myPendingAppInvitesRecordKeys } from '../query-keys';
import type {
  MyPendingAppInvitesRecordSelect,
  MyPendingAppInvitesRecordWithRelations,
  MyPendingAppInvitesRecordFilter,
  MyPendingAppInvitesRecordsOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  MyPendingAppInvitesRecordSelect,
  MyPendingAppInvitesRecordWithRelations,
  MyPendingAppInvitesRecordFilter,
  MyPendingAppInvitesRecordsOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const myPendingAppInvitesQueryKey = myPendingAppInvitesRecordKeys.list;
/**
 * Query hook for fetching MyPendingAppInvitesRecord list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useMyPendingAppInvitesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useMyPendingAppInvitesQuery<
  S extends MyPendingAppInvitesRecordSelect,
  TData = {
    myPendingAppInvites: ConnectionResult<
      InferSelectResult<MyPendingAppInvitesRecordWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, MyPendingAppInvitesRecordFilter, MyPendingAppInvitesRecordsOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, MyPendingAppInvitesRecordSelect>;
  } & Omit<
    UseQueryOptions<
      {
        myPendingAppInvites: ConnectionResult<
          InferSelectResult<MyPendingAppInvitesRecordWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useMyPendingAppInvitesQuery(
  params: {
    selection: ListSelectionConfig<
      MyPendingAppInvitesRecordSelect,
      MyPendingAppInvitesRecordFilter,
      MyPendingAppInvitesRecordsOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    MyPendingAppInvitesRecordSelect,
    MyPendingAppInvitesRecordFilter,
    MyPendingAppInvitesRecordsOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: myPendingAppInvitesRecordKeys.list(args),
    queryFn: () => getClient().myPendingAppInvitesRecord.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch MyPendingAppInvitesRecord list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchMyPendingAppInvitesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchMyPendingAppInvitesQuery<
  S extends MyPendingAppInvitesRecordSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, MyPendingAppInvitesRecordFilter, MyPendingAppInvitesRecordsOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, MyPendingAppInvitesRecordSelect>;
}): Promise<{
  myPendingAppInvites: ConnectionResult<
    InferSelectResult<MyPendingAppInvitesRecordWithRelations, S>
  >;
}>;
export async function fetchMyPendingAppInvitesQuery(params: {
  selection: ListSelectionConfig<
    MyPendingAppInvitesRecordSelect,
    MyPendingAppInvitesRecordFilter,
    MyPendingAppInvitesRecordsOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    MyPendingAppInvitesRecordSelect,
    MyPendingAppInvitesRecordFilter,
    MyPendingAppInvitesRecordsOrderBy
  >(params.selection);
  return getClient().myPendingAppInvitesRecord.findMany(args).unwrap();
}
/**
 * Prefetch MyPendingAppInvitesRecord list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchMyPendingAppInvitesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchMyPendingAppInvitesQuery<S extends MyPendingAppInvitesRecordSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, MyPendingAppInvitesRecordFilter, MyPendingAppInvitesRecordsOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, MyPendingAppInvitesRecordSelect>;
  }
): Promise<void>;
export async function prefetchMyPendingAppInvitesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      MyPendingAppInvitesRecordSelect,
      MyPendingAppInvitesRecordFilter,
      MyPendingAppInvitesRecordsOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    MyPendingAppInvitesRecordSelect,
    MyPendingAppInvitesRecordFilter,
    MyPendingAppInvitesRecordsOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: myPendingAppInvitesRecordKeys.list(args),
    queryFn: () => getClient().myPendingAppInvitesRecord.findMany(args).unwrap(),
  });
}
