/**
 * Custom query hook for orgCapabilitiesGetMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { OrgCapabilitiesGetMaskVariables } from '../../orm/query';
export type { OrgCapabilitiesGetMaskVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilitiesGetMaskQueryKey = customQueryKeys.orgCapabilitiesGetMask;
/**
 * Query hook for orgCapabilitiesGetMask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilitiesGetMaskQuery({ variables: { ids } });
 *
 * if (data?.orgCapabilitiesGetMask) {
 *   console.log(data.orgCapabilitiesGetMask);
 * }
 * ```
 */
export function useOrgCapabilitiesGetMaskQuery<
  TData = {
    orgCapabilitiesGetMask: string | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilitiesGetMaskQuery<
  TData = {
    orgCapabilitiesGetMask: string | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: orgCapabilitiesGetMaskQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetMask(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch orgCapabilitiesGetMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilitiesGetMaskQuery({ variables: { ids } });
 * ```
 */
export async function fetchOrgCapabilitiesGetMaskQuery(params?: {
  variables?: OrgCapabilitiesGetMaskVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.orgCapabilitiesGetMask(variables).unwrap();
}
/**
 * Prefetch orgCapabilitiesGetMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilitiesGetMaskQuery(queryClient, { variables: { ids } });
 * ```
 */
export async function prefetchOrgCapabilitiesGetMaskQuery(
  queryClient: QueryClient,
  params?: {
    variables?: OrgCapabilitiesGetMaskVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: orgCapabilitiesGetMaskQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetMask(variables).unwrap(),
  });
}
