/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgCapabilityDefaultCapabilityKeys } from '../query-keys';
import type {
  OrgCapabilityDefaultCapabilitySelect,
  OrgCapabilityDefaultCapabilityWithRelations,
  OrgCapabilityDefaultCapabilityFilter,
  OrgCapabilityDefaultCapabilityOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgCapabilityDefaultCapabilitySelect,
  OrgCapabilityDefaultCapabilityWithRelations,
  OrgCapabilityDefaultCapabilityFilter,
  OrgCapabilityDefaultCapabilityOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilityDefaultCapabilitiesQueryKey = orgCapabilityDefaultCapabilityKeys.list;
/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilityDefaultCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgCapabilityDefaultCapabilitiesQuery<
  S extends OrgCapabilityDefaultCapabilitySelect,
  TData = {
    orgCapabilityDefaultCapabilities: ConnectionResult<
      InferSelectResult<OrgCapabilityDefaultCapabilityWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<
        S,
        OrgCapabilityDefaultCapabilityFilter,
        OrgCapabilityDefaultCapabilityOrderBy
      >,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgCapabilityDefaultCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilityDefaultCapabilities: ConnectionResult<
          InferSelectResult<OrgCapabilityDefaultCapabilityWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilityDefaultCapabilitiesQuery(
  params: {
    selection: ListSelectionConfig<
      OrgCapabilityDefaultCapabilitySelect,
      OrgCapabilityDefaultCapabilityFilter,
      OrgCapabilityDefaultCapabilityOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgCapabilityDefaultCapabilitySelect,
    OrgCapabilityDefaultCapabilityFilter,
    OrgCapabilityDefaultCapabilityOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgCapabilityDefaultCapabilityKeys.list(args),
    queryFn: () => getClient().orgCapabilityDefaultCapability.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilityDefaultCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgCapabilityDefaultCapabilitiesQuery<
  S extends OrgCapabilityDefaultCapabilitySelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<
      S,
      OrgCapabilityDefaultCapabilityFilter,
      OrgCapabilityDefaultCapabilityOrderBy
    >,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, OrgCapabilityDefaultCapabilitySelect>;
}): Promise<{
  orgCapabilityDefaultCapabilities: ConnectionResult<
    InferSelectResult<OrgCapabilityDefaultCapabilityWithRelations, S>
  >;
}>;
export async function fetchOrgCapabilityDefaultCapabilitiesQuery(params: {
  selection: ListSelectionConfig<
    OrgCapabilityDefaultCapabilitySelect,
    OrgCapabilityDefaultCapabilityFilter,
    OrgCapabilityDefaultCapabilityOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    OrgCapabilityDefaultCapabilitySelect,
    OrgCapabilityDefaultCapabilityFilter,
    OrgCapabilityDefaultCapabilityOrderBy
  >(params.selection);
  return getClient().orgCapabilityDefaultCapability.findMany(args).unwrap();
}
/**
 * Join table linking capability defaults to individual capabilities; recompute trigger rebuilds the defaults bitmask
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilityDefaultCapabilitiesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgCapabilityDefaultCapabilitiesQuery<
  S extends OrgCapabilityDefaultCapabilitySelect,
>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<
        S,
        OrgCapabilityDefaultCapabilityFilter,
        OrgCapabilityDefaultCapabilityOrderBy
      >,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgCapabilityDefaultCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchOrgCapabilityDefaultCapabilitiesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      OrgCapabilityDefaultCapabilitySelect,
      OrgCapabilityDefaultCapabilityFilter,
      OrgCapabilityDefaultCapabilityOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgCapabilityDefaultCapabilitySelect,
    OrgCapabilityDefaultCapabilityFilter,
    OrgCapabilityDefaultCapabilityOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgCapabilityDefaultCapabilityKeys.list(args),
    queryFn: () => getClient().orgCapabilityDefaultCapability.findMany(args).unwrap(),
  });
}
