/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgProfileKeys } from '../query-keys';
import type { OrgProfileSelect, OrgProfileWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { OrgProfileSelect, OrgProfileWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgProfileQueryKey = orgProfileKeys.detail;
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgProfileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgProfileQuery<
  S extends OrgProfileSelect,
  TData = {
    orgProfile: InferSelectResult<OrgProfileWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgProfileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgProfile: InferSelectResult<OrgProfileWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgProfileQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgProfileSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgProfileSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgProfileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgProfile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```ts
 * const data = await fetchOrgProfileQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgProfileQuery<S extends OrgProfileSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgProfileSelect>;
}): Promise<{
  orgProfile: InferSelectResult<OrgProfileWithRelations, S> | null;
}>;
export async function fetchOrgProfileQuery(params: {
  id: string;
  selection: SelectionConfig<OrgProfileSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgProfileSelect>(params.selection);
  return getClient()
    .orgProfile.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```ts
 * await prefetchOrgProfileQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgProfileQuery<S extends OrgProfileSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgProfileSelect>;
  }
): Promise<void>;
export async function prefetchOrgProfileQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgProfileSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgProfileSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgProfileKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgProfile.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
