/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgCapabilityKeys } from '../query-keys';
import type { OrgCapabilitySelect, OrgCapabilityWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { OrgCapabilitySelect, OrgCapabilityWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilityQueryKey = orgCapabilityKeys.detail;
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgCapabilityQuery<
  S extends OrgCapabilitySelect,
  TData = {
    orgCapability: InferSelectResult<OrgCapabilityWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgCapability: InferSelectResult<OrgCapabilityWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilityQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgCapabilitySelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgCapabilitySelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgCapabilityQuery<S extends OrgCapabilitySelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgCapabilitySelect>;
}): Promise<{
  orgCapability: InferSelectResult<OrgCapabilityWithRelations, S> | null;
}>;
export async function fetchOrgCapabilityQuery(params: {
  id: string;
  selection: SelectionConfig<OrgCapabilitySelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgCapabilitySelect>(params.selection);
  return getClient()
    .orgCapability.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilityQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgCapabilityQuery<S extends OrgCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchOrgCapabilityQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgCapabilitySelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgCapabilitySelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
