/**
 * Audit log of capability additions and removals from profile definitions
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgProfileDefinitionGrantKeys } from '../query-keys';
import type {
  OrgProfileDefinitionGrantSelect,
  OrgProfileDefinitionGrantWithRelations,
  OrgProfileDefinitionGrantFilter,
  OrgProfileDefinitionGrantOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgProfileDefinitionGrantSelect,
  OrgProfileDefinitionGrantWithRelations,
  OrgProfileDefinitionGrantFilter,
  OrgProfileDefinitionGrantOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgProfileDefinitionGrantsQueryKey = orgProfileDefinitionGrantKeys.list;
/**
 * Audit log of capability additions and removals from profile definitions
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgProfileDefinitionGrantsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgProfileDefinitionGrantsQuery<
  S extends OrgProfileDefinitionGrantSelect,
  TData = {
    orgProfileDefinitionGrants: ConnectionResult<
      InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>
    >;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, OrgProfileDefinitionGrantFilter, OrgProfileDefinitionGrantOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgProfileDefinitionGrantSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgProfileDefinitionGrants: ConnectionResult<
          InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>
        >;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgProfileDefinitionGrantsQuery(
  params: {
    selection: ListSelectionConfig<
      OrgProfileDefinitionGrantSelect,
      OrgProfileDefinitionGrantFilter,
      OrgProfileDefinitionGrantOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgProfileDefinitionGrantSelect,
    OrgProfileDefinitionGrantFilter,
    OrgProfileDefinitionGrantOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgProfileDefinitionGrantKeys.list(args),
    queryFn: () => getClient().orgProfileDefinitionGrant.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Audit log of capability additions and removals from profile definitions
 *
 * @example
 * ```ts
 * const data = await fetchOrgProfileDefinitionGrantsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgProfileDefinitionGrantsQuery<
  S extends OrgProfileDefinitionGrantSelect,
>(params: {
  selection: {
    fields: S;
  } & Omit<
    ListSelectionConfig<S, OrgProfileDefinitionGrantFilter, OrgProfileDefinitionGrantOrderBy>,
    'fields'
  > &
    HookStrictSelect<NoInfer<S>, OrgProfileDefinitionGrantSelect>;
}): Promise<{
  orgProfileDefinitionGrants: ConnectionResult<
    InferSelectResult<OrgProfileDefinitionGrantWithRelations, S>
  >;
}>;
export async function fetchOrgProfileDefinitionGrantsQuery(params: {
  selection: ListSelectionConfig<
    OrgProfileDefinitionGrantSelect,
    OrgProfileDefinitionGrantFilter,
    OrgProfileDefinitionGrantOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    OrgProfileDefinitionGrantSelect,
    OrgProfileDefinitionGrantFilter,
    OrgProfileDefinitionGrantOrderBy
  >(params.selection);
  return getClient().orgProfileDefinitionGrant.findMany(args).unwrap();
}
/**
 * Audit log of capability additions and removals from profile definitions
 *
 * @example
 * ```ts
 * await prefetchOrgProfileDefinitionGrantsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgProfileDefinitionGrantsQuery<
  S extends OrgProfileDefinitionGrantSelect,
>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<
      ListSelectionConfig<S, OrgProfileDefinitionGrantFilter, OrgProfileDefinitionGrantOrderBy>,
      'fields'
    > &
      HookStrictSelect<NoInfer<S>, OrgProfileDefinitionGrantSelect>;
  }
): Promise<void>;
export async function prefetchOrgProfileDefinitionGrantsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      OrgProfileDefinitionGrantSelect,
      OrgProfileDefinitionGrantFilter,
      OrgProfileDefinitionGrantOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgProfileDefinitionGrantSelect,
    OrgProfileDefinitionGrantFilter,
    OrgProfileDefinitionGrantOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgProfileDefinitionGrantKeys.list(args),
    queryFn: () => getClient().orgProfileDefinitionGrant.findMany(args).unwrap(),
  });
}
