/**
 * Records of individual capability grants and revocations for members via bitmask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgGrantKeys } from '../query-keys';
import type {
  OrgGrantSelect,
  OrgGrantWithRelations,
  OrgGrantFilter,
  OrgGrantOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgGrantSelect,
  OrgGrantWithRelations,
  OrgGrantFilter,
  OrgGrantOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgGrantsQueryKey = orgGrantKeys.list;
/**
 * Records of individual capability grants and revocations for members via bitmask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgGrantsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgGrantsQuery<
  S extends OrgGrantSelect,
  TData = {
    orgGrants: ConnectionResult<InferSelectResult<OrgGrantWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgGrantFilter, OrgGrantOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgGrantSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgGrants: ConnectionResult<InferSelectResult<OrgGrantWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgGrantsQuery(
  params: {
    selection: ListSelectionConfig<OrgGrantSelect, OrgGrantFilter, OrgGrantOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<OrgGrantSelect, OrgGrantFilter, OrgGrantOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgGrantKeys.list(args),
    queryFn: () => getClient().orgGrant.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Records of individual capability grants and revocations for members via bitmask
 *
 * @example
 * ```ts
 * const data = await fetchOrgGrantsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgGrantsQuery<S extends OrgGrantSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgGrantFilter, OrgGrantOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgGrantSelect>;
}): Promise<{
  orgGrants: ConnectionResult<InferSelectResult<OrgGrantWithRelations, S>>;
}>;
export async function fetchOrgGrantsQuery(params: {
  selection: ListSelectionConfig<OrgGrantSelect, OrgGrantFilter, OrgGrantOrderBy>;
}) {
  const args = buildListSelectionArgs<OrgGrantSelect, OrgGrantFilter, OrgGrantOrderBy>(
    params.selection
  );
  return getClient().orgGrant.findMany(args).unwrap();
}
/**
 * Records of individual capability grants and revocations for members via bitmask
 *
 * @example
 * ```ts
 * await prefetchOrgGrantsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgGrantsQuery<S extends OrgGrantSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgGrantFilter, OrgGrantOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgGrantSelect>;
  }
): Promise<void>;
export async function prefetchOrgGrantsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgGrantSelect, OrgGrantFilter, OrgGrantOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<OrgGrantSelect, OrgGrantFilter, OrgGrantOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: orgGrantKeys.list(args),
    queryFn: () => getClient().orgGrant.findMany(args).unwrap(),
  });
}
