/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgCapabilityKeys } from '../query-keys';
import type {
  OrgCapabilitySelect,
  OrgCapabilityWithRelations,
  OrgCapabilityFilter,
  OrgCapabilityOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgCapabilitySelect,
  OrgCapabilityWithRelations,
  OrgCapabilityFilter,
  OrgCapabilityOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilitiesQueryKey = orgCapabilityKeys.list;
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgCapabilitiesQuery<
  S extends OrgCapabilitySelect,
  TData = {
    orgCapabilities: ConnectionResult<InferSelectResult<OrgCapabilityWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgCapabilityFilter, OrgCapabilityOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilities: ConnectionResult<InferSelectResult<OrgCapabilityWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilitiesQuery(
  params: {
    selection: ListSelectionConfig<OrgCapabilitySelect, OrgCapabilityFilter, OrgCapabilityOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgCapabilitySelect,
    OrgCapabilityFilter,
    OrgCapabilityOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgCapabilityKeys.list(args),
    queryFn: () => getClient().orgCapability.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilitiesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgCapabilitiesQuery<S extends OrgCapabilitySelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgCapabilityFilter, OrgCapabilityOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgCapabilitySelect>;
}): Promise<{
  orgCapabilities: ConnectionResult<InferSelectResult<OrgCapabilityWithRelations, S>>;
}>;
export async function fetchOrgCapabilitiesQuery(params: {
  selection: ListSelectionConfig<OrgCapabilitySelect, OrgCapabilityFilter, OrgCapabilityOrderBy>;
}) {
  const args = buildListSelectionArgs<
    OrgCapabilitySelect,
    OrgCapabilityFilter,
    OrgCapabilityOrderBy
  >(params.selection);
  return getClient().orgCapability.findMany(args).unwrap();
}
/**
 * Defines available capabilities as named bits within a bitmask, used by the RBAC system for access control
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilitiesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgCapabilitiesQuery<S extends OrgCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgCapabilityFilter, OrgCapabilityOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchOrgCapabilitiesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgCapabilitySelect, OrgCapabilityFilter, OrgCapabilityOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgCapabilitySelect,
    OrgCapabilityFilter,
    OrgCapabilityOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgCapabilityKeys.list(args),
    queryFn: () => getClient().orgCapability.findMany(args).unwrap(),
  });
}
