/**
 * Custom query hook for orgCapabilitiesGetPaddedMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { OrgCapabilitiesGetPaddedMaskVariables } from '../../orm/query';
export type { OrgCapabilitiesGetPaddedMaskVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilitiesGetPaddedMaskQueryKey = customQueryKeys.orgCapabilitiesGetPaddedMask;
/**
 * Query hook for orgCapabilitiesGetPaddedMask
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilitiesGetPaddedMaskQuery({ variables: { mask } });
 *
 * if (data?.orgCapabilitiesGetPaddedMask) {
 *   console.log(data.orgCapabilitiesGetPaddedMask);
 * }
 * ```
 */
export function useOrgCapabilitiesGetPaddedMaskQuery<
  TData = {
    orgCapabilitiesGetPaddedMask: string | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetPaddedMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetPaddedMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilitiesGetPaddedMaskQuery<
  TData = {
    orgCapabilitiesGetPaddedMask: string | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetPaddedMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetPaddedMask: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: orgCapabilitiesGetPaddedMaskQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetPaddedMask(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch orgCapabilitiesGetPaddedMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilitiesGetPaddedMaskQuery({ variables: { mask } });
 * ```
 */
export async function fetchOrgCapabilitiesGetPaddedMaskQuery(params?: {
  variables?: OrgCapabilitiesGetPaddedMaskVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.orgCapabilitiesGetPaddedMask(variables).unwrap();
}
/**
 * Prefetch orgCapabilitiesGetPaddedMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilitiesGetPaddedMaskQuery(queryClient, { variables: { mask } });
 * ```
 */
export async function prefetchOrgCapabilitiesGetPaddedMaskQuery(
  queryClient: QueryClient,
  params?: {
    variables?: OrgCapabilitiesGetPaddedMaskVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: orgCapabilitiesGetPaddedMaskQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetPaddedMask(variables).unwrap(),
  });
}
