/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgMembershipKeys } from '../query-keys';
import type { OrgMembershipSelect, OrgMembershipWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { OrgMembershipSelect, OrgMembershipWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgMembershipQueryKey = orgMembershipKeys.detail;
/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgMembershipQuery<
  S extends OrgMembershipSelect,
  TData = {
    orgMembership: InferSelectResult<OrgMembershipWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgMembershipSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgMembership: InferSelectResult<OrgMembershipWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgMembershipQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgMembershipSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgMembershipSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgMembershipKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgMembership.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 *
 * @example
 * ```ts
 * const data = await fetchOrgMembershipQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgMembershipQuery<S extends OrgMembershipSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgMembershipSelect>;
}): Promise<{
  orgMembership: InferSelectResult<OrgMembershipWithRelations, S> | null;
}>;
export async function fetchOrgMembershipQuery(params: {
  id: string;
  selection: SelectionConfig<OrgMembershipSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgMembershipSelect>(params.selection);
  return getClient()
    .orgMembership.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgMembershipQuery<S extends OrgMembershipSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgMembershipSelect>;
  }
): Promise<void>;
export async function prefetchOrgMembershipQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgMembershipSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgMembershipSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgMembershipKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgMembership.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
