/**
 * Custom query hook for orgCapabilitiesGetByMask
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { OrgCapabilitiesGetByMaskVariables } from '../../orm/query';
import type { OrgCapabilityConnection } from '../../orm/input-types';
export type { OrgCapabilitiesGetByMaskVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilitiesGetByMaskQueryKey = customQueryKeys.orgCapabilitiesGetByMask;
/**
 * Reads and enables pagination through a set of `OrgCapability`.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilitiesGetByMaskQuery({ variables: { mask, first, offset, after } });
 *
 * if (data?.orgCapabilitiesGetByMask) {
 *   console.log(data.orgCapabilitiesGetByMask);
 * }
 * ```
 */
export function useOrgCapabilitiesGetByMaskQuery<
  TData = {
    orgCapabilitiesGetByMask: OrgCapabilityConnection | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetByMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetByMask: OrgCapabilityConnection | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilitiesGetByMaskQuery<
  TData = {
    orgCapabilitiesGetByMask: OrgCapabilityConnection | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetByMaskVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetByMask: OrgCapabilityConnection | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: orgCapabilitiesGetByMaskQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetByMask(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch orgCapabilitiesGetByMask without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilitiesGetByMaskQuery({ variables: { mask, first, offset, after } });
 * ```
 */
export async function fetchOrgCapabilitiesGetByMaskQuery(params?: {
  variables?: OrgCapabilitiesGetByMaskVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.orgCapabilitiesGetByMask(variables).unwrap();
}
/**
 * Prefetch orgCapabilitiesGetByMask for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilitiesGetByMaskQuery(queryClient, { variables: { mask, first, offset, after } });
 * ```
 */
export async function prefetchOrgCapabilitiesGetByMaskQuery(
  queryClient: QueryClient,
  params?: {
    variables?: OrgCapabilitiesGetByMaskVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: orgCapabilitiesGetByMaskQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetByMask(variables).unwrap(),
  });
}
