/**
 * Custom query hook for orgCapabilitiesGetMaskByNames
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { customQueryKeys } from '../query-keys';
import type { OrgCapabilitiesGetMaskByNamesVariables } from '../../orm/query';
export type { OrgCapabilitiesGetMaskByNamesVariables } from '../../orm/query';
/** Query key factory - re-exported from query-keys.ts */
export const orgCapabilitiesGetMaskByNamesQueryKey = customQueryKeys.orgCapabilitiesGetMaskByNames;
/**
 * Query hook for orgCapabilitiesGetMaskByNames
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgCapabilitiesGetMaskByNamesQuery({ variables: { names } });
 *
 * if (data?.orgCapabilitiesGetMaskByNames) {
 *   console.log(data.orgCapabilitiesGetMaskByNames);
 * }
 * ```
 */
export function useOrgCapabilitiesGetMaskByNamesQuery<
  TData = {
    orgCapabilitiesGetMaskByNames: string | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetMaskByNamesVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetMaskByNames: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgCapabilitiesGetMaskByNamesQuery<
  TData = {
    orgCapabilitiesGetMaskByNames: string | null;
  },
>(
  params?: {
    variables?: OrgCapabilitiesGetMaskByNamesVariables;
  } & Omit<
    UseQueryOptions<
      {
        orgCapabilitiesGetMaskByNames: string | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData> {
  const variables = params?.variables ?? {};
  const { variables: _variables, ...queryOptions } = params ?? {};
  void _variables;
  return useQuery({
    queryKey: orgCapabilitiesGetMaskByNamesQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetMaskByNames(variables).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch orgCapabilitiesGetMaskByNames without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchOrgCapabilitiesGetMaskByNamesQuery({ variables: { names } });
 * ```
 */
export async function fetchOrgCapabilitiesGetMaskByNamesQuery(params?: {
  variables?: OrgCapabilitiesGetMaskByNamesVariables;
}) {
  const variables = params?.variables ?? {};
  return getClient().query.orgCapabilitiesGetMaskByNames(variables).unwrap();
}
/**
 * Prefetch orgCapabilitiesGetMaskByNames for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchOrgCapabilitiesGetMaskByNamesQuery(queryClient, { variables: { names } });
 * ```
 */
export async function prefetchOrgCapabilitiesGetMaskByNamesQuery(
  queryClient: QueryClient,
  params?: {
    variables?: OrgCapabilitiesGetMaskByNamesVariables;
  }
): Promise<void> {
  const variables = params?.variables ?? {};
  await queryClient.prefetchQuery({
    queryKey: orgCapabilitiesGetMaskByNamesQueryKey(variables),
    queryFn: () => getClient().query.orgCapabilitiesGetMaskByNames(variables).unwrap(),
  });
}
