/**
 * Join table linking profiles to individual capabilities they include
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { orgProfileCapabilityKeys } from '../query-keys';
import type {
  OrgProfileCapabilitySelect,
  OrgProfileCapabilityWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  OrgProfileCapabilitySelect,
  OrgProfileCapabilityWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgProfileCapabilityQueryKey = orgProfileCapabilityKeys.detail;
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgProfileCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useOrgProfileCapabilityQuery<
  S extends OrgProfileCapabilitySelect,
  TData = {
    orgProfileCapability: InferSelectResult<OrgProfileCapabilityWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgProfileCapabilitySelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgProfileCapability: InferSelectResult<OrgProfileCapabilityWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgProfileCapabilityQuery(
  params: {
    id: string;
    selection: SelectionConfig<OrgProfileCapabilitySelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<OrgProfileCapabilitySelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgProfileCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgProfileCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```ts
 * const data = await fetchOrgProfileCapabilityQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchOrgProfileCapabilityQuery<S extends OrgProfileCapabilitySelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, OrgProfileCapabilitySelect>;
}): Promise<{
  orgProfileCapability: InferSelectResult<OrgProfileCapabilityWithRelations, S> | null;
}>;
export async function fetchOrgProfileCapabilityQuery(params: {
  id: string;
  selection: SelectionConfig<OrgProfileCapabilitySelect>;
}): Promise<any> {
  const args = buildSelectionArgs<OrgProfileCapabilitySelect>(params.selection);
  return getClient()
    .orgProfileCapability.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Join table linking profiles to individual capabilities they include
 *
 * @example
 * ```ts
 * await prefetchOrgProfileCapabilityQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchOrgProfileCapabilityQuery<S extends OrgProfileCapabilitySelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, OrgProfileCapabilitySelect>;
  }
): Promise<void>;
export async function prefetchOrgProfileCapabilityQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<OrgProfileCapabilitySelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<OrgProfileCapabilitySelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgProfileCapabilityKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .orgProfileCapability.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
