/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgProfileKeys } from '../query-keys';
import type {
  OrgProfileSelect,
  OrgProfileWithRelations,
  OrgProfileFilter,
  OrgProfileOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgProfileSelect,
  OrgProfileWithRelations,
  OrgProfileFilter,
  OrgProfileOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgProfilesQueryKey = orgProfileKeys.list;
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgProfilesQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgProfilesQuery<
  S extends OrgProfileSelect,
  TData = {
    orgProfiles: ConnectionResult<InferSelectResult<OrgProfileWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgProfileFilter, OrgProfileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgProfileSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgProfiles: ConnectionResult<InferSelectResult<OrgProfileWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgProfilesQuery(
  params: {
    selection: ListSelectionConfig<OrgProfileSelect, OrgProfileFilter, OrgProfileOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<OrgProfileSelect, OrgProfileFilter, OrgProfileOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgProfileKeys.list(args),
    queryFn: () => getClient().orgProfile.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```ts
 * const data = await fetchOrgProfilesQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgProfilesQuery<S extends OrgProfileSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgProfileFilter, OrgProfileOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgProfileSelect>;
}): Promise<{
  orgProfiles: ConnectionResult<InferSelectResult<OrgProfileWithRelations, S>>;
}>;
export async function fetchOrgProfilesQuery(params: {
  selection: ListSelectionConfig<OrgProfileSelect, OrgProfileFilter, OrgProfileOrderBy>;
}) {
  const args = buildListSelectionArgs<OrgProfileSelect, OrgProfileFilter, OrgProfileOrderBy>(
    params.selection
  );
  return getClient().orgProfile.findMany(args).unwrap();
}
/**
 * Named capability bundles (roles) that group multiple capabilities into reusable profiles
 *
 * @example
 * ```ts
 * await prefetchOrgProfilesQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgProfilesQuery<S extends OrgProfileSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgProfileFilter, OrgProfileOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgProfileSelect>;
  }
): Promise<void>;
export async function prefetchOrgProfilesQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgProfileSelect, OrgProfileFilter, OrgProfileOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<OrgProfileSelect, OrgProfileFilter, OrgProfileOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: orgProfileKeys.list(args),
    queryFn: () => getClient().orgProfile.findMany(args).unwrap(),
  });
}
