/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { orgMembershipKeys } from '../query-keys';
import type {
  OrgMembershipSelect,
  OrgMembershipWithRelations,
  OrgMembershipFilter,
  OrgMembershipOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  OrgMembershipSelect,
  OrgMembershipWithRelations,
  OrgMembershipFilter,
  OrgMembershipOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const orgMembershipsQueryKey = orgMembershipKeys.list;
/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useOrgMembershipsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useOrgMembershipsQuery<
  S extends OrgMembershipSelect,
  TData = {
    orgMemberships: ConnectionResult<InferSelectResult<OrgMembershipWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgMembershipFilter, OrgMembershipOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgMembershipSelect>;
  } & Omit<
    UseQueryOptions<
      {
        orgMemberships: ConnectionResult<InferSelectResult<OrgMembershipWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useOrgMembershipsQuery(
  params: {
    selection: ListSelectionConfig<OrgMembershipSelect, OrgMembershipFilter, OrgMembershipOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    OrgMembershipSelect,
    OrgMembershipFilter,
    OrgMembershipOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: orgMembershipKeys.list(args),
    queryFn: () => getClient().orgMembership.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 *
 * @example
 * ```ts
 * const data = await fetchOrgMembershipsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchOrgMembershipsQuery<S extends OrgMembershipSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, OrgMembershipFilter, OrgMembershipOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, OrgMembershipSelect>;
}): Promise<{
  orgMemberships: ConnectionResult<InferSelectResult<OrgMembershipWithRelations, S>>;
}>;
export async function fetchOrgMembershipsQuery(params: {
  selection: ListSelectionConfig<OrgMembershipSelect, OrgMembershipFilter, OrgMembershipOrderBy>;
}) {
  const args = buildListSelectionArgs<
    OrgMembershipSelect,
    OrgMembershipFilter,
    OrgMembershipOrderBy
  >(params.selection);
  return getClient().orgMembership.findMany(args).unwrap();
}
/**
 * Tracks membership records linking actors to entities with capability bitmasks, ownership, and admin status
 *
 * @example
 * ```ts
 * await prefetchOrgMembershipsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchOrgMembershipsQuery<S extends OrgMembershipSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, OrgMembershipFilter, OrgMembershipOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, OrgMembershipSelect>;
  }
): Promise<void>;
export async function prefetchOrgMembershipsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<OrgMembershipSelect, OrgMembershipFilter, OrgMembershipOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    OrgMembershipSelect,
    OrgMembershipFilter,
    OrgMembershipOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: orgMembershipKeys.list(args),
    queryFn: () => getClient().orgMembership.findMany(args).unwrap(),
  });
}
