-- Revert: schemas/myapp_events_public/tables/app_event_aggregates/triggers/app_event_aggregates_after_insert_update_tgr


DROP TRIGGER app_event_aggregates_after_insert_update_tgr ON myapp_events_public.app_event_aggregates;


