-- Revert: schemas/myapp_memberships_public/tables/org_membership_settings/indexes/org_membership_settings_updated_by_idx


DROP INDEX myapp_memberships_public.org_membership_settings_updated_by_idx;


