-- Revert: schemas/myapp_memberships_public/tables/org_membership_defaults/indexes/org_membership_defaults_created_at_idx


DROP INDEX myapp_memberships_public.org_membership_defaults_created_at_idx;


