-- Revert: schemas/myapp_profiles_public/tables/org_profile_definition_grants/triggers/org_profile_definition_grants_apply_trg


DROP TRIGGER org_profile_definition_grants_apply_trg ON myapp_profiles_public.org_profile_definition_grants;


