/**
 * Hook for fetching schemas within a specific database
 * @migrated Uses generated SDK execute adapter
 *
 * Note: This hook uses a custom query with nested relations (apiSchemas)
 * which isn't directly generated by the SDK. We use the execute function directly.
 */

import { useQuery } from '@tanstack/react-query';

import { executeSb } from '@/graphql/execute';

export interface LinkedApi {
	id: string;
	apiId: string;
	api: {
		id: string;
		name: string;
	} | null;
}

export interface DatabaseSchema {
	id: string;
	name: string;
	schemaName: string;
	label: string | null;
	description: string | null;
	databaseId: string;
	createdAt: string | null;
	updatedAt: string | null;
	apiSchemas: {
		nodes: LinkedApi[];
	};
}

interface DatabaseSchemasQueryResult {
	schemas: {
		nodes: DatabaseSchema[];
		totalCount: number;
	};
}

// Custom query with nested relations
const DATABASE_SCHEMAS_QUERY = `
	query DatabaseSchemas($databaseId: UUID!) {
		schemas(condition: { databaseId: $databaseId }, orderBy: NAME_ASC) {
			nodes {
				id
				name
				schemaName
				label
				description
				databaseId
				createdAt
				updatedAt
				apiSchemas {
					nodes {
						id
						apiId
						api {
							id
							name
						}
					}
				}
			}
			totalCount
		}
	}
`;

export interface UseDatabaseSchemasOptions {
	/** Database ID to fetch schemas for */
	databaseId: string;
	/** Enable/disable the query */
	enabled?: boolean;
}

export interface UseDatabaseSchemasResult {
	/** Array of schema objects */
	schemas: DatabaseSchema[];
	/** Total count of all schemas */
	totalCount: number;
	/** Loading state */
	isLoading: boolean;
	/** Error state */
	error: Error | null;
	/** Refetch function */
	refetch: () => Promise<unknown>;
}

/**
 * Hook for fetching schemas within a specific database
 */
export function useDatabaseSchemas(options: UseDatabaseSchemasOptions): UseDatabaseSchemasResult {
	const { databaseId, enabled = true } = options;
	const isEnabled = enabled && Boolean(databaseId);

	const { data, isLoading, error, refetch } = useQuery<DatabaseSchemasQueryResult, Error>({
		queryKey: databaseSchemasQueryKeys.byDatabase(databaseId),
		queryFn: async () => {
			const result = (await executeSb(DATABASE_SCHEMAS_QUERY, {
				databaseId,
			})) as DatabaseSchemasQueryResult;
			return result;
		},
		enabled: isEnabled,
		staleTime: 5 * 60 * 1000,
		refetchOnMount: isEnabled ? 'always' : false,
		refetchOnWindowFocus: 'always',
		refetchOnReconnect: 'always',
	});

	const schemas = data?.schemas?.nodes ?? [];
	const totalCount = data?.schemas?.totalCount ?? 0;

	return {
		schemas,
		totalCount,
		isLoading,
		error,
		refetch,
	};
}

/**
 * Generate query keys for consistent cache management
 */
export const databaseSchemasQueryKeys = {
	all: ['database-schemas'] as const,
	byDatabase: (databaseId: string) => [...databaseSchemasQueryKeys.all, { databaseId }] as const,
};
