-- Revert: schemas/myapp_profiles_public/tables/org_profile_definition_grants/indexes/org_profile_definition_grants_permission_id_idx


DROP INDEX myapp_profiles_public.org_profile_definition_grants_permission_id_idx;


