'use client';

import { useMemo, useState } from 'react';
import { Button } from '@constructive-io/ui/button';
import { ResponsiveDiagram } from '@constructive-io/ui/responsive-diagram';
import { ScrollArea } from '@constructive-io/ui/scroll-area';
import type { CardComponent } from '@constructive-io/ui/stack';

import { getDefaultFormValues } from '../policy-hooks';
import { PolicyConfigForm } from '../policy-config-form';
import { PolicyDiagramByKey } from '../policy-diagram';
import type { MergedPolicyType } from '../policy-types';

export interface CompositeConditionEditCardProps {
	policyType: MergedPolicyType;
	policyData: Record<string, unknown>;
	onSave: (policyData: Record<string, unknown>) => void;
}

/**
 * Card for editing a single condition in a composite policy.
 * Similar layout to PolicyEditCard but without role/enabled settings.
 */
export const CompositeConditionEditCard: CardComponent<CompositeConditionEditCardProps> = ({
	policyType,
	policyData: initialPolicyData,
	onSave,
	card,
}) => {
	// Merge initial data with defaults so empty fields show default values
	const mergedInitialData = useMemo(() => {
		const defaults = getDefaultFormValues(policyType);
		return { ...defaults, ...initialPolicyData };
	}, [policyType, initialPolicyData]);

	const [policyData, setPolicyData] = useState<Record<string, unknown>>(mergedInitialData);

	const handleSave = () => {
		onSave(policyData);
		card.close();
	};

	const PolicyIcon = policyType.icon;

	return (
		<div className='flex h-full flex-col'>
			<ScrollArea className='min-h-0 flex-1'>
				<div className='space-y-6 p-6'>
					{/* Policy Header */}
					<div className='space-y-4'>
						<div className='flex items-start gap-3'>
							<div className='bg-primary/10 flex size-10 shrink-0 items-center justify-center rounded-lg'>
								<PolicyIcon className='text-primary size-5' />
							</div>
							<div className='min-w-0 flex-1'>
								<h3 className='font-semibold'>{policyType.title}</h3>
								<p className='text-muted-foreground text-sm'>{policyType.tagline}</p>
							</div>
						</div>

						{/* Policy Diagram */}
						<ResponsiveDiagram>
							<PolicyDiagramByKey
								diagramKey={policyType.diagramKey ?? 'allow-all'}
								tableName='table'
								config={policyData}
							/>
						</ResponsiveDiagram>
					</div>

					{/* Access Rule Config */}
					<div className='space-y-3'>
						<p className='text-muted-foreground text-xs font-semibold tracking-wide uppercase'>Access Rule Config</p>
						<PolicyConfigForm
							policyType={policyType}
							value={policyData}
							onChange={setPolicyData}
							hideAutoGeneratedInfo
							flattenAdvanced
						/>
					</div>
				</div>
			</ScrollArea>

			<div className='flex justify-end gap-2 border-t px-4 py-3'>
				<Button type='button' variant='outline' onClick={() => card.close()}>
					Cancel
				</Button>
				<Button type='button' onClick={handleSave}>
					Save
				</Button>
			</div>
		</div>
	);
};
