-- Revert: schemas/myapp_permissions_public/tables/app_permission_defaults/triggers/app_permission_defaults_insert_trg


DROP TRIGGER app_permission_defaults_insert_trg ON myapp_permissions_public.app_permission_defaults;


